
#pragma once
enum tokenType {
    cantmove_token,
    linecomment_token,
    hex_uwb_token,
    octal_token,
    exc_token,
    hex_l_token,
    amp_token,
    semicolon_token,
    decimal_ll_token,
    whitespace_token,
    decimal_u_token,
    fraction_token,
    lbracket_token,
    decimal_lu_token,
    shiftright_token,
    div_token,
    hex_ll_token,
    bnoteq_token,
    minus_token,
    decimal_wb_token,
    lcurly_token,
    tilde_token,
    le_token,
    decimal_l_token,
    modeq_token,
    langle_token,
    oct_ll_token,
    oct_lu_token,
    decimalfraction_token,
    hex_ull_token,
    colon_token,
    shiftleft_token,
    assignment_token,
    preproc_token,
    decimal_token,
    decimal_uwb_token,
    dot_token,
    caret_token,
    and_token,
    boreq_token,
    blockcomment_token,
    newline_token,
    minuseq_token,
    oct_l_token,
    hex_lu_token,
    oct_u_token,
    pipe_token,
    hexadecimal_token,
    star_token,
    mod_token,
    timeseq_token,
    eof_token,
    question_token,
    plus_token,
    comma_token,
    noteq_token,
    lor_token,
    stringliteral_token,
    xoreq_token,
    identifier_token,
    hexfraction_token,
    ge_token,
    oct_ull_token,
    charliteral_token,
    bandeq_token,
    hex_u_token,
    oct_uwb_token,
    hex_wb_token,
    eq_token,
    lparen_token,
    bad_token,
    decimal_ull_token,
    oct_wb_token,
    arrow_token,
    rcurly_token,
    pluseq_token,
    rangle_token,
    rbracket_token,
    rparen_token,
    TOKENCOUNT
};

static const char* tokenTypeStrings[TOKENCOUNT] = {
    "cantmove",
    "linecomment",
    "hex_uwb",
    "octal",
    "exc",
    "hex_l",
    "amp",
    "semicolon",
    "decimal_ll",
    "whitespace",
    "decimal_u",
    "fraction",
    "lbracket",
    "decimal_lu",
    "shiftright",
    "div",
    "hex_ll",
    "bnoteq",
    "minus",
    "decimal_wb",
    "lcurly",
    "tilde",
    "le",
    "decimal_l",
    "modeq",
    "langle",
    "oct_ll",
    "oct_lu",
    "decimalfraction",
    "hex_ull",
    "colon",
    "shiftleft",
    "assignment",
    "preproc",
    "decimal",
    "decimal_uwb",
    "dot",
    "caret",
    "and",
    "boreq",
    "blockcomment",
    "newline",
    "minuseq",
    "oct_l",
    "hex_lu",
    "oct_u",
    "pipe",
    "hexadecimal",
    "star",
    "mod",
    "timeseq",
    "eof",
    "question",
    "plus",
    "comma",
    "noteq",
    "lor",
    "stringliteral",
    "xoreq",
    "identifier",
    "hexfraction",
    "ge",
    "oct_ull",
    "charliteral",
    "bandeq",
    "hex_u",
    "oct_uwb",
    "hex_wb",
    "eq",
    "lparen",
    "bad",
    "decimal_ull",
    "oct_wb",
    "arrow",
    "rcurly",
    "pluseq",
    "rangle",
    "rbracket",
    "rparen"
};

static const char* tokenTypeColors[TOKENCOUNT] = {
    "\033[38;2;244;71;71m",
    "\033[38;2;106;153;85m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;255;215;0m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;255;215;0m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;106;153;85m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;106;153;85m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;128;128;128m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;156;220;254m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;106;153;85m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;255;215;0m",
    "\033[38;2;244;71;71m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;255;215;0m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;255;215;0m",
    "\033[38;2;255;215;0m"
};

#define MAXCHAR 97

enum state {
    cantmove_state,
    newline_state,
    lparen_state,
    rparen_state,
    lcurly_state,
    rcurly_state,
    rbracket_state,
    lbracket_state,
    question_state,
    semicolon_state,
    colon_state,
    comma_state,
    dot_state,
    eof_state,
    start_state,
    identifier_state,
    modeq_state,
    mod_state,
    minuseq_state,
    arrow_state,
    minus_state,
    xoreq_state,
    caret_state,
    bnoteq_state,
    tilde_state,
    boreq_state,
    lor_state,
    pipe_state,
    eq_state,
    assignment_state,
    pluseq_state,
    plus_state,
    shiftleft_state,
    le_state,
    langle_state,
    shiftright_state,
    ge_state,
    rangle_state,
    div_state,
    linecomment_state,
    blockcomment_state,
    blockcommentweak_state,
    blockcommentfinish_state,
    bandeq_state,
    and_state,
    amp_state,
    timeseq_state,
    star_state,
    noteq_state,
    exc_state,
    preproc_state,
    whitespace_state,
    charliteralstart_state,
    charliteral_state,
    charliteralchewedone_state,
    charliteralescape_state,
    charescapeoctal0_state,
    charescapeoctal1_state,
    charescapehexempty_state,
    charescapehex_state,
    stringliteral_state,
    stringliteralstart_state,
    stringliteralescape_state,
    stringescapeoctal0_state,
    stringescapeoctal1_state,
    stringescapehexempty_state,
    stringescapehex_state,
    nondecimal_state,
    fraction_state,
    octal_state,
    oct_u_state,
    oct_lu_state,
    oct_l_state,
    oct_L_state,
    oct_w_state,
    oct_W_state,
    oct_ull_state,
    oct_ul_state,
    oct_uL_state,
    oct_uwb_state,
    oct_uw_state,
    oct_uW_state,
    oct_ll_state,
    oct_wb_state,
    hexfraction_state,
    hexadecimal_state,
    hex_u_state,
    hex_lu_state,
    hex_l_state,
    hex_L_state,
    hex_w_state,
    hex_W_state,
    hex_ull_state,
    hex_ul_state,
    hex_uL_state,
    hex_uwb_state,
    hex_uw_state,
    hex_uW_state,
    hex_ll_state,
    hex_wb_state,
    decimalfraction_state,
    decimal_state,
    decimal_u_state,
    decimal_lu_state,
    decimal_l_state,
    decimal_L_state,
    decimal_w_state,
    decimal_W_state,
    decimal_ull_state,
    decimal_ul_state,
    decimal_uL_state,
    decimal_uwb_state,
    decimal_uw_state,
    decimal_uW_state,
    decimal_ll_state,
    decimal_wb_state,
    STATECOUNT
};

static enum state stateMachine_transitions[STATECOUNT][MAXCHAR + 1] = {
    [start_state][52] = identifier_state,
    [start_state][53] = identifier_state,
    [start_state][54] = identifier_state,
    [start_state][3] = identifier_state,
    [start_state][4] = identifier_state,
    [start_state][6] = identifier_state,
    [start_state][56] = identifier_state,
    [start_state][59] = identifier_state,
    [start_state][11] = identifier_state,
    [start_state][60] = identifier_state,
    [start_state][61] = identifier_state,
    [start_state][62] = identifier_state,
    [start_state][63] = identifier_state,
    [start_state][64] = identifier_state,
    [start_state][65] = identifier_state,
    [start_state][66] = identifier_state,
    [start_state][14] = identifier_state,
    [start_state][15] = identifier_state,
    [start_state][68] = identifier_state,
    [start_state][17] = identifier_state,
    [start_state][69] = identifier_state,
    [start_state][71] = identifier_state,
    [start_state][18] = identifier_state,
    [start_state][19] = identifier_state,
    [start_state][72] = identifier_state,
    [start_state][21] = identifier_state,
    [start_state][73] = identifier_state,
    [start_state][22] = identifier_state,
    [start_state][75] = identifier_state,
    [start_state][77] = identifier_state,
    [start_state][24] = identifier_state,
    [start_state][81] = identifier_state,
    [start_state][26] = identifier_state,
    [start_state][27] = identifier_state,
    [start_state][28] = identifier_state,
    [start_state][30] = identifier_state,
    [start_state][83] = identifier_state,
    [start_state][32] = identifier_state,
    [start_state][31] = identifier_state,
    [start_state][34] = identifier_state,
    [start_state][85] = identifier_state,
    [start_state][84] = identifier_state,
    [start_state][87] = identifier_state,
    [start_state][89] = identifier_state,
    [start_state][90] = identifier_state,
    [start_state][39] = identifier_state,
    [start_state][91] = identifier_state,
    [start_state][92] = identifier_state,
    [start_state][94] = identifier_state,
    [start_state][95] = identifier_state,
    [start_state][96] = identifier_state,
    [start_state][48] = identifier_state,
    [start_state][49] = identifier_state,
    [start_state][97] = nondecimal_state,
    [start_state][12] = decimal_state,
    [start_state][25] = decimal_state,
    [start_state][42] = decimal_state,
    [start_state][79] = decimal_state,
    [start_state][16] = decimal_state,
    [start_state][45] = decimal_state,
    [start_state][33] = decimal_state,
    [start_state][9] = decimal_state,
    [start_state][38] = decimal_state,
    [start_state][51] = whitespace_state,
    [start_state][43] = whitespace_state,
    [start_state][8] = whitespace_state,
    [start_state][1] = newline_state,
    [start_state][40] = mod_state,
    [start_state][13] = minus_state,
    [start_state][86] = plus_state,
    [start_state][55] = caret_state,
    [start_state][23] = tilde_state,
    [start_state][88] = lparen_state,
    [start_state][7] = rparen_state,
    [start_state][70] = lcurly_state,
    [start_state][5] = rcurly_state,
    [start_state][35] = rbracket_state,
    [start_state][93] = lbracket_state,
    [start_state][82] = question_state,
    [start_state][76] = semicolon_state,
    [start_state][37] = colon_state,
    [start_state][58] = assignment_state,
    [start_state][78] = langle_state,
    [start_state][46] = rangle_state,
    [start_state][80] = div_state,
    [start_state][44] = star_state,
    [start_state][67] = preproc_state,
    [start_state][50] = amp_state,
    [start_state][20] = comma_state,
    [start_state][2] = dot_state,
    [start_state][47] = exc_state,
    [start_state][57] = stringliteralstart_state,
    [start_state][10] = pipe_state,
    [start_state][36] = charliteralstart_state,
    [start_state][29] = eof_state,
    [identifier_state][52] = identifier_state,
    [identifier_state][53] = identifier_state,
    [identifier_state][54] = identifier_state,
    [identifier_state][3] = identifier_state,
    [identifier_state][4] = identifier_state,
    [identifier_state][6] = identifier_state,
    [identifier_state][56] = identifier_state,
    [identifier_state][59] = identifier_state,
    [identifier_state][11] = identifier_state,
    [identifier_state][60] = identifier_state,
    [identifier_state][61] = identifier_state,
    [identifier_state][62] = identifier_state,
    [identifier_state][63] = identifier_state,
    [identifier_state][64] = identifier_state,
    [identifier_state][65] = identifier_state,
    [identifier_state][66] = identifier_state,
    [identifier_state][14] = identifier_state,
    [identifier_state][15] = identifier_state,
    [identifier_state][68] = identifier_state,
    [identifier_state][17] = identifier_state,
    [identifier_state][69] = identifier_state,
    [identifier_state][71] = identifier_state,
    [identifier_state][18] = identifier_state,
    [identifier_state][19] = identifier_state,
    [identifier_state][72] = identifier_state,
    [identifier_state][21] = identifier_state,
    [identifier_state][73] = identifier_state,
    [identifier_state][22] = identifier_state,
    [identifier_state][75] = identifier_state,
    [identifier_state][77] = identifier_state,
    [identifier_state][24] = identifier_state,
    [identifier_state][81] = identifier_state,
    [identifier_state][26] = identifier_state,
    [identifier_state][27] = identifier_state,
    [identifier_state][28] = identifier_state,
    [identifier_state][30] = identifier_state,
    [identifier_state][83] = identifier_state,
    [identifier_state][32] = identifier_state,
    [identifier_state][31] = identifier_state,
    [identifier_state][34] = identifier_state,
    [identifier_state][85] = identifier_state,
    [identifier_state][84] = identifier_state,
    [identifier_state][87] = identifier_state,
    [identifier_state][89] = identifier_state,
    [identifier_state][90] = identifier_state,
    [identifier_state][39] = identifier_state,
    [identifier_state][91] = identifier_state,
    [identifier_state][92] = identifier_state,
    [identifier_state][94] = identifier_state,
    [identifier_state][95] = identifier_state,
    [identifier_state][96] = identifier_state,
    [identifier_state][48] = identifier_state,
    [identifier_state][49] = identifier_state,
    [identifier_state][12] = identifier_state,
    [identifier_state][25] = identifier_state,
    [identifier_state][42] = identifier_state,
    [identifier_state][79] = identifier_state,
    [identifier_state][16] = identifier_state,
    [identifier_state][45] = identifier_state,
    [identifier_state][33] = identifier_state,
    [identifier_state][9] = identifier_state,
    [identifier_state][38] = identifier_state,
    [identifier_state][97] = identifier_state,
    [mod_state][58] = modeq_state,
    [minus_state][58] = minuseq_state,
    [minus_state][46] = arrow_state,
    [caret_state][58] = xoreq_state,
    [tilde_state][58] = bnoteq_state,
    [pipe_state][58] = boreq_state,
    [pipe_state][10] = lor_state,
    [assignment_state][58] = eq_state,
    [plus_state][58] = pluseq_state,
    [langle_state][78] = shiftleft_state,
    [langle_state][58] = le_state,
    [rangle_state][46] = shiftright_state,
    [rangle_state][58] = ge_state,
    [div_state][80] = linecomment_state,
    [div_state][44] = blockcomment_state,
    [linecomment_state][2] = linecomment_state,
    [linecomment_state][3] = linecomment_state,
    [linecomment_state][4] = linecomment_state,
    [linecomment_state][5] = linecomment_state,
    [linecomment_state][6] = linecomment_state,
    [linecomment_state][7] = linecomment_state,
    [linecomment_state][8] = linecomment_state,
    [linecomment_state][9] = linecomment_state,
    [linecomment_state][10] = linecomment_state,
    [linecomment_state][11] = linecomment_state,
    [linecomment_state][12] = linecomment_state,
    [linecomment_state][13] = linecomment_state,
    [linecomment_state][14] = linecomment_state,
    [linecomment_state][15] = linecomment_state,
    [linecomment_state][16] = linecomment_state,
    [linecomment_state][17] = linecomment_state,
    [linecomment_state][18] = linecomment_state,
    [linecomment_state][19] = linecomment_state,
    [linecomment_state][20] = linecomment_state,
    [linecomment_state][21] = linecomment_state,
    [linecomment_state][22] = linecomment_state,
    [linecomment_state][23] = linecomment_state,
    [linecomment_state][24] = linecomment_state,
    [linecomment_state][25] = linecomment_state,
    [linecomment_state][26] = linecomment_state,
    [linecomment_state][27] = linecomment_state,
    [linecomment_state][28] = linecomment_state,
    [linecomment_state][30] = linecomment_state,
    [linecomment_state][31] = linecomment_state,
    [linecomment_state][32] = linecomment_state,
    [linecomment_state][33] = linecomment_state,
    [linecomment_state][34] = linecomment_state,
    [linecomment_state][35] = linecomment_state,
    [linecomment_state][36] = linecomment_state,
    [linecomment_state][37] = linecomment_state,
    [linecomment_state][38] = linecomment_state,
    [linecomment_state][39] = linecomment_state,
    [linecomment_state][40] = linecomment_state,
    [linecomment_state][41] = linecomment_state,
    [linecomment_state][42] = linecomment_state,
    [linecomment_state][43] = linecomment_state,
    [linecomment_state][44] = linecomment_state,
    [linecomment_state][45] = linecomment_state,
    [linecomment_state][46] = linecomment_state,
    [linecomment_state][47] = linecomment_state,
    [linecomment_state][48] = linecomment_state,
    [linecomment_state][49] = linecomment_state,
    [linecomment_state][50] = linecomment_state,
    [linecomment_state][51] = linecomment_state,
    [linecomment_state][52] = linecomment_state,
    [linecomment_state][53] = linecomment_state,
    [linecomment_state][54] = linecomment_state,
    [linecomment_state][55] = linecomment_state,
    [linecomment_state][56] = linecomment_state,
    [linecomment_state][57] = linecomment_state,
    [linecomment_state][58] = linecomment_state,
    [linecomment_state][59] = linecomment_state,
    [linecomment_state][60] = linecomment_state,
    [linecomment_state][61] = linecomment_state,
    [linecomment_state][62] = linecomment_state,
    [linecomment_state][63] = linecomment_state,
    [linecomment_state][64] = linecomment_state,
    [linecomment_state][65] = linecomment_state,
    [linecomment_state][66] = linecomment_state,
    [linecomment_state][67] = linecomment_state,
    [linecomment_state][68] = linecomment_state,
    [linecomment_state][69] = linecomment_state,
    [linecomment_state][70] = linecomment_state,
    [linecomment_state][71] = linecomment_state,
    [linecomment_state][72] = linecomment_state,
    [linecomment_state][73] = linecomment_state,
    [linecomment_state][74] = linecomment_state,
    [linecomment_state][75] = linecomment_state,
    [linecomment_state][76] = linecomment_state,
    [linecomment_state][77] = linecomment_state,
    [linecomment_state][78] = linecomment_state,
    [linecomment_state][79] = linecomment_state,
    [linecomment_state][80] = linecomment_state,
    [linecomment_state][81] = linecomment_state,
    [linecomment_state][82] = linecomment_state,
    [linecomment_state][83] = linecomment_state,
    [linecomment_state][84] = linecomment_state,
    [linecomment_state][85] = linecomment_state,
    [linecomment_state][86] = linecomment_state,
    [linecomment_state][87] = linecomment_state,
    [linecomment_state][88] = linecomment_state,
    [linecomment_state][89] = linecomment_state,
    [linecomment_state][90] = linecomment_state,
    [linecomment_state][91] = linecomment_state,
    [linecomment_state][92] = linecomment_state,
    [linecomment_state][93] = linecomment_state,
    [linecomment_state][94] = linecomment_state,
    [linecomment_state][95] = linecomment_state,
    [linecomment_state][96] = linecomment_state,
    [linecomment_state][97] = linecomment_state,
    [blockcomment_state][44] = blockcommentweak_state,
    [blockcomment_state][1] = blockcomment_state,
    [blockcomment_state][2] = blockcomment_state,
    [blockcomment_state][3] = blockcomment_state,
    [blockcomment_state][4] = blockcomment_state,
    [blockcomment_state][5] = blockcomment_state,
    [blockcomment_state][6] = blockcomment_state,
    [blockcomment_state][7] = blockcomment_state,
    [blockcomment_state][8] = blockcomment_state,
    [blockcomment_state][9] = blockcomment_state,
    [blockcomment_state][10] = blockcomment_state,
    [blockcomment_state][11] = blockcomment_state,
    [blockcomment_state][12] = blockcomment_state,
    [blockcomment_state][13] = blockcomment_state,
    [blockcomment_state][14] = blockcomment_state,
    [blockcomment_state][15] = blockcomment_state,
    [blockcomment_state][16] = blockcomment_state,
    [blockcomment_state][17] = blockcomment_state,
    [blockcomment_state][18] = blockcomment_state,
    [blockcomment_state][19] = blockcomment_state,
    [blockcomment_state][20] = blockcomment_state,
    [blockcomment_state][21] = blockcomment_state,
    [blockcomment_state][22] = blockcomment_state,
    [blockcomment_state][23] = blockcomment_state,
    [blockcomment_state][24] = blockcomment_state,
    [blockcomment_state][25] = blockcomment_state,
    [blockcomment_state][26] = blockcomment_state,
    [blockcomment_state][27] = blockcomment_state,
    [blockcomment_state][28] = blockcomment_state,
    [blockcomment_state][30] = blockcomment_state,
    [blockcomment_state][31] = blockcomment_state,
    [blockcomment_state][32] = blockcomment_state,
    [blockcomment_state][33] = blockcomment_state,
    [blockcomment_state][34] = blockcomment_state,
    [blockcomment_state][35] = blockcomment_state,
    [blockcomment_state][36] = blockcomment_state,
    [blockcomment_state][37] = blockcomment_state,
    [blockcomment_state][38] = blockcomment_state,
    [blockcomment_state][39] = blockcomment_state,
    [blockcomment_state][40] = blockcomment_state,
    [blockcomment_state][41] = blockcomment_state,
    [blockcomment_state][42] = blockcomment_state,
    [blockcomment_state][43] = blockcomment_state,
    [blockcomment_state][45] = blockcomment_state,
    [blockcomment_state][46] = blockcomment_state,
    [blockcomment_state][47] = blockcomment_state,
    [blockcomment_state][48] = blockcomment_state,
    [blockcomment_state][49] = blockcomment_state,
    [blockcomment_state][50] = blockcomment_state,
    [blockcomment_state][51] = blockcomment_state,
    [blockcomment_state][52] = blockcomment_state,
    [blockcomment_state][53] = blockcomment_state,
    [blockcomment_state][54] = blockcomment_state,
    [blockcomment_state][55] = blockcomment_state,
    [blockcomment_state][56] = blockcomment_state,
    [blockcomment_state][57] = blockcomment_state,
    [blockcomment_state][58] = blockcomment_state,
    [blockcomment_state][59] = blockcomment_state,
    [blockcomment_state][60] = blockcomment_state,
    [blockcomment_state][61] = blockcomment_state,
    [blockcomment_state][62] = blockcomment_state,
    [blockcomment_state][63] = blockcomment_state,
    [blockcomment_state][64] = blockcomment_state,
    [blockcomment_state][65] = blockcomment_state,
    [blockcomment_state][66] = blockcomment_state,
    [blockcomment_state][67] = blockcomment_state,
    [blockcomment_state][68] = blockcomment_state,
    [blockcomment_state][69] = blockcomment_state,
    [blockcomment_state][70] = blockcomment_state,
    [blockcomment_state][71] = blockcomment_state,
    [blockcomment_state][72] = blockcomment_state,
    [blockcomment_state][73] = blockcomment_state,
    [blockcomment_state][74] = blockcomment_state,
    [blockcomment_state][75] = blockcomment_state,
    [blockcomment_state][76] = blockcomment_state,
    [blockcomment_state][77] = blockcomment_state,
    [blockcomment_state][78] = blockcomment_state,
    [blockcomment_state][79] = blockcomment_state,
    [blockcomment_state][80] = blockcomment_state,
    [blockcomment_state][81] = blockcomment_state,
    [blockcomment_state][82] = blockcomment_state,
    [blockcomment_state][83] = blockcomment_state,
    [blockcomment_state][84] = blockcomment_state,
    [blockcomment_state][85] = blockcomment_state,
    [blockcomment_state][86] = blockcomment_state,
    [blockcomment_state][87] = blockcomment_state,
    [blockcomment_state][88] = blockcomment_state,
    [blockcomment_state][89] = blockcomment_state,
    [blockcomment_state][90] = blockcomment_state,
    [blockcomment_state][91] = blockcomment_state,
    [blockcomment_state][92] = blockcomment_state,
    [blockcomment_state][93] = blockcomment_state,
    [blockcomment_state][94] = blockcomment_state,
    [blockcomment_state][95] = blockcomment_state,
    [blockcomment_state][96] = blockcomment_state,
    [blockcomment_state][97] = blockcomment_state,
    [blockcommentweak_state][44] = blockcommentweak_state,
    [blockcommentweak_state][80] = blockcommentfinish_state,
    [blockcommentweak_state][1] = blockcomment_state,
    [blockcommentweak_state][2] = blockcomment_state,
    [blockcommentweak_state][3] = blockcomment_state,
    [blockcommentweak_state][4] = blockcomment_state,
    [blockcommentweak_state][5] = blockcomment_state,
    [blockcommentweak_state][6] = blockcomment_state,
    [blockcommentweak_state][7] = blockcomment_state,
    [blockcommentweak_state][8] = blockcomment_state,
    [blockcommentweak_state][9] = blockcomment_state,
    [blockcommentweak_state][10] = blockcomment_state,
    [blockcommentweak_state][11] = blockcomment_state,
    [blockcommentweak_state][12] = blockcomment_state,
    [blockcommentweak_state][13] = blockcomment_state,
    [blockcommentweak_state][14] = blockcomment_state,
    [blockcommentweak_state][15] = blockcomment_state,
    [blockcommentweak_state][16] = blockcomment_state,
    [blockcommentweak_state][17] = blockcomment_state,
    [blockcommentweak_state][18] = blockcomment_state,
    [blockcommentweak_state][19] = blockcomment_state,
    [blockcommentweak_state][20] = blockcomment_state,
    [blockcommentweak_state][21] = blockcomment_state,
    [blockcommentweak_state][22] = blockcomment_state,
    [blockcommentweak_state][23] = blockcomment_state,
    [blockcommentweak_state][24] = blockcomment_state,
    [blockcommentweak_state][25] = blockcomment_state,
    [blockcommentweak_state][26] = blockcomment_state,
    [blockcommentweak_state][27] = blockcomment_state,
    [blockcommentweak_state][28] = blockcomment_state,
    [blockcommentweak_state][30] = blockcomment_state,
    [blockcommentweak_state][31] = blockcomment_state,
    [blockcommentweak_state][32] = blockcomment_state,
    [blockcommentweak_state][33] = blockcomment_state,
    [blockcommentweak_state][34] = blockcomment_state,
    [blockcommentweak_state][35] = blockcomment_state,
    [blockcommentweak_state][36] = blockcomment_state,
    [blockcommentweak_state][37] = blockcomment_state,
    [blockcommentweak_state][38] = blockcomment_state,
    [blockcommentweak_state][39] = blockcomment_state,
    [blockcommentweak_state][40] = blockcomment_state,
    [blockcommentweak_state][41] = blockcomment_state,
    [blockcommentweak_state][42] = blockcomment_state,
    [blockcommentweak_state][43] = blockcomment_state,
    [blockcommentweak_state][45] = blockcomment_state,
    [blockcommentweak_state][46] = blockcomment_state,
    [blockcommentweak_state][47] = blockcomment_state,
    [blockcommentweak_state][48] = blockcomment_state,
    [blockcommentweak_state][49] = blockcomment_state,
    [blockcommentweak_state][50] = blockcomment_state,
    [blockcommentweak_state][51] = blockcomment_state,
    [blockcommentweak_state][52] = blockcomment_state,
    [blockcommentweak_state][53] = blockcomment_state,
    [blockcommentweak_state][54] = blockcomment_state,
    [blockcommentweak_state][55] = blockcomment_state,
    [blockcommentweak_state][56] = blockcomment_state,
    [blockcommentweak_state][57] = blockcomment_state,
    [blockcommentweak_state][58] = blockcomment_state,
    [blockcommentweak_state][59] = blockcomment_state,
    [blockcommentweak_state][60] = blockcomment_state,
    [blockcommentweak_state][61] = blockcomment_state,
    [blockcommentweak_state][62] = blockcomment_state,
    [blockcommentweak_state][63] = blockcomment_state,
    [blockcommentweak_state][64] = blockcomment_state,
    [blockcommentweak_state][65] = blockcomment_state,
    [blockcommentweak_state][66] = blockcomment_state,
    [blockcommentweak_state][67] = blockcomment_state,
    [blockcommentweak_state][68] = blockcomment_state,
    [blockcommentweak_state][69] = blockcomment_state,
    [blockcommentweak_state][70] = blockcomment_state,
    [blockcommentweak_state][71] = blockcomment_state,
    [blockcommentweak_state][72] = blockcomment_state,
    [blockcommentweak_state][73] = blockcomment_state,
    [blockcommentweak_state][74] = blockcomment_state,
    [blockcommentweak_state][75] = blockcomment_state,
    [blockcommentweak_state][76] = blockcomment_state,
    [blockcommentweak_state][77] = blockcomment_state,
    [blockcommentweak_state][78] = blockcomment_state,
    [blockcommentweak_state][79] = blockcomment_state,
    [blockcommentweak_state][81] = blockcomment_state,
    [blockcommentweak_state][82] = blockcomment_state,
    [blockcommentweak_state][83] = blockcomment_state,
    [blockcommentweak_state][84] = blockcomment_state,
    [blockcommentweak_state][85] = blockcomment_state,
    [blockcommentweak_state][86] = blockcomment_state,
    [blockcommentweak_state][87] = blockcomment_state,
    [blockcommentweak_state][88] = blockcomment_state,
    [blockcommentweak_state][89] = blockcomment_state,
    [blockcommentweak_state][90] = blockcomment_state,
    [blockcommentweak_state][91] = blockcomment_state,
    [blockcommentweak_state][92] = blockcomment_state,
    [blockcommentweak_state][93] = blockcomment_state,
    [blockcommentweak_state][94] = blockcomment_state,
    [blockcommentweak_state][95] = blockcomment_state,
    [blockcommentweak_state][96] = blockcomment_state,
    [blockcommentweak_state][97] = blockcomment_state,
    [amp_state][58] = bandeq_state,
    [amp_state][50] = and_state,
    [star_state][58] = timeseq_state,
    [exc_state][58] = noteq_state,
    [preproc_state][2] = preproc_state,
    [preproc_state][3] = preproc_state,
    [preproc_state][4] = preproc_state,
    [preproc_state][5] = preproc_state,
    [preproc_state][6] = preproc_state,
    [preproc_state][7] = preproc_state,
    [preproc_state][8] = preproc_state,
    [preproc_state][9] = preproc_state,
    [preproc_state][10] = preproc_state,
    [preproc_state][11] = preproc_state,
    [preproc_state][12] = preproc_state,
    [preproc_state][13] = preproc_state,
    [preproc_state][14] = preproc_state,
    [preproc_state][15] = preproc_state,
    [preproc_state][16] = preproc_state,
    [preproc_state][17] = preproc_state,
    [preproc_state][18] = preproc_state,
    [preproc_state][19] = preproc_state,
    [preproc_state][20] = preproc_state,
    [preproc_state][21] = preproc_state,
    [preproc_state][22] = preproc_state,
    [preproc_state][23] = preproc_state,
    [preproc_state][24] = preproc_state,
    [preproc_state][25] = preproc_state,
    [preproc_state][26] = preproc_state,
    [preproc_state][27] = preproc_state,
    [preproc_state][28] = preproc_state,
    [preproc_state][30] = preproc_state,
    [preproc_state][31] = preproc_state,
    [preproc_state][32] = preproc_state,
    [preproc_state][33] = preproc_state,
    [preproc_state][34] = preproc_state,
    [preproc_state][35] = preproc_state,
    [preproc_state][36] = preproc_state,
    [preproc_state][37] = preproc_state,
    [preproc_state][38] = preproc_state,
    [preproc_state][39] = preproc_state,
    [preproc_state][40] = preproc_state,
    [preproc_state][41] = preproc_state,
    [preproc_state][42] = preproc_state,
    [preproc_state][43] = preproc_state,
    [preproc_state][44] = preproc_state,
    [preproc_state][45] = preproc_state,
    [preproc_state][46] = preproc_state,
    [preproc_state][47] = preproc_state,
    [preproc_state][48] = preproc_state,
    [preproc_state][49] = preproc_state,
    [preproc_state][50] = preproc_state,
    [preproc_state][51] = preproc_state,
    [preproc_state][52] = preproc_state,
    [preproc_state][53] = preproc_state,
    [preproc_state][54] = preproc_state,
    [preproc_state][55] = preproc_state,
    [preproc_state][56] = preproc_state,
    [preproc_state][57] = preproc_state,
    [preproc_state][58] = preproc_state,
    [preproc_state][59] = preproc_state,
    [preproc_state][60] = preproc_state,
    [preproc_state][61] = preproc_state,
    [preproc_state][62] = preproc_state,
    [preproc_state][63] = preproc_state,
    [preproc_state][64] = preproc_state,
    [preproc_state][65] = preproc_state,
    [preproc_state][66] = preproc_state,
    [preproc_state][67] = preproc_state,
    [preproc_state][68] = preproc_state,
    [preproc_state][69] = preproc_state,
    [preproc_state][70] = preproc_state,
    [preproc_state][71] = preproc_state,
    [preproc_state][72] = preproc_state,
    [preproc_state][73] = preproc_state,
    [preproc_state][74] = preproc_state,
    [preproc_state][75] = preproc_state,
    [preproc_state][76] = preproc_state,
    [preproc_state][77] = preproc_state,
    [preproc_state][78] = preproc_state,
    [preproc_state][79] = preproc_state,
    [preproc_state][80] = preproc_state,
    [preproc_state][81] = preproc_state,
    [preproc_state][82] = preproc_state,
    [preproc_state][83] = preproc_state,
    [preproc_state][84] = preproc_state,
    [preproc_state][85] = preproc_state,
    [preproc_state][86] = preproc_state,
    [preproc_state][87] = preproc_state,
    [preproc_state][88] = preproc_state,
    [preproc_state][89] = preproc_state,
    [preproc_state][90] = preproc_state,
    [preproc_state][91] = preproc_state,
    [preproc_state][92] = preproc_state,
    [preproc_state][93] = preproc_state,
    [preproc_state][94] = preproc_state,
    [preproc_state][95] = preproc_state,
    [preproc_state][96] = preproc_state,
    [preproc_state][97] = preproc_state,
    [whitespace_state][51] = whitespace_state,
    [whitespace_state][43] = whitespace_state,
    [whitespace_state][8] = whitespace_state,
    [whitespace_state][1] = newline_state,
    [charliteralstart_state][74] = charliteralescape_state,
    [charliteralstart_state][2] = charliteralchewedone_state,
    [charliteralstart_state][3] = charliteralchewedone_state,
    [charliteralstart_state][4] = charliteralchewedone_state,
    [charliteralstart_state][5] = charliteralchewedone_state,
    [charliteralstart_state][6] = charliteralchewedone_state,
    [charliteralstart_state][7] = charliteralchewedone_state,
    [charliteralstart_state][8] = charliteralchewedone_state,
    [charliteralstart_state][9] = charliteralchewedone_state,
    [charliteralstart_state][10] = charliteralchewedone_state,
    [charliteralstart_state][11] = charliteralchewedone_state,
    [charliteralstart_state][12] = charliteralchewedone_state,
    [charliteralstart_state][13] = charliteralchewedone_state,
    [charliteralstart_state][14] = charliteralchewedone_state,
    [charliteralstart_state][15] = charliteralchewedone_state,
    [charliteralstart_state][16] = charliteralchewedone_state,
    [charliteralstart_state][17] = charliteralchewedone_state,
    [charliteralstart_state][18] = charliteralchewedone_state,
    [charliteralstart_state][19] = charliteralchewedone_state,
    [charliteralstart_state][20] = charliteralchewedone_state,
    [charliteralstart_state][21] = charliteralchewedone_state,
    [charliteralstart_state][22] = charliteralchewedone_state,
    [charliteralstart_state][23] = charliteralchewedone_state,
    [charliteralstart_state][24] = charliteralchewedone_state,
    [charliteralstart_state][25] = charliteralchewedone_state,
    [charliteralstart_state][26] = charliteralchewedone_state,
    [charliteralstart_state][27] = charliteralchewedone_state,
    [charliteralstart_state][28] = charliteralchewedone_state,
    [charliteralstart_state][30] = charliteralchewedone_state,
    [charliteralstart_state][31] = charliteralchewedone_state,
    [charliteralstart_state][32] = charliteralchewedone_state,
    [charliteralstart_state][33] = charliteralchewedone_state,
    [charliteralstart_state][34] = charliteralchewedone_state,
    [charliteralstart_state][35] = charliteralchewedone_state,
    [charliteralstart_state][37] = charliteralchewedone_state,
    [charliteralstart_state][38] = charliteralchewedone_state,
    [charliteralstart_state][39] = charliteralchewedone_state,
    [charliteralstart_state][40] = charliteralchewedone_state,
    [charliteralstart_state][41] = charliteralchewedone_state,
    [charliteralstart_state][42] = charliteralchewedone_state,
    [charliteralstart_state][43] = charliteralchewedone_state,
    [charliteralstart_state][44] = charliteralchewedone_state,
    [charliteralstart_state][45] = charliteralchewedone_state,
    [charliteralstart_state][46] = charliteralchewedone_state,
    [charliteralstart_state][47] = charliteralchewedone_state,
    [charliteralstart_state][48] = charliteralchewedone_state,
    [charliteralstart_state][49] = charliteralchewedone_state,
    [charliteralstart_state][50] = charliteralchewedone_state,
    [charliteralstart_state][51] = charliteralchewedone_state,
    [charliteralstart_state][52] = charliteralchewedone_state,
    [charliteralstart_state][53] = charliteralchewedone_state,
    [charliteralstart_state][54] = charliteralchewedone_state,
    [charliteralstart_state][55] = charliteralchewedone_state,
    [charliteralstart_state][56] = charliteralchewedone_state,
    [charliteralstart_state][57] = charliteralchewedone_state,
    [charliteralstart_state][58] = charliteralchewedone_state,
    [charliteralstart_state][59] = charliteralchewedone_state,
    [charliteralstart_state][60] = charliteralchewedone_state,
    [charliteralstart_state][61] = charliteralchewedone_state,
    [charliteralstart_state][62] = charliteralchewedone_state,
    [charliteralstart_state][63] = charliteralchewedone_state,
    [charliteralstart_state][64] = charliteralchewedone_state,
    [charliteralstart_state][65] = charliteralchewedone_state,
    [charliteralstart_state][66] = charliteralchewedone_state,
    [charliteralstart_state][67] = charliteralchewedone_state,
    [charliteralstart_state][68] = charliteralchewedone_state,
    [charliteralstart_state][69] = charliteralchewedone_state,
    [charliteralstart_state][70] = charliteralchewedone_state,
    [charliteralstart_state][71] = charliteralchewedone_state,
    [charliteralstart_state][72] = charliteralchewedone_state,
    [charliteralstart_state][73] = charliteralchewedone_state,
    [charliteralstart_state][75] = charliteralchewedone_state,
    [charliteralstart_state][76] = charliteralchewedone_state,
    [charliteralstart_state][77] = charliteralchewedone_state,
    [charliteralstart_state][78] = charliteralchewedone_state,
    [charliteralstart_state][79] = charliteralchewedone_state,
    [charliteralstart_state][80] = charliteralchewedone_state,
    [charliteralstart_state][81] = charliteralchewedone_state,
    [charliteralstart_state][82] = charliteralchewedone_state,
    [charliteralstart_state][83] = charliteralchewedone_state,
    [charliteralstart_state][84] = charliteralchewedone_state,
    [charliteralstart_state][85] = charliteralchewedone_state,
    [charliteralstart_state][86] = charliteralchewedone_state,
    [charliteralstart_state][87] = charliteralchewedone_state,
    [charliteralstart_state][88] = charliteralchewedone_state,
    [charliteralstart_state][89] = charliteralchewedone_state,
    [charliteralstart_state][90] = charliteralchewedone_state,
    [charliteralstart_state][91] = charliteralchewedone_state,
    [charliteralstart_state][92] = charliteralchewedone_state,
    [charliteralstart_state][93] = charliteralchewedone_state,
    [charliteralstart_state][94] = charliteralchewedone_state,
    [charliteralstart_state][95] = charliteralchewedone_state,
    [charliteralstart_state][96] = charliteralchewedone_state,
    [charliteralstart_state][97] = charliteralchewedone_state,
    [charliteralchewedone_state][74] = charliteralescape_state,
    [charliteralchewedone_state][36] = charliteral_state,
    [charliteralchewedone_state][2] = charliteralchewedone_state,
    [charliteralchewedone_state][3] = charliteralchewedone_state,
    [charliteralchewedone_state][4] = charliteralchewedone_state,
    [charliteralchewedone_state][5] = charliteralchewedone_state,
    [charliteralchewedone_state][6] = charliteralchewedone_state,
    [charliteralchewedone_state][7] = charliteralchewedone_state,
    [charliteralchewedone_state][8] = charliteralchewedone_state,
    [charliteralchewedone_state][9] = charliteralchewedone_state,
    [charliteralchewedone_state][10] = charliteralchewedone_state,
    [charliteralchewedone_state][11] = charliteralchewedone_state,
    [charliteralchewedone_state][12] = charliteralchewedone_state,
    [charliteralchewedone_state][13] = charliteralchewedone_state,
    [charliteralchewedone_state][14] = charliteralchewedone_state,
    [charliteralchewedone_state][15] = charliteralchewedone_state,
    [charliteralchewedone_state][16] = charliteralchewedone_state,
    [charliteralchewedone_state][17] = charliteralchewedone_state,
    [charliteralchewedone_state][18] = charliteralchewedone_state,
    [charliteralchewedone_state][19] = charliteralchewedone_state,
    [charliteralchewedone_state][20] = charliteralchewedone_state,
    [charliteralchewedone_state][21] = charliteralchewedone_state,
    [charliteralchewedone_state][22] = charliteralchewedone_state,
    [charliteralchewedone_state][23] = charliteralchewedone_state,
    [charliteralchewedone_state][24] = charliteralchewedone_state,
    [charliteralchewedone_state][25] = charliteralchewedone_state,
    [charliteralchewedone_state][26] = charliteralchewedone_state,
    [charliteralchewedone_state][27] = charliteralchewedone_state,
    [charliteralchewedone_state][28] = charliteralchewedone_state,
    [charliteralchewedone_state][30] = charliteralchewedone_state,
    [charliteralchewedone_state][31] = charliteralchewedone_state,
    [charliteralchewedone_state][32] = charliteralchewedone_state,
    [charliteralchewedone_state][33] = charliteralchewedone_state,
    [charliteralchewedone_state][34] = charliteralchewedone_state,
    [charliteralchewedone_state][35] = charliteralchewedone_state,
    [charliteralchewedone_state][37] = charliteralchewedone_state,
    [charliteralchewedone_state][38] = charliteralchewedone_state,
    [charliteralchewedone_state][39] = charliteralchewedone_state,
    [charliteralchewedone_state][40] = charliteralchewedone_state,
    [charliteralchewedone_state][41] = charliteralchewedone_state,
    [charliteralchewedone_state][42] = charliteralchewedone_state,
    [charliteralchewedone_state][43] = charliteralchewedone_state,
    [charliteralchewedone_state][44] = charliteralchewedone_state,
    [charliteralchewedone_state][45] = charliteralchewedone_state,
    [charliteralchewedone_state][46] = charliteralchewedone_state,
    [charliteralchewedone_state][47] = charliteralchewedone_state,
    [charliteralchewedone_state][48] = charliteralchewedone_state,
    [charliteralchewedone_state][49] = charliteralchewedone_state,
    [charliteralchewedone_state][50] = charliteralchewedone_state,
    [charliteralchewedone_state][51] = charliteralchewedone_state,
    [charliteralchewedone_state][52] = charliteralchewedone_state,
    [charliteralchewedone_state][53] = charliteralchewedone_state,
    [charliteralchewedone_state][54] = charliteralchewedone_state,
    [charliteralchewedone_state][55] = charliteralchewedone_state,
    [charliteralchewedone_state][56] = charliteralchewedone_state,
    [charliteralchewedone_state][57] = charliteralchewedone_state,
    [charliteralchewedone_state][58] = charliteralchewedone_state,
    [charliteralchewedone_state][59] = charliteralchewedone_state,
    [charliteralchewedone_state][60] = charliteralchewedone_state,
    [charliteralchewedone_state][61] = charliteralchewedone_state,
    [charliteralchewedone_state][62] = charliteralchewedone_state,
    [charliteralchewedone_state][63] = charliteralchewedone_state,
    [charliteralchewedone_state][64] = charliteralchewedone_state,
    [charliteralchewedone_state][65] = charliteralchewedone_state,
    [charliteralchewedone_state][66] = charliteralchewedone_state,
    [charliteralchewedone_state][67] = charliteralchewedone_state,
    [charliteralchewedone_state][68] = charliteralchewedone_state,
    [charliteralchewedone_state][69] = charliteralchewedone_state,
    [charliteralchewedone_state][70] = charliteralchewedone_state,
    [charliteralchewedone_state][71] = charliteralchewedone_state,
    [charliteralchewedone_state][72] = charliteralchewedone_state,
    [charliteralchewedone_state][73] = charliteralchewedone_state,
    [charliteralchewedone_state][75] = charliteralchewedone_state,
    [charliteralchewedone_state][76] = charliteralchewedone_state,
    [charliteralchewedone_state][77] = charliteralchewedone_state,
    [charliteralchewedone_state][78] = charliteralchewedone_state,
    [charliteralchewedone_state][79] = charliteralchewedone_state,
    [charliteralchewedone_state][80] = charliteralchewedone_state,
    [charliteralchewedone_state][81] = charliteralchewedone_state,
    [charliteralchewedone_state][82] = charliteralchewedone_state,
    [charliteralchewedone_state][83] = charliteralchewedone_state,
    [charliteralchewedone_state][84] = charliteralchewedone_state,
    [charliteralchewedone_state][85] = charliteralchewedone_state,
    [charliteralchewedone_state][86] = charliteralchewedone_state,
    [charliteralchewedone_state][87] = charliteralchewedone_state,
    [charliteralchewedone_state][88] = charliteralchewedone_state,
    [charliteralchewedone_state][89] = charliteralchewedone_state,
    [charliteralchewedone_state][90] = charliteralchewedone_state,
    [charliteralchewedone_state][91] = charliteralchewedone_state,
    [charliteralchewedone_state][92] = charliteralchewedone_state,
    [charliteralchewedone_state][93] = charliteralchewedone_state,
    [charliteralchewedone_state][94] = charliteralchewedone_state,
    [charliteralchewedone_state][95] = charliteralchewedone_state,
    [charliteralchewedone_state][96] = charliteralchewedone_state,
    [charliteralchewedone_state][97] = charliteralchewedone_state,
    [charliteralescape_state][36] = charliteralchewedone_state,
    [charliteralescape_state][57] = charliteralchewedone_state,
    [charliteralescape_state][82] = charliteralchewedone_state,
    [charliteralescape_state][74] = charliteralchewedone_state,
    [charliteralescape_state][95] = charliteralchewedone_state,
    [charliteralescape_state][81] = charliteralchewedone_state,
    [charliteralescape_state][65] = charliteralchewedone_state,
    [charliteralescape_state][34] = charliteralchewedone_state,
    [charliteralescape_state][4] = charliteralchewedone_state,
    [charliteralescape_state][3] = charliteralchewedone_state,
    [charliteralescape_state][84] = charliteralchewedone_state,
    [charliteralescape_state][25] = charescapeoctal0_state,
    [charliteralescape_state][42] = charescapeoctal0_state,
    [charliteralescape_state][79] = charescapeoctal0_state,
    [charliteralescape_state][16] = charescapeoctal0_state,
    [charliteralescape_state][33] = charescapeoctal0_state,
    [charliteralescape_state][9] = charescapeoctal0_state,
    [charliteralescape_state][38] = charescapeoctal0_state,
    [charliteralescape_state][97] = charescapeoctal0_state,
    [charliteralescape_state][39] = charescapehexempty_state,
    [charescapeoctal0_state][25] = charescapeoctal1_state,
    [charescapeoctal0_state][42] = charescapeoctal1_state,
    [charescapeoctal0_state][79] = charescapeoctal1_state,
    [charescapeoctal0_state][16] = charescapeoctal1_state,
    [charescapeoctal0_state][33] = charescapeoctal1_state,
    [charescapeoctal0_state][9] = charescapeoctal1_state,
    [charescapeoctal0_state][38] = charescapeoctal1_state,
    [charescapeoctal0_state][97] = charescapeoctal1_state,
    [charescapeoctal0_state][36] = charliteral_state,
    [charescapeoctal1_state][25] = charliteralchewedone_state,
    [charescapeoctal1_state][42] = charliteralchewedone_state,
    [charescapeoctal1_state][79] = charliteralchewedone_state,
    [charescapeoctal1_state][16] = charliteralchewedone_state,
    [charescapeoctal1_state][33] = charliteralchewedone_state,
    [charescapeoctal1_state][9] = charliteralchewedone_state,
    [charescapeoctal1_state][38] = charliteralchewedone_state,
    [charescapeoctal1_state][97] = charliteralchewedone_state,
    [charescapeoctal1_state][36] = charliteral_state,
    [charescapehexempty_state][9] = charescapehex_state,
    [charescapehexempty_state][11] = charescapehex_state,
    [charescapehexempty_state][12] = charescapehex_state,
    [charescapehexempty_state][64] = charescapehex_state,
    [charescapehexempty_state][65] = charescapehex_state,
    [charescapehexempty_state][16] = charescapehex_state,
    [charescapehexempty_state][18] = charescapehex_state,
    [charescapehexempty_state][19] = charescapehex_state,
    [charescapehexempty_state][21] = charescapehex_state,
    [charescapehexempty_state][25] = charescapehex_state,
    [charescapehexempty_state][79] = charescapehex_state,
    [charescapehexempty_state][81] = charescapehex_state,
    [charescapehexempty_state][26] = charescapehex_state,
    [charescapehexempty_state][33] = charescapehex_state,
    [charescapehexempty_state][89] = charescapehex_state,
    [charescapehexempty_state][38] = charescapehex_state,
    [charescapehexempty_state][42] = charescapehex_state,
    [charescapehexempty_state][45] = charescapehex_state,
    [charescapehexempty_state][94] = charescapehex_state,
    [charescapehexempty_state][95] = charescapehex_state,
    [charescapehexempty_state][49] = charescapehex_state,
    [charescapehexempty_state][97] = charescapehex_state,
    [charescapehex_state][9] = charescapehex_state,
    [charescapehex_state][11] = charescapehex_state,
    [charescapehex_state][12] = charescapehex_state,
    [charescapehex_state][64] = charescapehex_state,
    [charescapehex_state][65] = charescapehex_state,
    [charescapehex_state][16] = charescapehex_state,
    [charescapehex_state][18] = charescapehex_state,
    [charescapehex_state][19] = charescapehex_state,
    [charescapehex_state][21] = charescapehex_state,
    [charescapehex_state][25] = charescapehex_state,
    [charescapehex_state][79] = charescapehex_state,
    [charescapehex_state][81] = charescapehex_state,
    [charescapehex_state][26] = charescapehex_state,
    [charescapehex_state][33] = charescapehex_state,
    [charescapehex_state][89] = charescapehex_state,
    [charescapehex_state][38] = charescapehex_state,
    [charescapehex_state][42] = charescapehex_state,
    [charescapehex_state][45] = charescapehex_state,
    [charescapehex_state][94] = charescapehex_state,
    [charescapehex_state][95] = charescapehex_state,
    [charescapehex_state][49] = charescapehex_state,
    [charescapehex_state][97] = charescapehex_state,
    [charescapehex_state][36] = charliteral_state,
    [stringliteralstart_state][74] = stringliteralescape_state,
    [stringliteralstart_state][57] = stringliteral_state,
    [stringliteralstart_state][2] = stringliteralstart_state,
    [stringliteralstart_state][3] = stringliteralstart_state,
    [stringliteralstart_state][4] = stringliteralstart_state,
    [stringliteralstart_state][5] = stringliteralstart_state,
    [stringliteralstart_state][6] = stringliteralstart_state,
    [stringliteralstart_state][7] = stringliteralstart_state,
    [stringliteralstart_state][8] = stringliteralstart_state,
    [stringliteralstart_state][9] = stringliteralstart_state,
    [stringliteralstart_state][10] = stringliteralstart_state,
    [stringliteralstart_state][11] = stringliteralstart_state,
    [stringliteralstart_state][12] = stringliteralstart_state,
    [stringliteralstart_state][13] = stringliteralstart_state,
    [stringliteralstart_state][14] = stringliteralstart_state,
    [stringliteralstart_state][15] = stringliteralstart_state,
    [stringliteralstart_state][16] = stringliteralstart_state,
    [stringliteralstart_state][17] = stringliteralstart_state,
    [stringliteralstart_state][18] = stringliteralstart_state,
    [stringliteralstart_state][19] = stringliteralstart_state,
    [stringliteralstart_state][20] = stringliteralstart_state,
    [stringliteralstart_state][21] = stringliteralstart_state,
    [stringliteralstart_state][22] = stringliteralstart_state,
    [stringliteralstart_state][23] = stringliteralstart_state,
    [stringliteralstart_state][24] = stringliteralstart_state,
    [stringliteralstart_state][25] = stringliteralstart_state,
    [stringliteralstart_state][26] = stringliteralstart_state,
    [stringliteralstart_state][27] = stringliteralstart_state,
    [stringliteralstart_state][28] = stringliteralstart_state,
    [stringliteralstart_state][30] = stringliteralstart_state,
    [stringliteralstart_state][31] = stringliteralstart_state,
    [stringliteralstart_state][32] = stringliteralstart_state,
    [stringliteralstart_state][33] = stringliteralstart_state,
    [stringliteralstart_state][34] = stringliteralstart_state,
    [stringliteralstart_state][35] = stringliteralstart_state,
    [stringliteralstart_state][36] = stringliteralstart_state,
    [stringliteralstart_state][37] = stringliteralstart_state,
    [stringliteralstart_state][38] = stringliteralstart_state,
    [stringliteralstart_state][39] = stringliteralstart_state,
    [stringliteralstart_state][40] = stringliteralstart_state,
    [stringliteralstart_state][41] = stringliteralstart_state,
    [stringliteralstart_state][42] = stringliteralstart_state,
    [stringliteralstart_state][43] = stringliteralstart_state,
    [stringliteralstart_state][44] = stringliteralstart_state,
    [stringliteralstart_state][45] = stringliteralstart_state,
    [stringliteralstart_state][46] = stringliteralstart_state,
    [stringliteralstart_state][47] = stringliteralstart_state,
    [stringliteralstart_state][48] = stringliteralstart_state,
    [stringliteralstart_state][49] = stringliteralstart_state,
    [stringliteralstart_state][50] = stringliteralstart_state,
    [stringliteralstart_state][51] = stringliteralstart_state,
    [stringliteralstart_state][52] = stringliteralstart_state,
    [stringliteralstart_state][53] = stringliteralstart_state,
    [stringliteralstart_state][54] = stringliteralstart_state,
    [stringliteralstart_state][55] = stringliteralstart_state,
    [stringliteralstart_state][56] = stringliteralstart_state,
    [stringliteralstart_state][58] = stringliteralstart_state,
    [stringliteralstart_state][59] = stringliteralstart_state,
    [stringliteralstart_state][60] = stringliteralstart_state,
    [stringliteralstart_state][61] = stringliteralstart_state,
    [stringliteralstart_state][62] = stringliteralstart_state,
    [stringliteralstart_state][63] = stringliteralstart_state,
    [stringliteralstart_state][64] = stringliteralstart_state,
    [stringliteralstart_state][65] = stringliteralstart_state,
    [stringliteralstart_state][66] = stringliteralstart_state,
    [stringliteralstart_state][67] = stringliteralstart_state,
    [stringliteralstart_state][68] = stringliteralstart_state,
    [stringliteralstart_state][69] = stringliteralstart_state,
    [stringliteralstart_state][70] = stringliteralstart_state,
    [stringliteralstart_state][71] = stringliteralstart_state,
    [stringliteralstart_state][72] = stringliteralstart_state,
    [stringliteralstart_state][73] = stringliteralstart_state,
    [stringliteralstart_state][75] = stringliteralstart_state,
    [stringliteralstart_state][76] = stringliteralstart_state,
    [stringliteralstart_state][77] = stringliteralstart_state,
    [stringliteralstart_state][78] = stringliteralstart_state,
    [stringliteralstart_state][79] = stringliteralstart_state,
    [stringliteralstart_state][80] = stringliteralstart_state,
    [stringliteralstart_state][81] = stringliteralstart_state,
    [stringliteralstart_state][82] = stringliteralstart_state,
    [stringliteralstart_state][83] = stringliteralstart_state,
    [stringliteralstart_state][84] = stringliteralstart_state,
    [stringliteralstart_state][85] = stringliteralstart_state,
    [stringliteralstart_state][86] = stringliteralstart_state,
    [stringliteralstart_state][87] = stringliteralstart_state,
    [stringliteralstart_state][88] = stringliteralstart_state,
    [stringliteralstart_state][89] = stringliteralstart_state,
    [stringliteralstart_state][90] = stringliteralstart_state,
    [stringliteralstart_state][91] = stringliteralstart_state,
    [stringliteralstart_state][92] = stringliteralstart_state,
    [stringliteralstart_state][93] = stringliteralstart_state,
    [stringliteralstart_state][94] = stringliteralstart_state,
    [stringliteralstart_state][95] = stringliteralstart_state,
    [stringliteralstart_state][96] = stringliteralstart_state,
    [stringliteralstart_state][97] = stringliteralstart_state,
    [stringliteralescape_state][36] = stringliteralstart_state,
    [stringliteralescape_state][57] = stringliteralstart_state,
    [stringliteralescape_state][82] = stringliteralstart_state,
    [stringliteralescape_state][74] = stringliteralstart_state,
    [stringliteralescape_state][95] = stringliteralstart_state,
    [stringliteralescape_state][81] = stringliteralstart_state,
    [stringliteralescape_state][65] = stringliteralstart_state,
    [stringliteralescape_state][34] = stringliteralstart_state,
    [stringliteralescape_state][4] = stringliteralstart_state,
    [stringliteralescape_state][3] = stringliteralstart_state,
    [stringliteralescape_state][84] = stringliteralstart_state,
    [stringliteralescape_state][25] = stringescapeoctal0_state,
    [stringliteralescape_state][42] = stringescapeoctal0_state,
    [stringliteralescape_state][79] = stringescapeoctal0_state,
    [stringliteralescape_state][16] = stringescapeoctal0_state,
    [stringliteralescape_state][33] = stringescapeoctal0_state,
    [stringliteralescape_state][9] = stringescapeoctal0_state,
    [stringliteralescape_state][38] = stringescapeoctal0_state,
    [stringliteralescape_state][97] = stringescapeoctal0_state,
    [stringliteralescape_state][39] = stringescapehexempty_state,
    [stringescapeoctal0_state][25] = stringescapeoctal1_state,
    [stringescapeoctal0_state][42] = stringescapeoctal1_state,
    [stringescapeoctal0_state][79] = stringescapeoctal1_state,
    [stringescapeoctal0_state][16] = stringescapeoctal1_state,
    [stringescapeoctal0_state][33] = stringescapeoctal1_state,
    [stringescapeoctal0_state][9] = stringescapeoctal1_state,
    [stringescapeoctal0_state][38] = stringescapeoctal1_state,
    [stringescapeoctal0_state][97] = stringescapeoctal1_state,
    [stringescapeoctal0_state][57] = stringliteral_state,
    [stringescapeoctal0_state][2] = stringliteralstart_state,
    [stringescapeoctal0_state][3] = stringliteralstart_state,
    [stringescapeoctal0_state][4] = stringliteralstart_state,
    [stringescapeoctal0_state][5] = stringliteralstart_state,
    [stringescapeoctal0_state][6] = stringliteralstart_state,
    [stringescapeoctal0_state][7] = stringliteralstart_state,
    [stringescapeoctal0_state][8] = stringliteralstart_state,
    [stringescapeoctal0_state][10] = stringliteralstart_state,
    [stringescapeoctal0_state][11] = stringliteralstart_state,
    [stringescapeoctal0_state][12] = stringliteralstart_state,
    [stringescapeoctal0_state][13] = stringliteralstart_state,
    [stringescapeoctal0_state][14] = stringliteralstart_state,
    [stringescapeoctal0_state][15] = stringliteralstart_state,
    [stringescapeoctal0_state][17] = stringliteralstart_state,
    [stringescapeoctal0_state][18] = stringliteralstart_state,
    [stringescapeoctal0_state][19] = stringliteralstart_state,
    [stringescapeoctal0_state][20] = stringliteralstart_state,
    [stringescapeoctal0_state][21] = stringliteralstart_state,
    [stringescapeoctal0_state][22] = stringliteralstart_state,
    [stringescapeoctal0_state][23] = stringliteralstart_state,
    [stringescapeoctal0_state][24] = stringliteralstart_state,
    [stringescapeoctal0_state][26] = stringliteralstart_state,
    [stringescapeoctal0_state][27] = stringliteralstart_state,
    [stringescapeoctal0_state][28] = stringliteralstart_state,
    [stringescapeoctal0_state][30] = stringliteralstart_state,
    [stringescapeoctal0_state][31] = stringliteralstart_state,
    [stringescapeoctal0_state][32] = stringliteralstart_state,
    [stringescapeoctal0_state][34] = stringliteralstart_state,
    [stringescapeoctal0_state][35] = stringliteralstart_state,
    [stringescapeoctal0_state][36] = stringliteralstart_state,
    [stringescapeoctal0_state][37] = stringliteralstart_state,
    [stringescapeoctal0_state][39] = stringliteralstart_state,
    [stringescapeoctal0_state][40] = stringliteralstart_state,
    [stringescapeoctal0_state][41] = stringliteralstart_state,
    [stringescapeoctal0_state][43] = stringliteralstart_state,
    [stringescapeoctal0_state][44] = stringliteralstart_state,
    [stringescapeoctal0_state][45] = stringliteralstart_state,
    [stringescapeoctal0_state][46] = stringliteralstart_state,
    [stringescapeoctal0_state][47] = stringliteralstart_state,
    [stringescapeoctal0_state][48] = stringliteralstart_state,
    [stringescapeoctal0_state][49] = stringliteralstart_state,
    [stringescapeoctal0_state][50] = stringliteralstart_state,
    [stringescapeoctal0_state][51] = stringliteralstart_state,
    [stringescapeoctal0_state][52] = stringliteralstart_state,
    [stringescapeoctal0_state][53] = stringliteralstart_state,
    [stringescapeoctal0_state][54] = stringliteralstart_state,
    [stringescapeoctal0_state][55] = stringliteralstart_state,
    [stringescapeoctal0_state][56] = stringliteralstart_state,
    [stringescapeoctal0_state][58] = stringliteralstart_state,
    [stringescapeoctal0_state][59] = stringliteralstart_state,
    [stringescapeoctal0_state][60] = stringliteralstart_state,
    [stringescapeoctal0_state][61] = stringliteralstart_state,
    [stringescapeoctal0_state][62] = stringliteralstart_state,
    [stringescapeoctal0_state][63] = stringliteralstart_state,
    [stringescapeoctal0_state][64] = stringliteralstart_state,
    [stringescapeoctal0_state][65] = stringliteralstart_state,
    [stringescapeoctal0_state][66] = stringliteralstart_state,
    [stringescapeoctal0_state][67] = stringliteralstart_state,
    [stringescapeoctal0_state][68] = stringliteralstart_state,
    [stringescapeoctal0_state][69] = stringliteralstart_state,
    [stringescapeoctal0_state][70] = stringliteralstart_state,
    [stringescapeoctal0_state][71] = stringliteralstart_state,
    [stringescapeoctal0_state][72] = stringliteralstart_state,
    [stringescapeoctal0_state][73] = stringliteralstart_state,
    [stringescapeoctal0_state][74] = stringliteralstart_state,
    [stringescapeoctal0_state][75] = stringliteralstart_state,
    [stringescapeoctal0_state][76] = stringliteralstart_state,
    [stringescapeoctal0_state][77] = stringliteralstart_state,
    [stringescapeoctal0_state][78] = stringliteralstart_state,
    [stringescapeoctal0_state][80] = stringliteralstart_state,
    [stringescapeoctal0_state][81] = stringliteralstart_state,
    [stringescapeoctal0_state][82] = stringliteralstart_state,
    [stringescapeoctal0_state][83] = stringliteralstart_state,
    [stringescapeoctal0_state][84] = stringliteralstart_state,
    [stringescapeoctal0_state][85] = stringliteralstart_state,
    [stringescapeoctal0_state][86] = stringliteralstart_state,
    [stringescapeoctal0_state][87] = stringliteralstart_state,
    [stringescapeoctal0_state][88] = stringliteralstart_state,
    [stringescapeoctal0_state][89] = stringliteralstart_state,
    [stringescapeoctal0_state][90] = stringliteralstart_state,
    [stringescapeoctal0_state][91] = stringliteralstart_state,
    [stringescapeoctal0_state][92] = stringliteralstart_state,
    [stringescapeoctal0_state][93] = stringliteralstart_state,
    [stringescapeoctal0_state][94] = stringliteralstart_state,
    [stringescapeoctal0_state][95] = stringliteralstart_state,
    [stringescapeoctal0_state][96] = stringliteralstart_state,
    [stringescapeoctal1_state][25] = stringliteralstart_state,
    [stringescapeoctal1_state][42] = stringliteralstart_state,
    [stringescapeoctal1_state][79] = stringliteralstart_state,
    [stringescapeoctal1_state][16] = stringliteralstart_state,
    [stringescapeoctal1_state][33] = stringliteralstart_state,
    [stringescapeoctal1_state][9] = stringliteralstart_state,
    [stringescapeoctal1_state][38] = stringliteralstart_state,
    [stringescapeoctal1_state][97] = stringliteralstart_state,
    [stringescapeoctal1_state][57] = stringliteral_state,
    [stringescapeoctal1_state][2] = stringliteralstart_state,
    [stringescapeoctal1_state][3] = stringliteralstart_state,
    [stringescapeoctal1_state][4] = stringliteralstart_state,
    [stringescapeoctal1_state][5] = stringliteralstart_state,
    [stringescapeoctal1_state][6] = stringliteralstart_state,
    [stringescapeoctal1_state][7] = stringliteralstart_state,
    [stringescapeoctal1_state][8] = stringliteralstart_state,
    [stringescapeoctal1_state][10] = stringliteralstart_state,
    [stringescapeoctal1_state][11] = stringliteralstart_state,
    [stringescapeoctal1_state][12] = stringliteralstart_state,
    [stringescapeoctal1_state][13] = stringliteralstart_state,
    [stringescapeoctal1_state][14] = stringliteralstart_state,
    [stringescapeoctal1_state][15] = stringliteralstart_state,
    [stringescapeoctal1_state][17] = stringliteralstart_state,
    [stringescapeoctal1_state][18] = stringliteralstart_state,
    [stringescapeoctal1_state][19] = stringliteralstart_state,
    [stringescapeoctal1_state][20] = stringliteralstart_state,
    [stringescapeoctal1_state][21] = stringliteralstart_state,
    [stringescapeoctal1_state][22] = stringliteralstart_state,
    [stringescapeoctal1_state][23] = stringliteralstart_state,
    [stringescapeoctal1_state][24] = stringliteralstart_state,
    [stringescapeoctal1_state][26] = stringliteralstart_state,
    [stringescapeoctal1_state][27] = stringliteralstart_state,
    [stringescapeoctal1_state][28] = stringliteralstart_state,
    [stringescapeoctal1_state][30] = stringliteralstart_state,
    [stringescapeoctal1_state][31] = stringliteralstart_state,
    [stringescapeoctal1_state][32] = stringliteralstart_state,
    [stringescapeoctal1_state][34] = stringliteralstart_state,
    [stringescapeoctal1_state][35] = stringliteralstart_state,
    [stringescapeoctal1_state][36] = stringliteralstart_state,
    [stringescapeoctal1_state][37] = stringliteralstart_state,
    [stringescapeoctal1_state][39] = stringliteralstart_state,
    [stringescapeoctal1_state][40] = stringliteralstart_state,
    [stringescapeoctal1_state][41] = stringliteralstart_state,
    [stringescapeoctal1_state][43] = stringliteralstart_state,
    [stringescapeoctal1_state][44] = stringliteralstart_state,
    [stringescapeoctal1_state][45] = stringliteralstart_state,
    [stringescapeoctal1_state][46] = stringliteralstart_state,
    [stringescapeoctal1_state][47] = stringliteralstart_state,
    [stringescapeoctal1_state][48] = stringliteralstart_state,
    [stringescapeoctal1_state][49] = stringliteralstart_state,
    [stringescapeoctal1_state][50] = stringliteralstart_state,
    [stringescapeoctal1_state][51] = stringliteralstart_state,
    [stringescapeoctal1_state][52] = stringliteralstart_state,
    [stringescapeoctal1_state][53] = stringliteralstart_state,
    [stringescapeoctal1_state][54] = stringliteralstart_state,
    [stringescapeoctal1_state][55] = stringliteralstart_state,
    [stringescapeoctal1_state][56] = stringliteralstart_state,
    [stringescapeoctal1_state][58] = stringliteralstart_state,
    [stringescapeoctal1_state][59] = stringliteralstart_state,
    [stringescapeoctal1_state][60] = stringliteralstart_state,
    [stringescapeoctal1_state][61] = stringliteralstart_state,
    [stringescapeoctal1_state][62] = stringliteralstart_state,
    [stringescapeoctal1_state][63] = stringliteralstart_state,
    [stringescapeoctal1_state][64] = stringliteralstart_state,
    [stringescapeoctal1_state][65] = stringliteralstart_state,
    [stringescapeoctal1_state][66] = stringliteralstart_state,
    [stringescapeoctal1_state][67] = stringliteralstart_state,
    [stringescapeoctal1_state][68] = stringliteralstart_state,
    [stringescapeoctal1_state][69] = stringliteralstart_state,
    [stringescapeoctal1_state][70] = stringliteralstart_state,
    [stringescapeoctal1_state][71] = stringliteralstart_state,
    [stringescapeoctal1_state][72] = stringliteralstart_state,
    [stringescapeoctal1_state][73] = stringliteralstart_state,
    [stringescapeoctal1_state][74] = stringliteralstart_state,
    [stringescapeoctal1_state][75] = stringliteralstart_state,
    [stringescapeoctal1_state][76] = stringliteralstart_state,
    [stringescapeoctal1_state][77] = stringliteralstart_state,
    [stringescapeoctal1_state][78] = stringliteralstart_state,
    [stringescapeoctal1_state][80] = stringliteralstart_state,
    [stringescapeoctal1_state][81] = stringliteralstart_state,
    [stringescapeoctal1_state][82] = stringliteralstart_state,
    [stringescapeoctal1_state][83] = stringliteralstart_state,
    [stringescapeoctal1_state][84] = stringliteralstart_state,
    [stringescapeoctal1_state][85] = stringliteralstart_state,
    [stringescapeoctal1_state][86] = stringliteralstart_state,
    [stringescapeoctal1_state][87] = stringliteralstart_state,
    [stringescapeoctal1_state][88] = stringliteralstart_state,
    [stringescapeoctal1_state][89] = stringliteralstart_state,
    [stringescapeoctal1_state][90] = stringliteralstart_state,
    [stringescapeoctal1_state][91] = stringliteralstart_state,
    [stringescapeoctal1_state][92] = stringliteralstart_state,
    [stringescapeoctal1_state][93] = stringliteralstart_state,
    [stringescapeoctal1_state][94] = stringliteralstart_state,
    [stringescapeoctal1_state][95] = stringliteralstart_state,
    [stringescapeoctal1_state][96] = stringliteralstart_state,
    [stringescapehexempty_state][9] = stringescapehex_state,
    [stringescapehexempty_state][11] = stringescapehex_state,
    [stringescapehexempty_state][12] = stringescapehex_state,
    [stringescapehexempty_state][64] = stringescapehex_state,
    [stringescapehexempty_state][65] = stringescapehex_state,
    [stringescapehexempty_state][16] = stringescapehex_state,
    [stringescapehexempty_state][18] = stringescapehex_state,
    [stringescapehexempty_state][19] = stringescapehex_state,
    [stringescapehexempty_state][21] = stringescapehex_state,
    [stringescapehexempty_state][25] = stringescapehex_state,
    [stringescapehexempty_state][79] = stringescapehex_state,
    [stringescapehexempty_state][81] = stringescapehex_state,
    [stringescapehexempty_state][26] = stringescapehex_state,
    [stringescapehexempty_state][33] = stringescapehex_state,
    [stringescapehexempty_state][89] = stringescapehex_state,
    [stringescapehexempty_state][38] = stringescapehex_state,
    [stringescapehexempty_state][42] = stringescapehex_state,
    [stringescapehexempty_state][45] = stringescapehex_state,
    [stringescapehexempty_state][94] = stringescapehex_state,
    [stringescapehexempty_state][95] = stringescapehex_state,
    [stringescapehexempty_state][49] = stringescapehex_state,
    [stringescapehexempty_state][97] = stringescapehex_state,
    [stringescapehex_state][2] = stringliteralstart_state,
    [stringescapehex_state][3] = stringliteralstart_state,
    [stringescapehex_state][4] = stringliteralstart_state,
    [stringescapehex_state][5] = stringliteralstart_state,
    [stringescapehex_state][6] = stringliteralstart_state,
    [stringescapehex_state][7] = stringliteralstart_state,
    [stringescapehex_state][8] = stringliteralstart_state,
    [stringescapehex_state][9] = stringliteralstart_state,
    [stringescapehex_state][10] = stringliteralstart_state,
    [stringescapehex_state][11] = stringliteralstart_state,
    [stringescapehex_state][12] = stringliteralstart_state,
    [stringescapehex_state][13] = stringliteralstart_state,
    [stringescapehex_state][14] = stringliteralstart_state,
    [stringescapehex_state][15] = stringliteralstart_state,
    [stringescapehex_state][16] = stringliteralstart_state,
    [stringescapehex_state][17] = stringliteralstart_state,
    [stringescapehex_state][18] = stringliteralstart_state,
    [stringescapehex_state][19] = stringliteralstart_state,
    [stringescapehex_state][20] = stringliteralstart_state,
    [stringescapehex_state][21] = stringliteralstart_state,
    [stringescapehex_state][22] = stringliteralstart_state,
    [stringescapehex_state][23] = stringliteralstart_state,
    [stringescapehex_state][24] = stringliteralstart_state,
    [stringescapehex_state][25] = stringliteralstart_state,
    [stringescapehex_state][26] = stringliteralstart_state,
    [stringescapehex_state][27] = stringliteralstart_state,
    [stringescapehex_state][28] = stringliteralstart_state,
    [stringescapehex_state][30] = stringliteralstart_state,
    [stringescapehex_state][31] = stringliteralstart_state,
    [stringescapehex_state][32] = stringliteralstart_state,
    [stringescapehex_state][33] = stringliteralstart_state,
    [stringescapehex_state][34] = stringliteralstart_state,
    [stringescapehex_state][35] = stringliteralstart_state,
    [stringescapehex_state][36] = stringliteralstart_state,
    [stringescapehex_state][37] = stringliteralstart_state,
    [stringescapehex_state][38] = stringliteralstart_state,
    [stringescapehex_state][39] = stringliteralstart_state,
    [stringescapehex_state][40] = stringliteralstart_state,
    [stringescapehex_state][41] = stringliteralstart_state,
    [stringescapehex_state][42] = stringliteralstart_state,
    [stringescapehex_state][43] = stringliteralstart_state,
    [stringescapehex_state][44] = stringliteralstart_state,
    [stringescapehex_state][45] = stringliteralstart_state,
    [stringescapehex_state][46] = stringliteralstart_state,
    [stringescapehex_state][47] = stringliteralstart_state,
    [stringescapehex_state][48] = stringliteralstart_state,
    [stringescapehex_state][49] = stringliteralstart_state,
    [stringescapehex_state][50] = stringliteralstart_state,
    [stringescapehex_state][51] = stringliteralstart_state,
    [stringescapehex_state][52] = stringliteralstart_state,
    [stringescapehex_state][53] = stringliteralstart_state,
    [stringescapehex_state][54] = stringliteralstart_state,
    [stringescapehex_state][55] = stringliteralstart_state,
    [stringescapehex_state][56] = stringliteralstart_state,
    [stringescapehex_state][57] = stringliteralstart_state,
    [stringescapehex_state][58] = stringliteralstart_state,
    [stringescapehex_state][59] = stringliteralstart_state,
    [stringescapehex_state][60] = stringliteralstart_state,
    [stringescapehex_state][61] = stringliteralstart_state,
    [stringescapehex_state][62] = stringliteralstart_state,
    [stringescapehex_state][63] = stringliteralstart_state,
    [stringescapehex_state][64] = stringliteralstart_state,
    [stringescapehex_state][65] = stringliteralstart_state,
    [stringescapehex_state][66] = stringliteralstart_state,
    [stringescapehex_state][67] = stringliteralstart_state,
    [stringescapehex_state][68] = stringliteralstart_state,
    [stringescapehex_state][69] = stringliteralstart_state,
    [stringescapehex_state][70] = stringliteralstart_state,
    [stringescapehex_state][71] = stringliteralstart_state,
    [stringescapehex_state][72] = stringliteralstart_state,
    [stringescapehex_state][73] = stringliteralstart_state,
    [stringescapehex_state][74] = stringliteralstart_state,
    [stringescapehex_state][75] = stringliteralstart_state,
    [stringescapehex_state][76] = stringliteralstart_state,
    [stringescapehex_state][77] = stringliteralstart_state,
    [stringescapehex_state][78] = stringliteralstart_state,
    [stringescapehex_state][79] = stringliteralstart_state,
    [stringescapehex_state][80] = stringliteralstart_state,
    [stringescapehex_state][81] = stringliteralstart_state,
    [stringescapehex_state][82] = stringliteralstart_state,
    [stringescapehex_state][83] = stringliteralstart_state,
    [stringescapehex_state][84] = stringliteralstart_state,
    [stringescapehex_state][85] = stringliteralstart_state,
    [stringescapehex_state][86] = stringliteralstart_state,
    [stringescapehex_state][87] = stringliteralstart_state,
    [stringescapehex_state][88] = stringliteralstart_state,
    [stringescapehex_state][89] = stringliteralstart_state,
    [stringescapehex_state][90] = stringliteralstart_state,
    [stringescapehex_state][91] = stringliteralstart_state,
    [stringescapehex_state][92] = stringliteralstart_state,
    [stringescapehex_state][93] = stringliteralstart_state,
    [stringescapehex_state][94] = stringliteralstart_state,
    [stringescapehex_state][95] = stringliteralstart_state,
    [stringescapehex_state][96] = stringliteralstart_state,
    [stringescapehex_state][97] = stringliteralstart_state,
    [nondecimal_state][39] = hexadecimal_state,
    [nondecimal_state][91] = hexadecimal_state,
    [nondecimal_state][25] = octal_state,
    [nondecimal_state][42] = octal_state,
    [nondecimal_state][79] = octal_state,
    [nondecimal_state][16] = octal_state,
    [nondecimal_state][33] = octal_state,
    [nondecimal_state][9] = octal_state,
    [nondecimal_state][38] = octal_state,
    [nondecimal_state][97] = octal_state,
    [octal_state][25] = octal_state,
    [octal_state][42] = octal_state,
    [octal_state][79] = octal_state,
    [octal_state][16] = octal_state,
    [octal_state][33] = octal_state,
    [octal_state][9] = octal_state,
    [octal_state][38] = octal_state,
    [octal_state][97] = octal_state,
    [octal_state][36] = octal_state,
    [octal_state][2] = fraction_state,
    [octal_state][83] = oct_u_state,
    [octal_state][14] = oct_u_state,
    [octal_state][77] = oct_l_state,
    [octal_state][27] = oct_L_state,
    [octal_state][75] = oct_w_state,
    [octal_state][56] = oct_W_state,
    [oct_u_state][77] = oct_ul_state,
    [oct_u_state][27] = oct_uL_state,
    [oct_u_state][75] = oct_uw_state,
    [oct_u_state][56] = oct_uW_state,
    [oct_l_state][77] = oct_ll_state,
    [oct_l_state][83] = oct_lu_state,
    [oct_l_state][14] = oct_lu_state,
    [oct_L_state][27] = oct_ll_state,
    [oct_L_state][83] = oct_lu_state,
    [oct_L_state][14] = oct_lu_state,
    [oct_w_state][81] = oct_wb_state,
    [oct_W_state][11] = oct_wb_state,
    [oct_ul_state][77] = oct_ull_state,
    [oct_uL_state][27] = oct_ull_state,
    [oct_uw_state][81] = oct_uwb_state,
    [oct_uW_state][11] = oct_uwb_state,
    [oct_ll_state][83] = oct_ull_state,
    [oct_ll_state][14] = oct_ull_state,
    [oct_wb_state][83] = oct_uwb_state,
    [oct_wb_state][14] = oct_uwb_state,
    [hexadecimal_state][9] = hexadecimal_state,
    [hexadecimal_state][11] = hexadecimal_state,
    [hexadecimal_state][12] = hexadecimal_state,
    [hexadecimal_state][64] = hexadecimal_state,
    [hexadecimal_state][65] = hexadecimal_state,
    [hexadecimal_state][16] = hexadecimal_state,
    [hexadecimal_state][18] = hexadecimal_state,
    [hexadecimal_state][19] = hexadecimal_state,
    [hexadecimal_state][21] = hexadecimal_state,
    [hexadecimal_state][25] = hexadecimal_state,
    [hexadecimal_state][79] = hexadecimal_state,
    [hexadecimal_state][81] = hexadecimal_state,
    [hexadecimal_state][26] = hexadecimal_state,
    [hexadecimal_state][33] = hexadecimal_state,
    [hexadecimal_state][89] = hexadecimal_state,
    [hexadecimal_state][38] = hexadecimal_state,
    [hexadecimal_state][42] = hexadecimal_state,
    [hexadecimal_state][45] = hexadecimal_state,
    [hexadecimal_state][94] = hexadecimal_state,
    [hexadecimal_state][95] = hexadecimal_state,
    [hexadecimal_state][49] = hexadecimal_state,
    [hexadecimal_state][97] = hexadecimal_state,
    [hexadecimal_state][36] = hexadecimal_state,
    [hexadecimal_state][2] = hexfraction_state,
    [hexadecimal_state][83] = hex_u_state,
    [hexadecimal_state][14] = hex_u_state,
    [hexadecimal_state][77] = hex_l_state,
    [hexadecimal_state][27] = hex_L_state,
    [hexadecimal_state][75] = hex_w_state,
    [hexadecimal_state][56] = hex_W_state,
    [hex_u_state][77] = hex_ul_state,
    [hex_u_state][27] = hex_uL_state,
    [hex_u_state][75] = hex_uw_state,
    [hex_u_state][56] = hex_uW_state,
    [hex_l_state][77] = hex_ll_state,
    [hex_l_state][83] = hex_lu_state,
    [hex_l_state][14] = hex_lu_state,
    [hex_L_state][27] = hex_ll_state,
    [hex_L_state][83] = hex_lu_state,
    [hex_L_state][14] = hex_lu_state,
    [hex_w_state][81] = hex_wb_state,
    [hex_W_state][11] = hex_wb_state,
    [hex_ul_state][77] = hex_ull_state,
    [hex_uL_state][27] = hex_ull_state,
    [hex_uw_state][81] = hex_uwb_state,
    [hex_uW_state][11] = hex_uwb_state,
    [hex_ll_state][83] = hex_ull_state,
    [hex_ll_state][14] = hex_ull_state,
    [hex_wb_state][83] = hex_uwb_state,
    [hex_wb_state][14] = hex_uwb_state,
    [decimal_state][12] = decimal_state,
    [decimal_state][25] = decimal_state,
    [decimal_state][42] = decimal_state,
    [decimal_state][79] = decimal_state,
    [decimal_state][16] = decimal_state,
    [decimal_state][45] = decimal_state,
    [decimal_state][33] = decimal_state,
    [decimal_state][9] = decimal_state,
    [decimal_state][38] = decimal_state,
    [decimal_state][97] = decimal_state,
    [decimal_state][36] = decimal_state,
    [decimal_state][2] = decimalfraction_state,
    [decimal_state][83] = decimal_u_state,
    [decimal_state][14] = decimal_u_state,
    [decimal_state][77] = decimal_l_state,
    [decimal_state][27] = decimal_L_state,
    [decimal_state][75] = decimal_w_state,
    [decimal_state][56] = decimal_W_state,
    [decimal_u_state][77] = decimal_ul_state,
    [decimal_u_state][27] = decimal_uL_state,
    [decimal_u_state][75] = decimal_uw_state,
    [decimal_u_state][56] = decimal_uW_state,
    [decimal_l_state][77] = decimal_ll_state,
    [decimal_l_state][83] = decimal_lu_state,
    [decimal_l_state][14] = decimal_lu_state,
    [decimal_L_state][27] = decimal_ll_state,
    [decimal_L_state][83] = decimal_lu_state,
    [decimal_L_state][14] = decimal_lu_state,
    [decimal_w_state][81] = decimal_wb_state,
    [decimal_W_state][11] = decimal_wb_state,
    [decimal_ul_state][77] = decimal_ull_state,
    [decimal_uL_state][27] = decimal_ull_state,
    [decimal_uw_state][81] = decimal_uwb_state,
    [decimal_uW_state][11] = decimal_uwb_state,
    [decimal_ll_state][83] = decimal_ull_state,
    [decimal_ll_state][14] = decimal_ull_state,
    [decimal_wb_state][83] = decimal_uwb_state,
    [decimal_wb_state][14] = decimal_uwb_state
};

static enum tokenType stateMachine_correspondingTokens[STATECOUNT] = {
    [newline_state] = newline_token,
    [lparen_state] = lparen_token,
    [rparen_state] = rparen_token,
    [lcurly_state] = lcurly_token,
    [rcurly_state] = rcurly_token,
    [rbracket_state] = rbracket_token,
    [lbracket_state] = lbracket_token,
    [question_state] = question_token,
    [semicolon_state] = semicolon_token,
    [colon_state] = colon_token,
    [comma_state] = comma_token,
    [dot_state] = dot_token,
    [eof_state] = eof_token,
    [start_state] = bad_token,
    [identifier_state] = identifier_token,
    [modeq_state] = modeq_token,
    [mod_state] = mod_token,
    [minuseq_state] = minuseq_token,
    [arrow_state] = arrow_token,
    [minus_state] = minus_token,
    [xoreq_state] = xoreq_token,
    [caret_state] = caret_token,
    [bnoteq_state] = bnoteq_token,
    [tilde_state] = tilde_token,
    [boreq_state] = boreq_token,
    [lor_state] = lor_token,
    [pipe_state] = pipe_token,
    [eq_state] = eq_token,
    [assignment_state] = assignment_token,
    [pluseq_state] = pluseq_token,
    [plus_state] = plus_token,
    [shiftleft_state] = shiftleft_token,
    [le_state] = le_token,
    [langle_state] = langle_token,
    [shiftright_state] = shiftright_token,
    [ge_state] = ge_token,
    [rangle_state] = rangle_token,
    [div_state] = div_token,
    [cantmove_state] = cantmove_token,
    [linecomment_state] = linecomment_token,
    [blockcomment_state] = bad_token,
    [blockcommentweak_state] = bad_token,
    [blockcommentfinish_state] = blockcomment_token,
    [bandeq_state] = bandeq_token,
    [and_state] = and_token,
    [amp_state] = amp_token,
    [timeseq_state] = timeseq_token,
    [star_state] = star_token,
    [noteq_state] = noteq_token,
    [exc_state] = exc_token,
    [preproc_state] = preproc_token,
    [whitespace_state] = whitespace_token,
    [charliteralstart_state] = bad_token,
    [charliteral_state] = charliteral_token,
    [charliteralchewedone_state] = bad_token,
    [charliteralescape_state] = bad_token,
    [charescapeoctal0_state] = bad_token,
    [charescapeoctal1_state] = bad_token,
    [charescapehexempty_state] = bad_token,
    [charescapehex_state] = bad_token,
    [stringliteral_state] = stringliteral_token,
    [stringliteralstart_state] = bad_token,
    [stringliteralescape_state] = bad_token,
    [stringescapeoctal0_state] = bad_token,
    [stringescapeoctal1_state] = bad_token,
    [stringescapehexempty_state] = bad_token,
    [stringescapehex_state] = bad_token,
    [nondecimal_state] = octal_token,
    [fraction_state] = fraction_token,
    [octal_state] = octal_token,
    [oct_u_state] = oct_u_token,
    [oct_lu_state] = oct_lu_token,
    [oct_l_state] = oct_l_token,
    [oct_L_state] = oct_l_token,
    [oct_w_state] = bad_token,
    [oct_W_state] = bad_token,
    [oct_ull_state] = oct_ull_token,
    [oct_ul_state] = oct_lu_token,
    [oct_uL_state] = oct_lu_token,
    [oct_uwb_state] = oct_uwb_token,
    [oct_uw_state] = bad_token,
    [oct_uW_state] = bad_token,
    [oct_ll_state] = oct_ll_token,
    [oct_wb_state] = oct_wb_token,
    [hexfraction_state] = hexfraction_token,
    [hexadecimal_state] = hexadecimal_token,
    [hex_u_state] = hex_u_token,
    [hex_lu_state] = hex_lu_token,
    [hex_l_state] = hex_l_token,
    [hex_L_state] = hex_l_token,
    [hex_w_state] = bad_token,
    [hex_W_state] = bad_token,
    [hex_ull_state] = hex_ull_token,
    [hex_ul_state] = hex_lu_token,
    [hex_uL_state] = hex_lu_token,
    [hex_uwb_state] = hex_uwb_token,
    [hex_uw_state] = bad_token,
    [hex_uW_state] = bad_token,
    [hex_ll_state] = hex_ll_token,
    [hex_wb_state] = hex_wb_token,
    [decimalfraction_state] = decimalfraction_token,
    [decimal_state] = decimal_token,
    [decimal_u_state] = decimal_u_token,
    [decimal_lu_state] = decimal_lu_token,
    [decimal_l_state] = decimal_l_token,
    [decimal_L_state] = decimal_l_token,
    [decimal_w_state] = bad_token,
    [decimal_W_state] = bad_token,
    [decimal_ull_state] = decimal_ull_token,
    [decimal_ul_state] = decimal_lu_token,
    [decimal_uL_state] = decimal_lu_token,
    [decimal_uwb_state] = decimal_uwb_token,
    [decimal_uw_state] = bad_token,
    [decimal_uW_state] = bad_token,
    [decimal_ll_state] = decimal_ll_token,
    [decimal_wb_state] = decimal_wb_token
};

static unsigned char asciiEnumeration[] = {
    ['\n']=1,
    ['.']=2,
    ['t']=3,
    ['r']=4,
    ['}']=5,
    ['T']=6,
    [')']=7,
    ['\r']=8,
    ['4']=9,
    ['|']=10,
    ['B']=11,
    ['8']=12,
    ['-']=13,
    ['U']=14,
    ['h']=15,
    ['3']=16,
    ['_']=17,
    ['C']=18,
    ['F']=19,
    [',']=20,
    ['c']=21,
    ['K']=22,
    ['~']=23,
    ['Q']=24,
    ['1']=25,
    ['e']=26,
    ['L']=27,
    ['o']=28,
    [255]=29,
    ['R']=30,
    ['S']=31,
    ['P']=32,
    ['5']=33,
    ['n']=34,
    [']']=35,
    ['\'']=36,
    [':']=37,
    ['2']=38,
    ['x']=39,
    ['%']=40,
    [244]=41,
    ['6']=42,
    [' ']=43,
    ['*']=44,
    ['9']=45,
    ['>']=46,
    ['!']=47,
    ['i']=48,
    ['A']=49,
    ['&']=50,
    ['\t']=51,
    ['Z']=52,
    ['k']=53,
    ['q']=54,
    ['^']=55,
    ['W']=56,
    ['"']=57,
    ['=']=58,
    ['G']=59,
    ['N']=60,
    ['y']=61,
    ['V']=62,
    ['p']=63,
    ['d']=64,
    ['f']=65,
    ['s']=66,
    ['#']=67,
    ['I']=68,
    ['H']=69,
    ['{']=70,
    ['z']=71,
    ['M']=72,
    ['J']=73,
    ['\\']=74,
    ['w']=75,
    [';']=76,
    ['l']=77,
    ['<']=78,
    ['7']=79,
    ['/']=80,
    ['b']=81,
    ['?']=82,
    ['u']=83,
    ['v']=84,
    ['m']=85,
    ['+']=86,
    ['Y']=87,
    ['(']=88,
    ['D']=89,
    ['O']=90,
    ['X']=91,
    ['g']=92,
    ['[']=93,
    ['E']=94,
    ['a']=95,
    ['j']=96,
    ['0']=97
};

