
#pragma once
#include <ctype.h>
enum state {
    STARTSTATE,
    IDENTIFIERSTATE,
    INTEGERSTATE,
    FRACTIONSTATE,
    CANTMOVESTATE,
    MODSTATE,
    MODEQSTATE,
    MINUSSTATE,
    MINUSEQSTATE,
    CARETSTATE,
    XOREQSTATE,
    TILDESTATE,
    BNOTEQSTATE,
    QUESTIONSTATE,
    LPARENSTATE,
    RPARENSTATE,
    LCURLYSTATE,
    RCURLYSTATE,
    LBRACKETSTATE,
    RBRACKETSTATE,
    PIPESTATE,
    BOREQSTATE,
    LORSTATE,
    COLONSTATE,
    SEMICOLONSTATE,
    ASSIGNMENTSTATE,
    EQSTATE,
    PLUSSTATE,
    PLUSEQSTATE,
    LANGLESTATE,
    LEQSTATE,
    RANGLESTATE,
    GEQSTATE,
    QUOTESTATE,
    QUOTESUSPENDSTATE,
    QUOTEFINISHSTATE,
    SHIFTLEFTSTATE,
    SHIFTRIGHTSTATE,
    SLASHSTATE,
    LINECOMMENTSTATE,
    BLOCKCOMMENTSTATE,
    BLOCKCOMMENTMAYBESTATE,
    BLOCKCOMMENTFINISHSTATE,
    AMPSTATE,
    BANDEQSTATE,
    ANDSTATE,
    STARSTATE,
    TIMESEQSTATE,
    COMMASTATE,
    DOTSTATE,
    EXCSTATE,
    NOTEQSTATE,
    PREPROCSTATE,
    WHITESPACESTATE,
    NEWLINESTATE,
    EOFSTATE,
    LASTSTATE
};

enum charType {
    LETTERCHAR,
    DIGITCHAR,
    NEWLINECHAR,
    WHITESPACECHAR,
    MODCHAR,
    MINUSCHAR,
    PLUSCHAR,
    CARETCHAR,
    TILDECHAR,
    LPARENCHAR,
    RPARENCHAR,
    LCURLYCHAR,
    RCURLYCHAR,
    RBRACKETCHAR,
    LBRACKETCHAR,
    QUESTIONCHAR,
    SEMICOLONCHAR,
    COLONCHAR,
    EQCHAR,
    LANGLECHAR,
    RANGLECHAR,
    EOFCHAR,
    SLASHCHAR,
    STARCHAR,
    HASHCHAR,
    AMPCHAR,
    COMMACHAR,
    DOTCHAR,
    EXCCHAR,
    QUOTECHAR,
    PIPECHAR,
    BSLASHCHAR,
    BADCHAR,
    LASTCHAR
};

typedef struct {
    enum state state;
    enum state transitions[LASTSTATE][LASTCHAR];
    enum tokenType correspondingTokens[LASTSTATE];
} stateMachine_t;

static enum charType getCharType(int c) {
    if (isalpha(c) || c == '_') return LETTERCHAR;
    if (isdigit(c)) return DIGITCHAR;
    if (c == '\n') return NEWLINECHAR;
    if (isspace(c)) return WHITESPACECHAR;
    if (c == '+') return PLUSCHAR;
    if (c == '#') return HASHCHAR;
    if (c == '*') return STARCHAR;
    if (c == '&') return AMPCHAR;
    if (c == '/') return SLASHCHAR;
    if (c == '*') return STARCHAR;
    if (c == '!') return EXCCHAR;
    if (c == '(') return LPARENCHAR;
    if (c == ')') return RPARENCHAR;
    if (c == '{') return LCURLYCHAR;
    if (c == '}') return RCURLYCHAR;
    if (c == '.') return DOTCHAR;
    if (c == ',') return COMMACHAR;
    if (c == '|') return PIPECHAR;
    if (c == ';') return SEMICOLONCHAR;
    if (c == '=') return EQCHAR;
    if (c == '"') return QUOTECHAR;
    if (c == '\\') return BSLASHCHAR;
    if (c == '<') return LANGLECHAR;
    if (c == '>') return RANGLECHAR;
    if (c == EOF) return EOFCHAR;
    return BADCHAR;
}

static int stateMachine_update(stateMachine_t* t, int c, enum tokenType* currentTok) {
    enum charType charType = getCharType(c);
    enum state newState = t->transitions[t->state][charType];
    *currentTok = t->correspondingTokens[t->state];
    t->state = newState;
    return t->state;
}

static void stateMachine_init(stateMachine_t* t) {
    t->state = STARTSTATE;
    for (int i = 0; i < LASTSTATE; i++) {
        for (int j = 0; j < LASTCHAR; j++) {
            t->transitions[i][j] = CANTMOVESTATE;
        }
    }
    t->transitions[STARTSTATE][LETTERCHAR] = IDENTIFIERSTATE;
    t->transitions[STARTSTATE][DIGITCHAR] = INTEGERSTATE;
    t->transitions[STARTSTATE][NEWLINECHAR] = NEWLINESTATE;
    t->transitions[STARTSTATE][WHITESPACECHAR] = WHITESPACESTATE;
    t->transitions[STARTSTATE][MODCHAR] = MODSTATE;
    t->transitions[STARTSTATE][MINUSCHAR] = MINUSSTATE;
    t->transitions[STARTSTATE][PLUSCHAR] = PLUSSTATE;
    t->transitions[STARTSTATE][CARETCHAR] = CARETSTATE;
    t->transitions[STARTSTATE][TILDECHAR] = TILDESTATE;
    t->transitions[STARTSTATE][LPARENCHAR] = LPARENSTATE;
    t->transitions[STARTSTATE][RPARENCHAR] = RPARENSTATE;
    t->transitions[STARTSTATE][LCURLYCHAR] = LCURLYSTATE;
    t->transitions[STARTSTATE][RCURLYCHAR] = RCURLYSTATE;
    t->transitions[STARTSTATE][RBRACKETCHAR] = RBRACKETSTATE;
    t->transitions[STARTSTATE][LBRACKETCHAR] = LBRACKETSTATE;
    t->transitions[STARTSTATE][QUESTIONCHAR] = QUESTIONSTATE;
    t->transitions[STARTSTATE][SEMICOLONCHAR] = SEMICOLONSTATE;
    t->transitions[STARTSTATE][COLONCHAR] = COLONSTATE;
    t->transitions[STARTSTATE][EQCHAR] = ASSIGNMENTSTATE;
    t->transitions[STARTSTATE][LANGLECHAR] = LANGLESTATE;
    t->transitions[STARTSTATE][RANGLECHAR] = RANGLESTATE;
    t->transitions[STARTSTATE][EOFCHAR] = EOFSTATE;
    t->transitions[STARTSTATE][SLASHCHAR] = SLASHSTATE;
    t->transitions[STARTSTATE][STARCHAR] = STARSTATE;
    t->transitions[STARTSTATE][HASHCHAR] = PREPROCSTATE;
    t->transitions[STARTSTATE][AMPCHAR] = AMPSTATE;
    t->transitions[STARTSTATE][COMMACHAR] = COMMASTATE;
    t->transitions[STARTSTATE][DOTCHAR] = DOTSTATE;
    t->transitions[STARTSTATE][EXCCHAR] = EXCSTATE;
    t->transitions[STARTSTATE][QUOTECHAR] = QUOTESTATE;
    t->transitions[STARTSTATE][PIPECHAR] = PIPESTATE;
    t->transitions[IDENTIFIERSTATE][LETTERCHAR] = IDENTIFIERSTATE;
    t->transitions[INTEGERSTATE][DIGITCHAR] = INTEGERSTATE;
    t->transitions[INTEGERSTATE][DOTCHAR] = FRACTIONSTATE;
    t->transitions[FRACTIONSTATE][DIGITCHAR] = FRACTIONSTATE;
    t->transitions[MODSTATE][EQCHAR] = MODEQSTATE;
    t->transitions[MINUSSTATE][EQCHAR] = MINUSEQSTATE;
    t->transitions[CARETSTATE][EQCHAR] = XOREQSTATE;
    t->transitions[TILDESTATE][EQCHAR] = BNOTEQSTATE;
    t->transitions[PIPESTATE][EQCHAR] = BOREQSTATE;
    t->transitions[PIPESTATE][PIPECHAR] = LORSTATE;
    t->transitions[ASSIGNMENTSTATE][EQCHAR] = EQSTATE;
    t->transitions[PLUSSTATE][EQCHAR] = PLUSEQSTATE;
    t->transitions[LANGLESTATE][EQCHAR] = LEQSTATE;
    t->transitions[LANGLESTATE][LANGLECHAR] = SHIFTLEFTSTATE;
    t->transitions[RANGLESTATE][EQCHAR] = GEQSTATE;
    t->transitions[QUOTESTATE][LETTERCHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][DIGITCHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][NEWLINECHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][WHITESPACECHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][MODCHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][MINUSCHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][PLUSCHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][CARETCHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][TILDECHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][LPARENCHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][RPARENCHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][LCURLYCHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][RCURLYCHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][RBRACKETCHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][LBRACKETCHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][QUESTIONCHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][SEMICOLONCHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][COLONCHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][EQCHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][LANGLECHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][RANGLECHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][SLASHCHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][STARCHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][HASHCHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][AMPCHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][COMMACHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][DOTCHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][EXCCHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][QUOTECHAR] = QUOTEFINISHSTATE;
    t->transitions[QUOTESTATE][PIPECHAR] = QUOTESTATE;
    t->transitions[QUOTESTATE][BSLASHCHAR] = QUOTESUSPENDSTATE;
    t->transitions[QUOTESTATE][BADCHAR] = QUOTESUSPENDSTATE;
    t->transitions[QUOTESUSPENDSTATE][LETTERCHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][DIGITCHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][NEWLINECHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][WHITESPACECHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][MODCHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][MINUSCHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][PLUSCHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][CARETCHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][TILDECHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][LPARENCHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][RPARENCHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][LCURLYCHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][RCURLYCHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][RBRACKETCHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][LBRACKETCHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][QUESTIONCHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][SEMICOLONCHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][COLONCHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][EQCHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][LANGLECHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][RANGLECHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][SLASHCHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][STARCHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][HASHCHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][AMPCHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][COMMACHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][DOTCHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][EXCCHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][QUOTECHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][PIPECHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][BSLASHCHAR] = QUOTESTATE;
    t->transitions[QUOTESUSPENDSTATE][BADCHAR] = QUOTESTATE;
    t->transitions[SLASHSTATE][SLASHCHAR] = LINECOMMENTSTATE;
    t->transitions[SLASHSTATE][STARCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][LETTERCHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][DIGITCHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][WHITESPACECHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][MODCHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][MINUSCHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][PLUSCHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][CARETCHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][TILDECHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][LPARENCHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][RPARENCHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][LCURLYCHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][RCURLYCHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][RBRACKETCHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][LBRACKETCHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][QUESTIONCHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][SEMICOLONCHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][COLONCHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][EQCHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][LANGLECHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][RANGLECHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][SLASHCHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][STARCHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][HASHCHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][AMPCHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][COMMACHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][DOTCHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][EXCCHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][QUOTECHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][PIPECHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][BSLASHCHAR] = LINECOMMENTSTATE;
    t->transitions[LINECOMMENTSTATE][BADCHAR] = LINECOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][LETTERCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][DIGITCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][NEWLINECHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][WHITESPACECHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][MODCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][MINUSCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][PLUSCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][CARETCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][TILDECHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][LPARENCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][RPARENCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][LCURLYCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][RCURLYCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][RBRACKETCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][LBRACKETCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][QUESTIONCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][SEMICOLONCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][COLONCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][EQCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][LANGLECHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][RANGLECHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][SLASHCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][STARCHAR] = BLOCKCOMMENTMAYBESTATE;
    t->transitions[BLOCKCOMMENTSTATE][HASHCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][AMPCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][COMMACHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][DOTCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][EXCCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][QUOTECHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][PIPECHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][BSLASHCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTSTATE][BADCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][LETTERCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][DIGITCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][NEWLINECHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][WHITESPACECHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][MODCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][MINUSCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][PLUSCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][CARETCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][TILDECHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][LPARENCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][RPARENCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][LCURLYCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][RCURLYCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][RBRACKETCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][LBRACKETCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][QUESTIONCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][SEMICOLONCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][COLONCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][EQCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][LANGLECHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][RANGLECHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][SLASHCHAR] = BLOCKCOMMENTFINISHSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][STARCHAR] = BLOCKCOMMENTMAYBESTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][HASHCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][AMPCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][COMMACHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][DOTCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][EXCCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][QUOTECHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][PIPECHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][BSLASHCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[BLOCKCOMMENTMAYBESTATE][BADCHAR] = BLOCKCOMMENTSTATE;
    t->transitions[AMPSTATE][EQCHAR] = BANDEQSTATE;
    t->transitions[AMPSTATE][AMPCHAR] = ANDSTATE;
    t->transitions[STARSTATE][EQCHAR] = TIMESEQSTATE;
    t->transitions[EXCSTATE][EQCHAR] = NOTEQSTATE;
    t->transitions[PREPROCSTATE][LETTERCHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][DIGITCHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][WHITESPACECHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][MODCHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][MINUSCHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][PLUSCHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][CARETCHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][TILDECHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][LPARENCHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][RPARENCHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][LCURLYCHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][RCURLYCHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][RBRACKETCHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][LBRACKETCHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][QUESTIONCHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][SEMICOLONCHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][COLONCHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][EQCHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][LANGLECHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][RANGLECHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][SLASHCHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][STARCHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][HASHCHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][AMPCHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][COMMACHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][DOTCHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][EXCCHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][QUOTECHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][PIPECHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][BSLASHCHAR] = PREPROCSTATE;
    t->transitions[PREPROCSTATE][BADCHAR] = PREPROCSTATE;
    t->transitions[WHITESPACESTATE][NEWLINECHAR] = NEWLINESTATE;
    t->transitions[WHITESPACESTATE][WHITESPACECHAR] = WHITESPACESTATE;
    for (int i = 0; i < LASTSTATE; i++) {
        t->correspondingTokens[i] = BAD;
    }
    t->correspondingTokens[STARTSTATE] = BAD;
    t->correspondingTokens[IDENTIFIERSTATE] = IDENTIFIER;
    t->correspondingTokens[INTEGERSTATE] = INTEGER;
    t->correspondingTokens[FRACTIONSTATE] = FRACTION;
    t->correspondingTokens[CANTMOVESTATE] = BAD;
    t->correspondingTokens[MODSTATE] = MOD;
    t->correspondingTokens[MODEQSTATE] = MODEQ;
    t->correspondingTokens[MINUSSTATE] = MINUS;
    t->correspondingTokens[MINUSEQSTATE] = MINUSEQ;
    t->correspondingTokens[CARETSTATE] = XOR;
    t->correspondingTokens[XOREQSTATE] = XOREQ;
    t->correspondingTokens[TILDESTATE] = BNOT;
    t->correspondingTokens[BNOTEQSTATE] = BNOTEQ;
    t->correspondingTokens[QUESTIONSTATE] = QUESTION;
    t->correspondingTokens[LPARENSTATE] = LPAREN;
    t->correspondingTokens[RPARENSTATE] = RPAREN;
    t->correspondingTokens[LCURLYSTATE] = LCURLY;
    t->correspondingTokens[RCURLYSTATE] = RCURLY;
    t->correspondingTokens[LBRACKETSTATE] = LBRACKET;
    t->correspondingTokens[RBRACKETSTATE] = RBRACKET;
    t->correspondingTokens[PIPESTATE] = BOR;
    t->correspondingTokens[BOREQSTATE] = BOREQ;
    t->correspondingTokens[LORSTATE] = LOR;
    t->correspondingTokens[COLONSTATE] = COLON;
    t->correspondingTokens[SEMICOLONSTATE] = SEMICOLON;
    t->correspondingTokens[ASSIGNMENTSTATE] = ASSIGNMENT;
    t->correspondingTokens[EQSTATE] = EQ;
    t->correspondingTokens[PLUSSTATE] = PLUS;
    t->correspondingTokens[PLUSEQSTATE] = PLUSEQ;
    t->correspondingTokens[LANGLESTATE] = LT;
    t->correspondingTokens[LEQSTATE] = LTEQ;
    t->correspondingTokens[RANGLESTATE] = GT;
    t->correspondingTokens[GEQSTATE] = GTEQ;
    t->correspondingTokens[QUOTEFINISHSTATE] = STRING;
    t->correspondingTokens[SHIFTLEFTSTATE] = SHLEFT;
    t->correspondingTokens[SHIFTRIGHTSTATE] = SHRIGHT;
    t->correspondingTokens[SLASHSTATE] = DIVIDE;
    t->correspondingTokens[LINECOMMENTSTATE] = LINECOMMENT;
    t->correspondingTokens[BLOCKCOMMENTFINISHSTATE] = BLOCKCOMMENT;
    t->correspondingTokens[AMPSTATE] = AMP;
    t->correspondingTokens[BANDEQSTATE] = BANDEQ;
    t->correspondingTokens[ANDSTATE] = LAND;
    t->correspondingTokens[STARSTATE] = STAR;
    t->correspondingTokens[COMMASTATE] = COMMA;
    t->correspondingTokens[DOTSTATE] = DOT;
    t->correspondingTokens[EXCSTATE] = NOT;
    t->correspondingTokens[NOTEQSTATE] = NOTEQ;
    t->correspondingTokens[PREPROCSTATE] = PREPROC;
    t->correspondingTokens[WHITESPACESTATE] = WHITESPACE;
    t->correspondingTokens[NEWLINESTATE] = NEWLINE;
    t->correspondingTokens[EOFSTATE] = END;
}

