
#pragma once
enum tokenType {
    dot_token,
    caret_token,
    eq_token,
    rcurly_token,
    lcurly_token,
    question_token,
    oct_ll_token,
    hex_wb_token,
    decimal_lu_token,
    bnoteq_token,
    boreq_token,
    rbracket_token,
    hex_u_token,
    noteq_token,
    identifier_token,
    langle_token,
    hex_lu_token,
    charliteral_token,
    minus_token,
    pipe_token,
    lor_token,
    eof_token,
    stringliteral_token,
    oct_ull_token,
    hexfraction_token,
    newline_token,
    decimal_token,
    exc_token,
    octal_token,
    decimal_l_token,
    lbracket_token,
    modeq_token,
    hex_ll_token,
    minuseq_token,
    decimal_uwb_token,
    decimal_ull_token,
    fraction_token,
    assignment_token,
    amp_token,
    blockcomment_token,
    bandeq_token,
    decimalfraction_token,
    lparen_token,
    ge_token,
    hex_l_token,
    decimal_ll_token,
    bad_token,
    and_token,
    preproc_token,
    linecomment_token,
    le_token,
    hex_uwb_token,
    timeseq_token,
    star_token,
    oct_wb_token,
    comma_token,
    mod_token,
    div_token,
    colon_token,
    decimal_u_token,
    rparen_token,
    oct_uwb_token,
    hex_ull_token,
    semicolon_token,
    pluseq_token,
    whitespace_token,
    oct_u_token,
    oct_l_token,
    shiftleft_token,
    tilde_token,
    rangle_token,
    cantmove_token,
    oct_lu_token,
    shiftright_token,
    plus_token,
    hexadecimal_token,
    xoreq_token,
    decimal_wb_token,
    arrow_token,
    TOKENCOUNT
};

static const char* tokenTypeStrings[TOKENCOUNT] = {
    "dot",
    "caret",
    "eq",
    "rcurly",
    "lcurly",
    "question",
    "oct_ll",
    "hex_wb",
    "decimal_lu",
    "bnoteq",
    "boreq",
    "rbracket",
    "hex_u",
    "noteq",
    "identifier",
    "langle",
    "hex_lu",
    "charliteral",
    "minus",
    "pipe",
    "lor",
    "eof",
    "stringliteral",
    "oct_ull",
    "hexfraction",
    "newline",
    "decimal",
    "exc",
    "octal",
    "decimal_l",
    "lbracket",
    "modeq",
    "hex_ll",
    "minuseq",
    "decimal_uwb",
    "decimal_ull",
    "fraction",
    "assignment",
    "amp",
    "blockcomment",
    "bandeq",
    "decimalfraction",
    "lparen",
    "ge",
    "hex_l",
    "decimal_ll",
    "bad",
    "and",
    "preproc",
    "linecomment",
    "le",
    "hex_uwb",
    "timeseq",
    "star",
    "oct_wb",
    "comma",
    "mod",
    "div",
    "colon",
    "decimal_u",
    "rparen",
    "oct_uwb",
    "hex_ull",
    "semicolon",
    "pluseq",
    "whitespace",
    "oct_u",
    "oct_l",
    "shiftleft",
    "tilde",
    "rangle",
    "cantmove",
    "oct_lu",
    "shiftright",
    "plus",
    "hexadecimal",
    "xoreq",
    "decimal_wb",
    "arrow"
};

static const char* tokenTypeColors[TOKENCOUNT] = {
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;255;215;0m",
    "\033[38;2;255;215;0m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;255;215;0m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;156;220;254m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;106;153;85m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;128;128;128m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;255;215;0m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;106;153;85m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;255;215;0m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;244;71;71m",
    "\033[38;2;212;212;212m",
    "\033[38;2;106;153;85m",
    "\033[38;2;106;153;85m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;255;215;0m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;244;71;71m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m"
};

#define MAXCHAR 97

enum state {
    cantmove_state,
    charliteralstart_state,
    charliteral_state,
    charliteralchewedone_state,
    charliteralescape_state,
    charescapeoctal0_state,
    charescapeoctal1_state,
    charescapehexempty_state,
    charescapehex_state,
    nondecimal_state,
    fraction_state,
    octal_state,
    oct_u_state,
    oct_lu_state,
    oct_l_state,
    oct_L_state,
    oct_w_state,
    oct_W_state,
    oct_ull_state,
    oct_ul_state,
    oct_uL_state,
    oct_uwb_state,
    oct_uw_state,
    oct_uW_state,
    oct_ll_state,
    oct_wb_state,
    hexfraction_state,
    hexadecimal_state,
    hex_u_state,
    hex_lu_state,
    hex_l_state,
    hex_L_state,
    hex_w_state,
    hex_W_state,
    hex_ull_state,
    hex_ul_state,
    hex_uL_state,
    hex_uwb_state,
    hex_uw_state,
    hex_uW_state,
    hex_ll_state,
    hex_wb_state,
    decimalfraction_state,
    decimal_state,
    decimal_u_state,
    decimal_lu_state,
    decimal_l_state,
    decimal_L_state,
    decimal_w_state,
    decimal_W_state,
    decimal_ull_state,
    decimal_ul_state,
    decimal_uL_state,
    decimal_uwb_state,
    decimal_uw_state,
    decimal_uW_state,
    decimal_ll_state,
    decimal_wb_state,
    newline_state,
    lparen_state,
    rparen_state,
    lcurly_state,
    rcurly_state,
    rbracket_state,
    lbracket_state,
    question_state,
    semicolon_state,
    colon_state,
    comma_state,
    dot_state,
    eof_state,
    start_state,
    identifier_state,
    modeq_state,
    mod_state,
    minuseq_state,
    arrow_state,
    minus_state,
    xoreq_state,
    caret_state,
    bnoteq_state,
    tilde_state,
    boreq_state,
    lor_state,
    pipe_state,
    eq_state,
    assignment_state,
    pluseq_state,
    plus_state,
    shiftleft_state,
    le_state,
    langle_state,
    shiftright_state,
    ge_state,
    rangle_state,
    div_state,
    linecomment_state,
    blockcomment_state,
    blockcommentweak_state,
    blockcommentfinish_state,
    bandeq_state,
    and_state,
    amp_state,
    timeseq_state,
    star_state,
    noteq_state,
    exc_state,
    preproc_state,
    whitespace_state,
    stringliteral_state,
    stringliteralstart_state,
    stringliteralescape_state,
    stringescapeoctal0_state,
    stringescapeoctal1_state,
    stringescapehexempty_state,
    stringescapehex_state,
    STATECOUNT
};

static enum state stateMachine_transitions[STATECOUNT][MAXCHAR + 1] = {
    [charliteralstart_state][4] = charliteralescape_state,
    [charliteralstart_state][1] = charliteralchewedone_state,
    [charliteralstart_state][2] = charliteralchewedone_state,
    [charliteralstart_state][3] = charliteralchewedone_state,
    [charliteralstart_state][5] = charliteralchewedone_state,
    [charliteralstart_state][6] = charliteralchewedone_state,
    [charliteralstart_state][7] = charliteralchewedone_state,
    [charliteralstart_state][9] = charliteralchewedone_state,
    [charliteralstart_state][10] = charliteralchewedone_state,
    [charliteralstart_state][11] = charliteralchewedone_state,
    [charliteralstart_state][12] = charliteralchewedone_state,
    [charliteralstart_state][13] = charliteralchewedone_state,
    [charliteralstart_state][14] = charliteralchewedone_state,
    [charliteralstart_state][15] = charliteralchewedone_state,
    [charliteralstart_state][16] = charliteralchewedone_state,
    [charliteralstart_state][17] = charliteralchewedone_state,
    [charliteralstart_state][18] = charliteralchewedone_state,
    [charliteralstart_state][19] = charliteralchewedone_state,
    [charliteralstart_state][20] = charliteralchewedone_state,
    [charliteralstart_state][21] = charliteralchewedone_state,
    [charliteralstart_state][22] = charliteralchewedone_state,
    [charliteralstart_state][23] = charliteralchewedone_state,
    [charliteralstart_state][24] = charliteralchewedone_state,
    [charliteralstart_state][25] = charliteralchewedone_state,
    [charliteralstart_state][26] = charliteralchewedone_state,
    [charliteralstart_state][27] = charliteralchewedone_state,
    [charliteralstart_state][28] = charliteralchewedone_state,
    [charliteralstart_state][29] = charliteralchewedone_state,
    [charliteralstart_state][30] = charliteralchewedone_state,
    [charliteralstart_state][31] = charliteralchewedone_state,
    [charliteralstart_state][32] = charliteralchewedone_state,
    [charliteralstart_state][33] = charliteralchewedone_state,
    [charliteralstart_state][34] = charliteralchewedone_state,
    [charliteralstart_state][35] = charliteralchewedone_state,
    [charliteralstart_state][37] = charliteralchewedone_state,
    [charliteralstart_state][38] = charliteralchewedone_state,
    [charliteralstart_state][39] = charliteralchewedone_state,
    [charliteralstart_state][40] = charliteralchewedone_state,
    [charliteralstart_state][41] = charliteralchewedone_state,
    [charliteralstart_state][42] = charliteralchewedone_state,
    [charliteralstart_state][43] = charliteralchewedone_state,
    [charliteralstart_state][44] = charliteralchewedone_state,
    [charliteralstart_state][45] = charliteralchewedone_state,
    [charliteralstart_state][46] = charliteralchewedone_state,
    [charliteralstart_state][47] = charliteralchewedone_state,
    [charliteralstart_state][48] = charliteralchewedone_state,
    [charliteralstart_state][49] = charliteralchewedone_state,
    [charliteralstart_state][50] = charliteralchewedone_state,
    [charliteralstart_state][51] = charliteralchewedone_state,
    [charliteralstart_state][53] = charliteralchewedone_state,
    [charliteralstart_state][54] = charliteralchewedone_state,
    [charliteralstart_state][55] = charliteralchewedone_state,
    [charliteralstart_state][56] = charliteralchewedone_state,
    [charliteralstart_state][57] = charliteralchewedone_state,
    [charliteralstart_state][58] = charliteralchewedone_state,
    [charliteralstart_state][59] = charliteralchewedone_state,
    [charliteralstart_state][60] = charliteralchewedone_state,
    [charliteralstart_state][61] = charliteralchewedone_state,
    [charliteralstart_state][62] = charliteralchewedone_state,
    [charliteralstart_state][63] = charliteralchewedone_state,
    [charliteralstart_state][64] = charliteralchewedone_state,
    [charliteralstart_state][65] = charliteralchewedone_state,
    [charliteralstart_state][66] = charliteralchewedone_state,
    [charliteralstart_state][67] = charliteralchewedone_state,
    [charliteralstart_state][68] = charliteralchewedone_state,
    [charliteralstart_state][69] = charliteralchewedone_state,
    [charliteralstart_state][70] = charliteralchewedone_state,
    [charliteralstart_state][71] = charliteralchewedone_state,
    [charliteralstart_state][72] = charliteralchewedone_state,
    [charliteralstart_state][73] = charliteralchewedone_state,
    [charliteralstart_state][74] = charliteralchewedone_state,
    [charliteralstart_state][75] = charliteralchewedone_state,
    [charliteralstart_state][76] = charliteralchewedone_state,
    [charliteralstart_state][77] = charliteralchewedone_state,
    [charliteralstart_state][78] = charliteralchewedone_state,
    [charliteralstart_state][79] = charliteralchewedone_state,
    [charliteralstart_state][80] = charliteralchewedone_state,
    [charliteralstart_state][81] = charliteralchewedone_state,
    [charliteralstart_state][82] = charliteralchewedone_state,
    [charliteralstart_state][83] = charliteralchewedone_state,
    [charliteralstart_state][84] = charliteralchewedone_state,
    [charliteralstart_state][85] = charliteralchewedone_state,
    [charliteralstart_state][86] = charliteralchewedone_state,
    [charliteralstart_state][87] = charliteralchewedone_state,
    [charliteralstart_state][88] = charliteralchewedone_state,
    [charliteralstart_state][89] = charliteralchewedone_state,
    [charliteralstart_state][90] = charliteralchewedone_state,
    [charliteralstart_state][91] = charliteralchewedone_state,
    [charliteralstart_state][92] = charliteralchewedone_state,
    [charliteralstart_state][93] = charliteralchewedone_state,
    [charliteralstart_state][94] = charliteralchewedone_state,
    [charliteralstart_state][95] = charliteralchewedone_state,
    [charliteralstart_state][96] = charliteralchewedone_state,
    [charliteralstart_state][97] = charliteralchewedone_state,
    [charliteralchewedone_state][4] = charliteralescape_state,
    [charliteralchewedone_state][52] = charliteral_state,
    [charliteralchewedone_state][1] = charliteralchewedone_state,
    [charliteralchewedone_state][2] = charliteralchewedone_state,
    [charliteralchewedone_state][3] = charliteralchewedone_state,
    [charliteralchewedone_state][5] = charliteralchewedone_state,
    [charliteralchewedone_state][6] = charliteralchewedone_state,
    [charliteralchewedone_state][7] = charliteralchewedone_state,
    [charliteralchewedone_state][9] = charliteralchewedone_state,
    [charliteralchewedone_state][10] = charliteralchewedone_state,
    [charliteralchewedone_state][11] = charliteralchewedone_state,
    [charliteralchewedone_state][12] = charliteralchewedone_state,
    [charliteralchewedone_state][13] = charliteralchewedone_state,
    [charliteralchewedone_state][14] = charliteralchewedone_state,
    [charliteralchewedone_state][15] = charliteralchewedone_state,
    [charliteralchewedone_state][16] = charliteralchewedone_state,
    [charliteralchewedone_state][17] = charliteralchewedone_state,
    [charliteralchewedone_state][18] = charliteralchewedone_state,
    [charliteralchewedone_state][19] = charliteralchewedone_state,
    [charliteralchewedone_state][20] = charliteralchewedone_state,
    [charliteralchewedone_state][21] = charliteralchewedone_state,
    [charliteralchewedone_state][22] = charliteralchewedone_state,
    [charliteralchewedone_state][23] = charliteralchewedone_state,
    [charliteralchewedone_state][24] = charliteralchewedone_state,
    [charliteralchewedone_state][25] = charliteralchewedone_state,
    [charliteralchewedone_state][26] = charliteralchewedone_state,
    [charliteralchewedone_state][27] = charliteralchewedone_state,
    [charliteralchewedone_state][28] = charliteralchewedone_state,
    [charliteralchewedone_state][29] = charliteralchewedone_state,
    [charliteralchewedone_state][30] = charliteralchewedone_state,
    [charliteralchewedone_state][31] = charliteralchewedone_state,
    [charliteralchewedone_state][32] = charliteralchewedone_state,
    [charliteralchewedone_state][33] = charliteralchewedone_state,
    [charliteralchewedone_state][34] = charliteralchewedone_state,
    [charliteralchewedone_state][35] = charliteralchewedone_state,
    [charliteralchewedone_state][37] = charliteralchewedone_state,
    [charliteralchewedone_state][38] = charliteralchewedone_state,
    [charliteralchewedone_state][39] = charliteralchewedone_state,
    [charliteralchewedone_state][40] = charliteralchewedone_state,
    [charliteralchewedone_state][41] = charliteralchewedone_state,
    [charliteralchewedone_state][42] = charliteralchewedone_state,
    [charliteralchewedone_state][43] = charliteralchewedone_state,
    [charliteralchewedone_state][44] = charliteralchewedone_state,
    [charliteralchewedone_state][45] = charliteralchewedone_state,
    [charliteralchewedone_state][46] = charliteralchewedone_state,
    [charliteralchewedone_state][47] = charliteralchewedone_state,
    [charliteralchewedone_state][48] = charliteralchewedone_state,
    [charliteralchewedone_state][49] = charliteralchewedone_state,
    [charliteralchewedone_state][50] = charliteralchewedone_state,
    [charliteralchewedone_state][51] = charliteralchewedone_state,
    [charliteralchewedone_state][53] = charliteralchewedone_state,
    [charliteralchewedone_state][54] = charliteralchewedone_state,
    [charliteralchewedone_state][55] = charliteralchewedone_state,
    [charliteralchewedone_state][56] = charliteralchewedone_state,
    [charliteralchewedone_state][57] = charliteralchewedone_state,
    [charliteralchewedone_state][58] = charliteralchewedone_state,
    [charliteralchewedone_state][59] = charliteralchewedone_state,
    [charliteralchewedone_state][60] = charliteralchewedone_state,
    [charliteralchewedone_state][61] = charliteralchewedone_state,
    [charliteralchewedone_state][62] = charliteralchewedone_state,
    [charliteralchewedone_state][63] = charliteralchewedone_state,
    [charliteralchewedone_state][64] = charliteralchewedone_state,
    [charliteralchewedone_state][65] = charliteralchewedone_state,
    [charliteralchewedone_state][66] = charliteralchewedone_state,
    [charliteralchewedone_state][67] = charliteralchewedone_state,
    [charliteralchewedone_state][68] = charliteralchewedone_state,
    [charliteralchewedone_state][69] = charliteralchewedone_state,
    [charliteralchewedone_state][70] = charliteralchewedone_state,
    [charliteralchewedone_state][71] = charliteralchewedone_state,
    [charliteralchewedone_state][72] = charliteralchewedone_state,
    [charliteralchewedone_state][73] = charliteralchewedone_state,
    [charliteralchewedone_state][74] = charliteralchewedone_state,
    [charliteralchewedone_state][75] = charliteralchewedone_state,
    [charliteralchewedone_state][76] = charliteralchewedone_state,
    [charliteralchewedone_state][77] = charliteralchewedone_state,
    [charliteralchewedone_state][78] = charliteralchewedone_state,
    [charliteralchewedone_state][79] = charliteralchewedone_state,
    [charliteralchewedone_state][80] = charliteralchewedone_state,
    [charliteralchewedone_state][81] = charliteralchewedone_state,
    [charliteralchewedone_state][82] = charliteralchewedone_state,
    [charliteralchewedone_state][83] = charliteralchewedone_state,
    [charliteralchewedone_state][84] = charliteralchewedone_state,
    [charliteralchewedone_state][85] = charliteralchewedone_state,
    [charliteralchewedone_state][86] = charliteralchewedone_state,
    [charliteralchewedone_state][87] = charliteralchewedone_state,
    [charliteralchewedone_state][88] = charliteralchewedone_state,
    [charliteralchewedone_state][89] = charliteralchewedone_state,
    [charliteralchewedone_state][90] = charliteralchewedone_state,
    [charliteralchewedone_state][91] = charliteralchewedone_state,
    [charliteralchewedone_state][92] = charliteralchewedone_state,
    [charliteralchewedone_state][93] = charliteralchewedone_state,
    [charliteralchewedone_state][94] = charliteralchewedone_state,
    [charliteralchewedone_state][95] = charliteralchewedone_state,
    [charliteralchewedone_state][96] = charliteralchewedone_state,
    [charliteralchewedone_state][97] = charliteralchewedone_state,
    [charliteralescape_state][52] = charliteralchewedone_state,
    [charliteralescape_state][22] = charliteralchewedone_state,
    [charliteralescape_state][37] = charliteralchewedone_state,
    [charliteralescape_state][4] = charliteralchewedone_state,
    [charliteralescape_state][64] = charliteralchewedone_state,
    [charliteralescape_state][20] = charliteralchewedone_state,
    [charliteralescape_state][12] = charliteralchewedone_state,
    [charliteralescape_state][90] = charliteralchewedone_state,
    [charliteralescape_state][5] = charliteralchewedone_state,
    [charliteralescape_state][14] = charliteralchewedone_state,
    [charliteralescape_state][86] = charliteralchewedone_state,
    [charliteralescape_state][2] = charescapeoctal0_state,
    [charliteralescape_state][50] = charescapeoctal0_state,
    [charliteralescape_state][81] = charescapeoctal0_state,
    [charliteralescape_state][46] = charescapeoctal0_state,
    [charliteralescape_state][66] = charescapeoctal0_state,
    [charliteralescape_state][83] = charescapeoctal0_state,
    [charliteralescape_state][49] = charescapeoctal0_state,
    [charliteralescape_state][13] = charescapeoctal0_state,
    [charliteralescape_state][88] = charescapehexempty_state,
    [charescapeoctal0_state][2] = charescapeoctal1_state,
    [charescapeoctal0_state][50] = charescapeoctal1_state,
    [charescapeoctal0_state][81] = charescapeoctal1_state,
    [charescapeoctal0_state][46] = charescapeoctal1_state,
    [charescapeoctal0_state][66] = charescapeoctal1_state,
    [charescapeoctal0_state][83] = charescapeoctal1_state,
    [charescapeoctal0_state][49] = charescapeoctal1_state,
    [charescapeoctal0_state][13] = charescapeoctal1_state,
    [charescapeoctal0_state][52] = charliteral_state,
    [charescapeoctal1_state][2] = charliteralchewedone_state,
    [charescapeoctal1_state][50] = charliteralchewedone_state,
    [charescapeoctal1_state][81] = charliteralchewedone_state,
    [charescapeoctal1_state][46] = charliteralchewedone_state,
    [charescapeoctal1_state][66] = charliteralchewedone_state,
    [charescapeoctal1_state][83] = charliteralchewedone_state,
    [charescapeoctal1_state][49] = charliteralchewedone_state,
    [charescapeoctal1_state][13] = charliteralchewedone_state,
    [charescapeoctal1_state][52] = charliteral_state,
    [charescapehexempty_state][2] = charescapehex_state,
    [charescapehexempty_state][7] = charescapehex_state,
    [charescapehexempty_state][12] = charescapehex_state,
    [charescapehexempty_state][13] = charescapehex_state,
    [charescapehexempty_state][63] = charescapehex_state,
    [charescapehexempty_state][64] = charescapehex_state,
    [charescapehexempty_state][20] = charescapehex_state,
    [charescapehexempty_state][21] = charescapehex_state,
    [charescapehexempty_state][66] = charescapehex_state,
    [charescapehexempty_state][69] = charescapehex_state,
    [charescapehexempty_state][71] = charescapehex_state,
    [charescapehexempty_state][78] = charescapehex_state,
    [charescapehexempty_state][81] = charescapehex_state,
    [charescapehexempty_state][83] = charescapehex_state,
    [charescapehexempty_state][33] = charescapehex_state,
    [charescapehexempty_state][84] = charescapehex_state,
    [charescapehexempty_state][41] = charescapehex_state,
    [charescapehexempty_state][49] = charescapehex_state,
    [charescapehexempty_state][44] = charescapehex_state,
    [charescapehexempty_state][46] = charescapehex_state,
    [charescapehexempty_state][93] = charescapehex_state,
    [charescapehexempty_state][50] = charescapehex_state,
    [charescapehex_state][2] = charescapehex_state,
    [charescapehex_state][7] = charescapehex_state,
    [charescapehex_state][12] = charescapehex_state,
    [charescapehex_state][13] = charescapehex_state,
    [charescapehex_state][63] = charescapehex_state,
    [charescapehex_state][64] = charescapehex_state,
    [charescapehex_state][20] = charescapehex_state,
    [charescapehex_state][21] = charescapehex_state,
    [charescapehex_state][66] = charescapehex_state,
    [charescapehex_state][69] = charescapehex_state,
    [charescapehex_state][71] = charescapehex_state,
    [charescapehex_state][78] = charescapehex_state,
    [charescapehex_state][81] = charescapehex_state,
    [charescapehex_state][83] = charescapehex_state,
    [charescapehex_state][33] = charescapehex_state,
    [charescapehex_state][84] = charescapehex_state,
    [charescapehex_state][41] = charescapehex_state,
    [charescapehex_state][49] = charescapehex_state,
    [charescapehex_state][44] = charescapehex_state,
    [charescapehex_state][46] = charescapehex_state,
    [charescapehex_state][93] = charescapehex_state,
    [charescapehex_state][50] = charescapehex_state,
    [charescapehex_state][52] = charliteral_state,
    [nondecimal_state][88] = hexadecimal_state,
    [nondecimal_state][42] = hexadecimal_state,
    [nondecimal_state][2] = octal_state,
    [nondecimal_state][50] = octal_state,
    [nondecimal_state][81] = octal_state,
    [nondecimal_state][46] = octal_state,
    [nondecimal_state][66] = octal_state,
    [nondecimal_state][83] = octal_state,
    [nondecimal_state][49] = octal_state,
    [nondecimal_state][13] = octal_state,
    [octal_state][2] = octal_state,
    [octal_state][50] = octal_state,
    [octal_state][81] = octal_state,
    [octal_state][46] = octal_state,
    [octal_state][66] = octal_state,
    [octal_state][83] = octal_state,
    [octal_state][49] = octal_state,
    [octal_state][13] = octal_state,
    [octal_state][52] = octal_state,
    [octal_state][19] = fraction_state,
    [octal_state][65] = oct_u_state,
    [octal_state][28] = oct_u_state,
    [octal_state][30] = oct_l_state,
    [octal_state][58] = oct_L_state,
    [octal_state][25] = oct_w_state,
    [octal_state][74] = oct_W_state,
    [oct_u_state][30] = oct_ul_state,
    [oct_u_state][58] = oct_uL_state,
    [oct_u_state][25] = oct_uw_state,
    [oct_u_state][74] = oct_uW_state,
    [oct_l_state][30] = oct_ll_state,
    [oct_l_state][65] = oct_lu_state,
    [oct_l_state][28] = oct_lu_state,
    [oct_L_state][58] = oct_ll_state,
    [oct_L_state][65] = oct_lu_state,
    [oct_L_state][28] = oct_lu_state,
    [oct_w_state][20] = oct_wb_state,
    [oct_W_state][78] = oct_wb_state,
    [oct_ul_state][30] = oct_ull_state,
    [oct_uL_state][58] = oct_ull_state,
    [oct_uw_state][20] = oct_uwb_state,
    [oct_uW_state][78] = oct_uwb_state,
    [oct_ll_state][65] = oct_ull_state,
    [oct_ll_state][28] = oct_ull_state,
    [oct_wb_state][65] = oct_uwb_state,
    [oct_wb_state][28] = oct_uwb_state,
    [hexadecimal_state][2] = hexadecimal_state,
    [hexadecimal_state][7] = hexadecimal_state,
    [hexadecimal_state][12] = hexadecimal_state,
    [hexadecimal_state][13] = hexadecimal_state,
    [hexadecimal_state][63] = hexadecimal_state,
    [hexadecimal_state][64] = hexadecimal_state,
    [hexadecimal_state][20] = hexadecimal_state,
    [hexadecimal_state][21] = hexadecimal_state,
    [hexadecimal_state][66] = hexadecimal_state,
    [hexadecimal_state][69] = hexadecimal_state,
    [hexadecimal_state][71] = hexadecimal_state,
    [hexadecimal_state][78] = hexadecimal_state,
    [hexadecimal_state][81] = hexadecimal_state,
    [hexadecimal_state][83] = hexadecimal_state,
    [hexadecimal_state][33] = hexadecimal_state,
    [hexadecimal_state][84] = hexadecimal_state,
    [hexadecimal_state][41] = hexadecimal_state,
    [hexadecimal_state][49] = hexadecimal_state,
    [hexadecimal_state][44] = hexadecimal_state,
    [hexadecimal_state][46] = hexadecimal_state,
    [hexadecimal_state][93] = hexadecimal_state,
    [hexadecimal_state][50] = hexadecimal_state,
    [hexadecimal_state][52] = hexadecimal_state,
    [hexadecimal_state][19] = hexfraction_state,
    [hexadecimal_state][65] = hex_u_state,
    [hexadecimal_state][28] = hex_u_state,
    [hexadecimal_state][30] = hex_l_state,
    [hexadecimal_state][58] = hex_L_state,
    [hexadecimal_state][25] = hex_w_state,
    [hexadecimal_state][74] = hex_W_state,
    [hex_u_state][30] = hex_ul_state,
    [hex_u_state][58] = hex_uL_state,
    [hex_u_state][25] = hex_uw_state,
    [hex_u_state][74] = hex_uW_state,
    [hex_l_state][30] = hex_ll_state,
    [hex_l_state][65] = hex_lu_state,
    [hex_l_state][28] = hex_lu_state,
    [hex_L_state][58] = hex_ll_state,
    [hex_L_state][65] = hex_lu_state,
    [hex_L_state][28] = hex_lu_state,
    [hex_w_state][20] = hex_wb_state,
    [hex_W_state][78] = hex_wb_state,
    [hex_ul_state][30] = hex_ull_state,
    [hex_uL_state][58] = hex_ull_state,
    [hex_uw_state][20] = hex_uwb_state,
    [hex_uW_state][78] = hex_uwb_state,
    [hex_ll_state][65] = hex_ull_state,
    [hex_ll_state][28] = hex_ull_state,
    [hex_wb_state][65] = hex_uwb_state,
    [hex_wb_state][28] = hex_uwb_state,
    [decimal_state][2] = decimal_state,
    [decimal_state][50] = decimal_state,
    [decimal_state][63] = decimal_state,
    [decimal_state][81] = decimal_state,
    [decimal_state][46] = decimal_state,
    [decimal_state][66] = decimal_state,
    [decimal_state][83] = decimal_state,
    [decimal_state][84] = decimal_state,
    [decimal_state][49] = decimal_state,
    [decimal_state][13] = decimal_state,
    [decimal_state][52] = decimal_state,
    [decimal_state][19] = decimalfraction_state,
    [decimal_state][65] = decimal_u_state,
    [decimal_state][28] = decimal_u_state,
    [decimal_state][30] = decimal_l_state,
    [decimal_state][58] = decimal_L_state,
    [decimal_state][25] = decimal_w_state,
    [decimal_state][74] = decimal_W_state,
    [decimal_u_state][30] = decimal_ul_state,
    [decimal_u_state][58] = decimal_uL_state,
    [decimal_u_state][25] = decimal_uw_state,
    [decimal_u_state][74] = decimal_uW_state,
    [decimal_l_state][30] = decimal_ll_state,
    [decimal_l_state][65] = decimal_lu_state,
    [decimal_l_state][28] = decimal_lu_state,
    [decimal_L_state][58] = decimal_ll_state,
    [decimal_L_state][65] = decimal_lu_state,
    [decimal_L_state][28] = decimal_lu_state,
    [decimal_w_state][20] = decimal_wb_state,
    [decimal_W_state][78] = decimal_wb_state,
    [decimal_ul_state][30] = decimal_ull_state,
    [decimal_uL_state][58] = decimal_ull_state,
    [decimal_uw_state][20] = decimal_uwb_state,
    [decimal_uW_state][78] = decimal_uwb_state,
    [decimal_ll_state][65] = decimal_ull_state,
    [decimal_ll_state][28] = decimal_ull_state,
    [decimal_wb_state][65] = decimal_uwb_state,
    [decimal_wb_state][28] = decimal_uwb_state,
    [start_state][54] = identifier_state,
    [start_state][55] = identifier_state,
    [start_state][1] = identifier_state,
    [start_state][5] = identifier_state,
    [start_state][6] = identifier_state,
    [start_state][7] = identifier_state,
    [start_state][9] = identifier_state,
    [start_state][58] = identifier_state,
    [start_state][12] = identifier_state,
    [start_state][11] = identifier_state,
    [start_state][59] = identifier_state,
    [start_state][15] = identifier_state,
    [start_state][17] = identifier_state,
    [start_state][14] = identifier_state,
    [start_state][62] = identifier_state,
    [start_state][20] = identifier_state,
    [start_state][64] = identifier_state,
    [start_state][21] = identifier_state,
    [start_state][65] = identifier_state,
    [start_state][23] = identifier_state,
    [start_state][24] = identifier_state,
    [start_state][67] = identifier_state,
    [start_state][69] = identifier_state,
    [start_state][25] = identifier_state,
    [start_state][71] = identifier_state,
    [start_state][73] = identifier_state,
    [start_state][74] = identifier_state,
    [start_state][27] = identifier_state,
    [start_state][75] = identifier_state,
    [start_state][29] = identifier_state,
    [start_state][77] = identifier_state,
    [start_state][78] = identifier_state,
    [start_state][28] = identifier_state,
    [start_state][79] = identifier_state,
    [start_state][76] = identifier_state,
    [start_state][30] = identifier_state,
    [start_state][33] = identifier_state,
    [start_state][35] = identifier_state,
    [start_state][41] = identifier_state,
    [start_state][86] = identifier_state,
    [start_state][87] = identifier_state,
    [start_state][88] = identifier_state,
    [start_state][89] = identifier_state,
    [start_state][42] = identifier_state,
    [start_state][90] = identifier_state,
    [start_state][91] = identifier_state,
    [start_state][44] = identifier_state,
    [start_state][45] = identifier_state,
    [start_state][93] = identifier_state,
    [start_state][94] = identifier_state,
    [start_state][48] = identifier_state,
    [start_state][95] = identifier_state,
    [start_state][53] = identifier_state,
    [start_state][66] = nondecimal_state,
    [start_state][2] = decimal_state,
    [start_state][50] = decimal_state,
    [start_state][63] = decimal_state,
    [start_state][81] = decimal_state,
    [start_state][46] = decimal_state,
    [start_state][83] = decimal_state,
    [start_state][84] = decimal_state,
    [start_state][49] = decimal_state,
    [start_state][13] = decimal_state,
    [start_state][68] = whitespace_state,
    [start_state][70] = whitespace_state,
    [start_state][97] = whitespace_state,
    [start_state][8] = newline_state,
    [start_state][40] = mod_state,
    [start_state][16] = minus_state,
    [start_state][18] = plus_state,
    [start_state][57] = caret_state,
    [start_state][38] = tilde_state,
    [start_state][34] = lparen_state,
    [start_state][31] = rparen_state,
    [start_state][26] = lcurly_state,
    [start_state][3] = rcurly_state,
    [start_state][51] = rbracket_state,
    [start_state][32] = lbracket_state,
    [start_state][37] = question_state,
    [start_state][47] = semicolon_state,
    [start_state][72] = colon_state,
    [start_state][82] = assignment_state,
    [start_state][61] = langle_state,
    [start_state][39] = rangle_state,
    [start_state][92] = div_state,
    [start_state][96] = star_state,
    [start_state][85] = preproc_state,
    [start_state][60] = amp_state,
    [start_state][10] = comma_state,
    [start_state][19] = dot_state,
    [start_state][56] = exc_state,
    [start_state][22] = stringliteralstart_state,
    [start_state][80] = pipe_state,
    [start_state][52] = charliteralstart_state,
    [start_state][36] = eof_state,
    [identifier_state][54] = identifier_state,
    [identifier_state][55] = identifier_state,
    [identifier_state][1] = identifier_state,
    [identifier_state][5] = identifier_state,
    [identifier_state][6] = identifier_state,
    [identifier_state][7] = identifier_state,
    [identifier_state][9] = identifier_state,
    [identifier_state][58] = identifier_state,
    [identifier_state][12] = identifier_state,
    [identifier_state][11] = identifier_state,
    [identifier_state][59] = identifier_state,
    [identifier_state][15] = identifier_state,
    [identifier_state][17] = identifier_state,
    [identifier_state][14] = identifier_state,
    [identifier_state][62] = identifier_state,
    [identifier_state][20] = identifier_state,
    [identifier_state][64] = identifier_state,
    [identifier_state][21] = identifier_state,
    [identifier_state][65] = identifier_state,
    [identifier_state][23] = identifier_state,
    [identifier_state][24] = identifier_state,
    [identifier_state][67] = identifier_state,
    [identifier_state][69] = identifier_state,
    [identifier_state][25] = identifier_state,
    [identifier_state][71] = identifier_state,
    [identifier_state][73] = identifier_state,
    [identifier_state][74] = identifier_state,
    [identifier_state][27] = identifier_state,
    [identifier_state][75] = identifier_state,
    [identifier_state][29] = identifier_state,
    [identifier_state][77] = identifier_state,
    [identifier_state][78] = identifier_state,
    [identifier_state][28] = identifier_state,
    [identifier_state][79] = identifier_state,
    [identifier_state][76] = identifier_state,
    [identifier_state][30] = identifier_state,
    [identifier_state][33] = identifier_state,
    [identifier_state][35] = identifier_state,
    [identifier_state][41] = identifier_state,
    [identifier_state][86] = identifier_state,
    [identifier_state][87] = identifier_state,
    [identifier_state][88] = identifier_state,
    [identifier_state][89] = identifier_state,
    [identifier_state][42] = identifier_state,
    [identifier_state][90] = identifier_state,
    [identifier_state][91] = identifier_state,
    [identifier_state][44] = identifier_state,
    [identifier_state][45] = identifier_state,
    [identifier_state][93] = identifier_state,
    [identifier_state][94] = identifier_state,
    [identifier_state][48] = identifier_state,
    [identifier_state][95] = identifier_state,
    [identifier_state][53] = identifier_state,
    [identifier_state][2] = identifier_state,
    [identifier_state][50] = identifier_state,
    [identifier_state][63] = identifier_state,
    [identifier_state][81] = identifier_state,
    [identifier_state][46] = identifier_state,
    [identifier_state][66] = identifier_state,
    [identifier_state][83] = identifier_state,
    [identifier_state][84] = identifier_state,
    [identifier_state][49] = identifier_state,
    [identifier_state][13] = identifier_state,
    [mod_state][82] = modeq_state,
    [minus_state][82] = minuseq_state,
    [minus_state][39] = arrow_state,
    [caret_state][82] = xoreq_state,
    [tilde_state][82] = bnoteq_state,
    [pipe_state][82] = boreq_state,
    [pipe_state][80] = lor_state,
    [assignment_state][82] = eq_state,
    [plus_state][82] = pluseq_state,
    [langle_state][61] = shiftleft_state,
    [langle_state][82] = le_state,
    [rangle_state][39] = shiftright_state,
    [rangle_state][82] = ge_state,
    [div_state][92] = linecomment_state,
    [div_state][96] = blockcomment_state,
    [linecomment_state][1] = linecomment_state,
    [linecomment_state][2] = linecomment_state,
    [linecomment_state][3] = linecomment_state,
    [linecomment_state][4] = linecomment_state,
    [linecomment_state][5] = linecomment_state,
    [linecomment_state][6] = linecomment_state,
    [linecomment_state][7] = linecomment_state,
    [linecomment_state][9] = linecomment_state,
    [linecomment_state][10] = linecomment_state,
    [linecomment_state][11] = linecomment_state,
    [linecomment_state][12] = linecomment_state,
    [linecomment_state][13] = linecomment_state,
    [linecomment_state][14] = linecomment_state,
    [linecomment_state][15] = linecomment_state,
    [linecomment_state][16] = linecomment_state,
    [linecomment_state][17] = linecomment_state,
    [linecomment_state][18] = linecomment_state,
    [linecomment_state][19] = linecomment_state,
    [linecomment_state][20] = linecomment_state,
    [linecomment_state][21] = linecomment_state,
    [linecomment_state][22] = linecomment_state,
    [linecomment_state][23] = linecomment_state,
    [linecomment_state][24] = linecomment_state,
    [linecomment_state][25] = linecomment_state,
    [linecomment_state][26] = linecomment_state,
    [linecomment_state][27] = linecomment_state,
    [linecomment_state][28] = linecomment_state,
    [linecomment_state][29] = linecomment_state,
    [linecomment_state][30] = linecomment_state,
    [linecomment_state][31] = linecomment_state,
    [linecomment_state][32] = linecomment_state,
    [linecomment_state][33] = linecomment_state,
    [linecomment_state][34] = linecomment_state,
    [linecomment_state][35] = linecomment_state,
    [linecomment_state][37] = linecomment_state,
    [linecomment_state][38] = linecomment_state,
    [linecomment_state][39] = linecomment_state,
    [linecomment_state][40] = linecomment_state,
    [linecomment_state][41] = linecomment_state,
    [linecomment_state][42] = linecomment_state,
    [linecomment_state][43] = linecomment_state,
    [linecomment_state][44] = linecomment_state,
    [linecomment_state][45] = linecomment_state,
    [linecomment_state][46] = linecomment_state,
    [linecomment_state][47] = linecomment_state,
    [linecomment_state][48] = linecomment_state,
    [linecomment_state][49] = linecomment_state,
    [linecomment_state][50] = linecomment_state,
    [linecomment_state][51] = linecomment_state,
    [linecomment_state][52] = linecomment_state,
    [linecomment_state][53] = linecomment_state,
    [linecomment_state][54] = linecomment_state,
    [linecomment_state][55] = linecomment_state,
    [linecomment_state][56] = linecomment_state,
    [linecomment_state][57] = linecomment_state,
    [linecomment_state][58] = linecomment_state,
    [linecomment_state][59] = linecomment_state,
    [linecomment_state][60] = linecomment_state,
    [linecomment_state][61] = linecomment_state,
    [linecomment_state][62] = linecomment_state,
    [linecomment_state][63] = linecomment_state,
    [linecomment_state][64] = linecomment_state,
    [linecomment_state][65] = linecomment_state,
    [linecomment_state][66] = linecomment_state,
    [linecomment_state][67] = linecomment_state,
    [linecomment_state][68] = linecomment_state,
    [linecomment_state][69] = linecomment_state,
    [linecomment_state][70] = linecomment_state,
    [linecomment_state][71] = linecomment_state,
    [linecomment_state][72] = linecomment_state,
    [linecomment_state][73] = linecomment_state,
    [linecomment_state][74] = linecomment_state,
    [linecomment_state][75] = linecomment_state,
    [linecomment_state][76] = linecomment_state,
    [linecomment_state][77] = linecomment_state,
    [linecomment_state][78] = linecomment_state,
    [linecomment_state][79] = linecomment_state,
    [linecomment_state][80] = linecomment_state,
    [linecomment_state][81] = linecomment_state,
    [linecomment_state][82] = linecomment_state,
    [linecomment_state][83] = linecomment_state,
    [linecomment_state][84] = linecomment_state,
    [linecomment_state][85] = linecomment_state,
    [linecomment_state][86] = linecomment_state,
    [linecomment_state][87] = linecomment_state,
    [linecomment_state][88] = linecomment_state,
    [linecomment_state][89] = linecomment_state,
    [linecomment_state][90] = linecomment_state,
    [linecomment_state][91] = linecomment_state,
    [linecomment_state][92] = linecomment_state,
    [linecomment_state][93] = linecomment_state,
    [linecomment_state][94] = linecomment_state,
    [linecomment_state][95] = linecomment_state,
    [linecomment_state][96] = linecomment_state,
    [linecomment_state][97] = linecomment_state,
    [blockcomment_state][96] = blockcommentweak_state,
    [blockcomment_state][1] = blockcomment_state,
    [blockcomment_state][2] = blockcomment_state,
    [blockcomment_state][3] = blockcomment_state,
    [blockcomment_state][4] = blockcomment_state,
    [blockcomment_state][5] = blockcomment_state,
    [blockcomment_state][6] = blockcomment_state,
    [blockcomment_state][7] = blockcomment_state,
    [blockcomment_state][8] = blockcomment_state,
    [blockcomment_state][9] = blockcomment_state,
    [blockcomment_state][10] = blockcomment_state,
    [blockcomment_state][11] = blockcomment_state,
    [blockcomment_state][12] = blockcomment_state,
    [blockcomment_state][13] = blockcomment_state,
    [blockcomment_state][14] = blockcomment_state,
    [blockcomment_state][15] = blockcomment_state,
    [blockcomment_state][16] = blockcomment_state,
    [blockcomment_state][17] = blockcomment_state,
    [blockcomment_state][18] = blockcomment_state,
    [blockcomment_state][19] = blockcomment_state,
    [blockcomment_state][20] = blockcomment_state,
    [blockcomment_state][21] = blockcomment_state,
    [blockcomment_state][22] = blockcomment_state,
    [blockcomment_state][23] = blockcomment_state,
    [blockcomment_state][24] = blockcomment_state,
    [blockcomment_state][25] = blockcomment_state,
    [blockcomment_state][26] = blockcomment_state,
    [blockcomment_state][27] = blockcomment_state,
    [blockcomment_state][28] = blockcomment_state,
    [blockcomment_state][29] = blockcomment_state,
    [blockcomment_state][30] = blockcomment_state,
    [blockcomment_state][31] = blockcomment_state,
    [blockcomment_state][32] = blockcomment_state,
    [blockcomment_state][33] = blockcomment_state,
    [blockcomment_state][34] = blockcomment_state,
    [blockcomment_state][35] = blockcomment_state,
    [blockcomment_state][37] = blockcomment_state,
    [blockcomment_state][38] = blockcomment_state,
    [blockcomment_state][39] = blockcomment_state,
    [blockcomment_state][40] = blockcomment_state,
    [blockcomment_state][41] = blockcomment_state,
    [blockcomment_state][42] = blockcomment_state,
    [blockcomment_state][43] = blockcomment_state,
    [blockcomment_state][44] = blockcomment_state,
    [blockcomment_state][45] = blockcomment_state,
    [blockcomment_state][46] = blockcomment_state,
    [blockcomment_state][47] = blockcomment_state,
    [blockcomment_state][48] = blockcomment_state,
    [blockcomment_state][49] = blockcomment_state,
    [blockcomment_state][50] = blockcomment_state,
    [blockcomment_state][51] = blockcomment_state,
    [blockcomment_state][52] = blockcomment_state,
    [blockcomment_state][53] = blockcomment_state,
    [blockcomment_state][54] = blockcomment_state,
    [blockcomment_state][55] = blockcomment_state,
    [blockcomment_state][56] = blockcomment_state,
    [blockcomment_state][57] = blockcomment_state,
    [blockcomment_state][58] = blockcomment_state,
    [blockcomment_state][59] = blockcomment_state,
    [blockcomment_state][60] = blockcomment_state,
    [blockcomment_state][61] = blockcomment_state,
    [blockcomment_state][62] = blockcomment_state,
    [blockcomment_state][63] = blockcomment_state,
    [blockcomment_state][64] = blockcomment_state,
    [blockcomment_state][65] = blockcomment_state,
    [blockcomment_state][66] = blockcomment_state,
    [blockcomment_state][67] = blockcomment_state,
    [blockcomment_state][68] = blockcomment_state,
    [blockcomment_state][69] = blockcomment_state,
    [blockcomment_state][70] = blockcomment_state,
    [blockcomment_state][71] = blockcomment_state,
    [blockcomment_state][72] = blockcomment_state,
    [blockcomment_state][73] = blockcomment_state,
    [blockcomment_state][74] = blockcomment_state,
    [blockcomment_state][75] = blockcomment_state,
    [blockcomment_state][76] = blockcomment_state,
    [blockcomment_state][77] = blockcomment_state,
    [blockcomment_state][78] = blockcomment_state,
    [blockcomment_state][79] = blockcomment_state,
    [blockcomment_state][80] = blockcomment_state,
    [blockcomment_state][81] = blockcomment_state,
    [blockcomment_state][82] = blockcomment_state,
    [blockcomment_state][83] = blockcomment_state,
    [blockcomment_state][84] = blockcomment_state,
    [blockcomment_state][85] = blockcomment_state,
    [blockcomment_state][86] = blockcomment_state,
    [blockcomment_state][87] = blockcomment_state,
    [blockcomment_state][88] = blockcomment_state,
    [blockcomment_state][89] = blockcomment_state,
    [blockcomment_state][90] = blockcomment_state,
    [blockcomment_state][91] = blockcomment_state,
    [blockcomment_state][92] = blockcomment_state,
    [blockcomment_state][93] = blockcomment_state,
    [blockcomment_state][94] = blockcomment_state,
    [blockcomment_state][95] = blockcomment_state,
    [blockcomment_state][97] = blockcomment_state,
    [blockcommentweak_state][96] = blockcommentweak_state,
    [blockcommentweak_state][92] = blockcommentfinish_state,
    [blockcommentweak_state][1] = blockcomment_state,
    [blockcommentweak_state][2] = blockcomment_state,
    [blockcommentweak_state][3] = blockcomment_state,
    [blockcommentweak_state][4] = blockcomment_state,
    [blockcommentweak_state][5] = blockcomment_state,
    [blockcommentweak_state][6] = blockcomment_state,
    [blockcommentweak_state][7] = blockcomment_state,
    [blockcommentweak_state][8] = blockcomment_state,
    [blockcommentweak_state][9] = blockcomment_state,
    [blockcommentweak_state][10] = blockcomment_state,
    [blockcommentweak_state][11] = blockcomment_state,
    [blockcommentweak_state][12] = blockcomment_state,
    [blockcommentweak_state][13] = blockcomment_state,
    [blockcommentweak_state][14] = blockcomment_state,
    [blockcommentweak_state][15] = blockcomment_state,
    [blockcommentweak_state][16] = blockcomment_state,
    [blockcommentweak_state][17] = blockcomment_state,
    [blockcommentweak_state][18] = blockcomment_state,
    [blockcommentweak_state][19] = blockcomment_state,
    [blockcommentweak_state][20] = blockcomment_state,
    [blockcommentweak_state][21] = blockcomment_state,
    [blockcommentweak_state][22] = blockcomment_state,
    [blockcommentweak_state][23] = blockcomment_state,
    [blockcommentweak_state][24] = blockcomment_state,
    [blockcommentweak_state][25] = blockcomment_state,
    [blockcommentweak_state][26] = blockcomment_state,
    [blockcommentweak_state][27] = blockcomment_state,
    [blockcommentweak_state][28] = blockcomment_state,
    [blockcommentweak_state][29] = blockcomment_state,
    [blockcommentweak_state][30] = blockcomment_state,
    [blockcommentweak_state][31] = blockcomment_state,
    [blockcommentweak_state][32] = blockcomment_state,
    [blockcommentweak_state][33] = blockcomment_state,
    [blockcommentweak_state][34] = blockcomment_state,
    [blockcommentweak_state][35] = blockcomment_state,
    [blockcommentweak_state][37] = blockcomment_state,
    [blockcommentweak_state][38] = blockcomment_state,
    [blockcommentweak_state][39] = blockcomment_state,
    [blockcommentweak_state][40] = blockcomment_state,
    [blockcommentweak_state][41] = blockcomment_state,
    [blockcommentweak_state][42] = blockcomment_state,
    [blockcommentweak_state][43] = blockcomment_state,
    [blockcommentweak_state][44] = blockcomment_state,
    [blockcommentweak_state][45] = blockcomment_state,
    [blockcommentweak_state][46] = blockcomment_state,
    [blockcommentweak_state][47] = blockcomment_state,
    [blockcommentweak_state][48] = blockcomment_state,
    [blockcommentweak_state][49] = blockcomment_state,
    [blockcommentweak_state][50] = blockcomment_state,
    [blockcommentweak_state][51] = blockcomment_state,
    [blockcommentweak_state][52] = blockcomment_state,
    [blockcommentweak_state][53] = blockcomment_state,
    [blockcommentweak_state][54] = blockcomment_state,
    [blockcommentweak_state][55] = blockcomment_state,
    [blockcommentweak_state][56] = blockcomment_state,
    [blockcommentweak_state][57] = blockcomment_state,
    [blockcommentweak_state][58] = blockcomment_state,
    [blockcommentweak_state][59] = blockcomment_state,
    [blockcommentweak_state][60] = blockcomment_state,
    [blockcommentweak_state][61] = blockcomment_state,
    [blockcommentweak_state][62] = blockcomment_state,
    [blockcommentweak_state][63] = blockcomment_state,
    [blockcommentweak_state][64] = blockcomment_state,
    [blockcommentweak_state][65] = blockcomment_state,
    [blockcommentweak_state][66] = blockcomment_state,
    [blockcommentweak_state][67] = blockcomment_state,
    [blockcommentweak_state][68] = blockcomment_state,
    [blockcommentweak_state][69] = blockcomment_state,
    [blockcommentweak_state][70] = blockcomment_state,
    [blockcommentweak_state][71] = blockcomment_state,
    [blockcommentweak_state][72] = blockcomment_state,
    [blockcommentweak_state][73] = blockcomment_state,
    [blockcommentweak_state][74] = blockcomment_state,
    [blockcommentweak_state][75] = blockcomment_state,
    [blockcommentweak_state][76] = blockcomment_state,
    [blockcommentweak_state][77] = blockcomment_state,
    [blockcommentweak_state][78] = blockcomment_state,
    [blockcommentweak_state][79] = blockcomment_state,
    [blockcommentweak_state][80] = blockcomment_state,
    [blockcommentweak_state][81] = blockcomment_state,
    [blockcommentweak_state][82] = blockcomment_state,
    [blockcommentweak_state][83] = blockcomment_state,
    [blockcommentweak_state][84] = blockcomment_state,
    [blockcommentweak_state][85] = blockcomment_state,
    [blockcommentweak_state][86] = blockcomment_state,
    [blockcommentweak_state][87] = blockcomment_state,
    [blockcommentweak_state][88] = blockcomment_state,
    [blockcommentweak_state][89] = blockcomment_state,
    [blockcommentweak_state][90] = blockcomment_state,
    [blockcommentweak_state][91] = blockcomment_state,
    [blockcommentweak_state][93] = blockcomment_state,
    [blockcommentweak_state][94] = blockcomment_state,
    [blockcommentweak_state][95] = blockcomment_state,
    [blockcommentweak_state][97] = blockcomment_state,
    [amp_state][82] = bandeq_state,
    [amp_state][60] = and_state,
    [star_state][82] = timeseq_state,
    [exc_state][82] = noteq_state,
    [preproc_state][1] = preproc_state,
    [preproc_state][2] = preproc_state,
    [preproc_state][3] = preproc_state,
    [preproc_state][4] = preproc_state,
    [preproc_state][5] = preproc_state,
    [preproc_state][6] = preproc_state,
    [preproc_state][7] = preproc_state,
    [preproc_state][9] = preproc_state,
    [preproc_state][10] = preproc_state,
    [preproc_state][11] = preproc_state,
    [preproc_state][12] = preproc_state,
    [preproc_state][13] = preproc_state,
    [preproc_state][14] = preproc_state,
    [preproc_state][15] = preproc_state,
    [preproc_state][16] = preproc_state,
    [preproc_state][17] = preproc_state,
    [preproc_state][18] = preproc_state,
    [preproc_state][19] = preproc_state,
    [preproc_state][20] = preproc_state,
    [preproc_state][21] = preproc_state,
    [preproc_state][22] = preproc_state,
    [preproc_state][23] = preproc_state,
    [preproc_state][24] = preproc_state,
    [preproc_state][25] = preproc_state,
    [preproc_state][26] = preproc_state,
    [preproc_state][27] = preproc_state,
    [preproc_state][28] = preproc_state,
    [preproc_state][29] = preproc_state,
    [preproc_state][30] = preproc_state,
    [preproc_state][31] = preproc_state,
    [preproc_state][32] = preproc_state,
    [preproc_state][33] = preproc_state,
    [preproc_state][34] = preproc_state,
    [preproc_state][35] = preproc_state,
    [preproc_state][37] = preproc_state,
    [preproc_state][38] = preproc_state,
    [preproc_state][39] = preproc_state,
    [preproc_state][40] = preproc_state,
    [preproc_state][41] = preproc_state,
    [preproc_state][42] = preproc_state,
    [preproc_state][43] = preproc_state,
    [preproc_state][44] = preproc_state,
    [preproc_state][45] = preproc_state,
    [preproc_state][46] = preproc_state,
    [preproc_state][47] = preproc_state,
    [preproc_state][48] = preproc_state,
    [preproc_state][49] = preproc_state,
    [preproc_state][50] = preproc_state,
    [preproc_state][51] = preproc_state,
    [preproc_state][52] = preproc_state,
    [preproc_state][53] = preproc_state,
    [preproc_state][54] = preproc_state,
    [preproc_state][55] = preproc_state,
    [preproc_state][56] = preproc_state,
    [preproc_state][57] = preproc_state,
    [preproc_state][58] = preproc_state,
    [preproc_state][59] = preproc_state,
    [preproc_state][60] = preproc_state,
    [preproc_state][61] = preproc_state,
    [preproc_state][62] = preproc_state,
    [preproc_state][63] = preproc_state,
    [preproc_state][64] = preproc_state,
    [preproc_state][65] = preproc_state,
    [preproc_state][66] = preproc_state,
    [preproc_state][67] = preproc_state,
    [preproc_state][68] = preproc_state,
    [preproc_state][69] = preproc_state,
    [preproc_state][70] = preproc_state,
    [preproc_state][71] = preproc_state,
    [preproc_state][72] = preproc_state,
    [preproc_state][73] = preproc_state,
    [preproc_state][74] = preproc_state,
    [preproc_state][75] = preproc_state,
    [preproc_state][76] = preproc_state,
    [preproc_state][77] = preproc_state,
    [preproc_state][78] = preproc_state,
    [preproc_state][79] = preproc_state,
    [preproc_state][80] = preproc_state,
    [preproc_state][81] = preproc_state,
    [preproc_state][82] = preproc_state,
    [preproc_state][83] = preproc_state,
    [preproc_state][84] = preproc_state,
    [preproc_state][85] = preproc_state,
    [preproc_state][86] = preproc_state,
    [preproc_state][87] = preproc_state,
    [preproc_state][88] = preproc_state,
    [preproc_state][89] = preproc_state,
    [preproc_state][90] = preproc_state,
    [preproc_state][91] = preproc_state,
    [preproc_state][92] = preproc_state,
    [preproc_state][93] = preproc_state,
    [preproc_state][94] = preproc_state,
    [preproc_state][95] = preproc_state,
    [preproc_state][96] = preproc_state,
    [preproc_state][97] = preproc_state,
    [whitespace_state][68] = whitespace_state,
    [whitespace_state][70] = whitespace_state,
    [whitespace_state][97] = whitespace_state,
    [whitespace_state][8] = newline_state,
    [stringliteralstart_state][4] = stringliteralescape_state,
    [stringliteralstart_state][22] = stringliteral_state,
    [stringliteralstart_state][1] = stringliteralstart_state,
    [stringliteralstart_state][2] = stringliteralstart_state,
    [stringliteralstart_state][3] = stringliteralstart_state,
    [stringliteralstart_state][5] = stringliteralstart_state,
    [stringliteralstart_state][6] = stringliteralstart_state,
    [stringliteralstart_state][7] = stringliteralstart_state,
    [stringliteralstart_state][9] = stringliteralstart_state,
    [stringliteralstart_state][10] = stringliteralstart_state,
    [stringliteralstart_state][11] = stringliteralstart_state,
    [stringliteralstart_state][12] = stringliteralstart_state,
    [stringliteralstart_state][13] = stringliteralstart_state,
    [stringliteralstart_state][14] = stringliteralstart_state,
    [stringliteralstart_state][15] = stringliteralstart_state,
    [stringliteralstart_state][16] = stringliteralstart_state,
    [stringliteralstart_state][17] = stringliteralstart_state,
    [stringliteralstart_state][18] = stringliteralstart_state,
    [stringliteralstart_state][19] = stringliteralstart_state,
    [stringliteralstart_state][20] = stringliteralstart_state,
    [stringliteralstart_state][21] = stringliteralstart_state,
    [stringliteralstart_state][23] = stringliteralstart_state,
    [stringliteralstart_state][24] = stringliteralstart_state,
    [stringliteralstart_state][25] = stringliteralstart_state,
    [stringliteralstart_state][26] = stringliteralstart_state,
    [stringliteralstart_state][27] = stringliteralstart_state,
    [stringliteralstart_state][28] = stringliteralstart_state,
    [stringliteralstart_state][29] = stringliteralstart_state,
    [stringliteralstart_state][30] = stringliteralstart_state,
    [stringliteralstart_state][31] = stringliteralstart_state,
    [stringliteralstart_state][32] = stringliteralstart_state,
    [stringliteralstart_state][33] = stringliteralstart_state,
    [stringliteralstart_state][34] = stringliteralstart_state,
    [stringliteralstart_state][35] = stringliteralstart_state,
    [stringliteralstart_state][37] = stringliteralstart_state,
    [stringliteralstart_state][38] = stringliteralstart_state,
    [stringliteralstart_state][39] = stringliteralstart_state,
    [stringliteralstart_state][40] = stringliteralstart_state,
    [stringliteralstart_state][41] = stringliteralstart_state,
    [stringliteralstart_state][42] = stringliteralstart_state,
    [stringliteralstart_state][43] = stringliteralstart_state,
    [stringliteralstart_state][44] = stringliteralstart_state,
    [stringliteralstart_state][45] = stringliteralstart_state,
    [stringliteralstart_state][46] = stringliteralstart_state,
    [stringliteralstart_state][47] = stringliteralstart_state,
    [stringliteralstart_state][48] = stringliteralstart_state,
    [stringliteralstart_state][49] = stringliteralstart_state,
    [stringliteralstart_state][50] = stringliteralstart_state,
    [stringliteralstart_state][51] = stringliteralstart_state,
    [stringliteralstart_state][52] = stringliteralstart_state,
    [stringliteralstart_state][53] = stringliteralstart_state,
    [stringliteralstart_state][54] = stringliteralstart_state,
    [stringliteralstart_state][55] = stringliteralstart_state,
    [stringliteralstart_state][56] = stringliteralstart_state,
    [stringliteralstart_state][57] = stringliteralstart_state,
    [stringliteralstart_state][58] = stringliteralstart_state,
    [stringliteralstart_state][59] = stringliteralstart_state,
    [stringliteralstart_state][60] = stringliteralstart_state,
    [stringliteralstart_state][61] = stringliteralstart_state,
    [stringliteralstart_state][62] = stringliteralstart_state,
    [stringliteralstart_state][63] = stringliteralstart_state,
    [stringliteralstart_state][64] = stringliteralstart_state,
    [stringliteralstart_state][65] = stringliteralstart_state,
    [stringliteralstart_state][66] = stringliteralstart_state,
    [stringliteralstart_state][67] = stringliteralstart_state,
    [stringliteralstart_state][68] = stringliteralstart_state,
    [stringliteralstart_state][69] = stringliteralstart_state,
    [stringliteralstart_state][70] = stringliteralstart_state,
    [stringliteralstart_state][71] = stringliteralstart_state,
    [stringliteralstart_state][72] = stringliteralstart_state,
    [stringliteralstart_state][73] = stringliteralstart_state,
    [stringliteralstart_state][74] = stringliteralstart_state,
    [stringliteralstart_state][75] = stringliteralstart_state,
    [stringliteralstart_state][76] = stringliteralstart_state,
    [stringliteralstart_state][77] = stringliteralstart_state,
    [stringliteralstart_state][78] = stringliteralstart_state,
    [stringliteralstart_state][79] = stringliteralstart_state,
    [stringliteralstart_state][80] = stringliteralstart_state,
    [stringliteralstart_state][81] = stringliteralstart_state,
    [stringliteralstart_state][82] = stringliteralstart_state,
    [stringliteralstart_state][83] = stringliteralstart_state,
    [stringliteralstart_state][84] = stringliteralstart_state,
    [stringliteralstart_state][85] = stringliteralstart_state,
    [stringliteralstart_state][86] = stringliteralstart_state,
    [stringliteralstart_state][87] = stringliteralstart_state,
    [stringliteralstart_state][88] = stringliteralstart_state,
    [stringliteralstart_state][89] = stringliteralstart_state,
    [stringliteralstart_state][90] = stringliteralstart_state,
    [stringliteralstart_state][91] = stringliteralstart_state,
    [stringliteralstart_state][92] = stringliteralstart_state,
    [stringliteralstart_state][93] = stringliteralstart_state,
    [stringliteralstart_state][94] = stringliteralstart_state,
    [stringliteralstart_state][95] = stringliteralstart_state,
    [stringliteralstart_state][96] = stringliteralstart_state,
    [stringliteralstart_state][97] = stringliteralstart_state,
    [stringliteralescape_state][52] = stringliteralstart_state,
    [stringliteralescape_state][22] = stringliteralstart_state,
    [stringliteralescape_state][37] = stringliteralstart_state,
    [stringliteralescape_state][4] = stringliteralstart_state,
    [stringliteralescape_state][64] = stringliteralstart_state,
    [stringliteralescape_state][20] = stringliteralstart_state,
    [stringliteralescape_state][12] = stringliteralstart_state,
    [stringliteralescape_state][90] = stringliteralstart_state,
    [stringliteralescape_state][5] = stringliteralstart_state,
    [stringliteralescape_state][14] = stringliteralstart_state,
    [stringliteralescape_state][86] = stringliteralstart_state,
    [stringliteralescape_state][2] = stringescapeoctal0_state,
    [stringliteralescape_state][50] = stringescapeoctal0_state,
    [stringliteralescape_state][81] = stringescapeoctal0_state,
    [stringliteralescape_state][46] = stringescapeoctal0_state,
    [stringliteralescape_state][66] = stringescapeoctal0_state,
    [stringliteralescape_state][83] = stringescapeoctal0_state,
    [stringliteralescape_state][49] = stringescapeoctal0_state,
    [stringliteralescape_state][13] = stringescapeoctal0_state,
    [stringliteralescape_state][88] = stringescapehexempty_state,
    [stringescapeoctal0_state][2] = stringescapeoctal1_state,
    [stringescapeoctal0_state][50] = stringescapeoctal1_state,
    [stringescapeoctal0_state][81] = stringescapeoctal1_state,
    [stringescapeoctal0_state][46] = stringescapeoctal1_state,
    [stringescapeoctal0_state][66] = stringescapeoctal1_state,
    [stringescapeoctal0_state][83] = stringescapeoctal1_state,
    [stringescapeoctal0_state][49] = stringescapeoctal1_state,
    [stringescapeoctal0_state][13] = stringescapeoctal1_state,
    [stringescapeoctal0_state][22] = stringliteral_state,
    [stringescapeoctal0_state][1] = stringliteralstart_state,
    [stringescapeoctal0_state][3] = stringliteralstart_state,
    [stringescapeoctal0_state][4] = stringliteralstart_state,
    [stringescapeoctal0_state][5] = stringliteralstart_state,
    [stringescapeoctal0_state][6] = stringliteralstart_state,
    [stringescapeoctal0_state][7] = stringliteralstart_state,
    [stringescapeoctal0_state][9] = stringliteralstart_state,
    [stringescapeoctal0_state][10] = stringliteralstart_state,
    [stringescapeoctal0_state][11] = stringliteralstart_state,
    [stringescapeoctal0_state][12] = stringliteralstart_state,
    [stringescapeoctal0_state][14] = stringliteralstart_state,
    [stringescapeoctal0_state][15] = stringliteralstart_state,
    [stringescapeoctal0_state][16] = stringliteralstart_state,
    [stringescapeoctal0_state][17] = stringliteralstart_state,
    [stringescapeoctal0_state][18] = stringliteralstart_state,
    [stringescapeoctal0_state][19] = stringliteralstart_state,
    [stringescapeoctal0_state][20] = stringliteralstart_state,
    [stringescapeoctal0_state][21] = stringliteralstart_state,
    [stringescapeoctal0_state][23] = stringliteralstart_state,
    [stringescapeoctal0_state][24] = stringliteralstart_state,
    [stringescapeoctal0_state][25] = stringliteralstart_state,
    [stringescapeoctal0_state][26] = stringliteralstart_state,
    [stringescapeoctal0_state][27] = stringliteralstart_state,
    [stringescapeoctal0_state][28] = stringliteralstart_state,
    [stringescapeoctal0_state][29] = stringliteralstart_state,
    [stringescapeoctal0_state][30] = stringliteralstart_state,
    [stringescapeoctal0_state][31] = stringliteralstart_state,
    [stringescapeoctal0_state][32] = stringliteralstart_state,
    [stringescapeoctal0_state][33] = stringliteralstart_state,
    [stringescapeoctal0_state][34] = stringliteralstart_state,
    [stringescapeoctal0_state][35] = stringliteralstart_state,
    [stringescapeoctal0_state][37] = stringliteralstart_state,
    [stringescapeoctal0_state][38] = stringliteralstart_state,
    [stringescapeoctal0_state][39] = stringliteralstart_state,
    [stringescapeoctal0_state][40] = stringliteralstart_state,
    [stringescapeoctal0_state][41] = stringliteralstart_state,
    [stringescapeoctal0_state][42] = stringliteralstart_state,
    [stringescapeoctal0_state][43] = stringliteralstart_state,
    [stringescapeoctal0_state][44] = stringliteralstart_state,
    [stringescapeoctal0_state][45] = stringliteralstart_state,
    [stringescapeoctal0_state][47] = stringliteralstart_state,
    [stringescapeoctal0_state][48] = stringliteralstart_state,
    [stringescapeoctal0_state][51] = stringliteralstart_state,
    [stringescapeoctal0_state][52] = stringliteralstart_state,
    [stringescapeoctal0_state][53] = stringliteralstart_state,
    [stringescapeoctal0_state][54] = stringliteralstart_state,
    [stringescapeoctal0_state][55] = stringliteralstart_state,
    [stringescapeoctal0_state][56] = stringliteralstart_state,
    [stringescapeoctal0_state][57] = stringliteralstart_state,
    [stringescapeoctal0_state][58] = stringliteralstart_state,
    [stringescapeoctal0_state][59] = stringliteralstart_state,
    [stringescapeoctal0_state][60] = stringliteralstart_state,
    [stringescapeoctal0_state][61] = stringliteralstart_state,
    [stringescapeoctal0_state][62] = stringliteralstart_state,
    [stringescapeoctal0_state][63] = stringliteralstart_state,
    [stringescapeoctal0_state][64] = stringliteralstart_state,
    [stringescapeoctal0_state][65] = stringliteralstart_state,
    [stringescapeoctal0_state][67] = stringliteralstart_state,
    [stringescapeoctal0_state][68] = stringliteralstart_state,
    [stringescapeoctal0_state][69] = stringliteralstart_state,
    [stringescapeoctal0_state][70] = stringliteralstart_state,
    [stringescapeoctal0_state][71] = stringliteralstart_state,
    [stringescapeoctal0_state][72] = stringliteralstart_state,
    [stringescapeoctal0_state][73] = stringliteralstart_state,
    [stringescapeoctal0_state][74] = stringliteralstart_state,
    [stringescapeoctal0_state][75] = stringliteralstart_state,
    [stringescapeoctal0_state][76] = stringliteralstart_state,
    [stringescapeoctal0_state][77] = stringliteralstart_state,
    [stringescapeoctal0_state][78] = stringliteralstart_state,
    [stringescapeoctal0_state][79] = stringliteralstart_state,
    [stringescapeoctal0_state][80] = stringliteralstart_state,
    [stringescapeoctal0_state][82] = stringliteralstart_state,
    [stringescapeoctal0_state][84] = stringliteralstart_state,
    [stringescapeoctal0_state][85] = stringliteralstart_state,
    [stringescapeoctal0_state][86] = stringliteralstart_state,
    [stringescapeoctal0_state][87] = stringliteralstart_state,
    [stringescapeoctal0_state][88] = stringliteralstart_state,
    [stringescapeoctal0_state][89] = stringliteralstart_state,
    [stringescapeoctal0_state][90] = stringliteralstart_state,
    [stringescapeoctal0_state][91] = stringliteralstart_state,
    [stringescapeoctal0_state][92] = stringliteralstart_state,
    [stringescapeoctal0_state][93] = stringliteralstart_state,
    [stringescapeoctal0_state][94] = stringliteralstart_state,
    [stringescapeoctal0_state][95] = stringliteralstart_state,
    [stringescapeoctal0_state][96] = stringliteralstart_state,
    [stringescapeoctal0_state][97] = stringliteralstart_state,
    [stringescapeoctal1_state][2] = stringliteralstart_state,
    [stringescapeoctal1_state][50] = stringliteralstart_state,
    [stringescapeoctal1_state][81] = stringliteralstart_state,
    [stringescapeoctal1_state][46] = stringliteralstart_state,
    [stringescapeoctal1_state][66] = stringliteralstart_state,
    [stringescapeoctal1_state][83] = stringliteralstart_state,
    [stringescapeoctal1_state][49] = stringliteralstart_state,
    [stringescapeoctal1_state][13] = stringliteralstart_state,
    [stringescapeoctal1_state][22] = stringliteral_state,
    [stringescapeoctal1_state][1] = stringliteralstart_state,
    [stringescapeoctal1_state][3] = stringliteralstart_state,
    [stringescapeoctal1_state][4] = stringliteralstart_state,
    [stringescapeoctal1_state][5] = stringliteralstart_state,
    [stringescapeoctal1_state][6] = stringliteralstart_state,
    [stringescapeoctal1_state][7] = stringliteralstart_state,
    [stringescapeoctal1_state][9] = stringliteralstart_state,
    [stringescapeoctal1_state][10] = stringliteralstart_state,
    [stringescapeoctal1_state][11] = stringliteralstart_state,
    [stringescapeoctal1_state][12] = stringliteralstart_state,
    [stringescapeoctal1_state][14] = stringliteralstart_state,
    [stringescapeoctal1_state][15] = stringliteralstart_state,
    [stringescapeoctal1_state][16] = stringliteralstart_state,
    [stringescapeoctal1_state][17] = stringliteralstart_state,
    [stringescapeoctal1_state][18] = stringliteralstart_state,
    [stringescapeoctal1_state][19] = stringliteralstart_state,
    [stringescapeoctal1_state][20] = stringliteralstart_state,
    [stringescapeoctal1_state][21] = stringliteralstart_state,
    [stringescapeoctal1_state][23] = stringliteralstart_state,
    [stringescapeoctal1_state][24] = stringliteralstart_state,
    [stringescapeoctal1_state][25] = stringliteralstart_state,
    [stringescapeoctal1_state][26] = stringliteralstart_state,
    [stringescapeoctal1_state][27] = stringliteralstart_state,
    [stringescapeoctal1_state][28] = stringliteralstart_state,
    [stringescapeoctal1_state][29] = stringliteralstart_state,
    [stringescapeoctal1_state][30] = stringliteralstart_state,
    [stringescapeoctal1_state][31] = stringliteralstart_state,
    [stringescapeoctal1_state][32] = stringliteralstart_state,
    [stringescapeoctal1_state][33] = stringliteralstart_state,
    [stringescapeoctal1_state][34] = stringliteralstart_state,
    [stringescapeoctal1_state][35] = stringliteralstart_state,
    [stringescapeoctal1_state][37] = stringliteralstart_state,
    [stringescapeoctal1_state][38] = stringliteralstart_state,
    [stringescapeoctal1_state][39] = stringliteralstart_state,
    [stringescapeoctal1_state][40] = stringliteralstart_state,
    [stringescapeoctal1_state][41] = stringliteralstart_state,
    [stringescapeoctal1_state][42] = stringliteralstart_state,
    [stringescapeoctal1_state][43] = stringliteralstart_state,
    [stringescapeoctal1_state][44] = stringliteralstart_state,
    [stringescapeoctal1_state][45] = stringliteralstart_state,
    [stringescapeoctal1_state][47] = stringliteralstart_state,
    [stringescapeoctal1_state][48] = stringliteralstart_state,
    [stringescapeoctal1_state][51] = stringliteralstart_state,
    [stringescapeoctal1_state][52] = stringliteralstart_state,
    [stringescapeoctal1_state][53] = stringliteralstart_state,
    [stringescapeoctal1_state][54] = stringliteralstart_state,
    [stringescapeoctal1_state][55] = stringliteralstart_state,
    [stringescapeoctal1_state][56] = stringliteralstart_state,
    [stringescapeoctal1_state][57] = stringliteralstart_state,
    [stringescapeoctal1_state][58] = stringliteralstart_state,
    [stringescapeoctal1_state][59] = stringliteralstart_state,
    [stringescapeoctal1_state][60] = stringliteralstart_state,
    [stringescapeoctal1_state][61] = stringliteralstart_state,
    [stringescapeoctal1_state][62] = stringliteralstart_state,
    [stringescapeoctal1_state][63] = stringliteralstart_state,
    [stringescapeoctal1_state][64] = stringliteralstart_state,
    [stringescapeoctal1_state][65] = stringliteralstart_state,
    [stringescapeoctal1_state][67] = stringliteralstart_state,
    [stringescapeoctal1_state][68] = stringliteralstart_state,
    [stringescapeoctal1_state][69] = stringliteralstart_state,
    [stringescapeoctal1_state][70] = stringliteralstart_state,
    [stringescapeoctal1_state][71] = stringliteralstart_state,
    [stringescapeoctal1_state][72] = stringliteralstart_state,
    [stringescapeoctal1_state][73] = stringliteralstart_state,
    [stringescapeoctal1_state][74] = stringliteralstart_state,
    [stringescapeoctal1_state][75] = stringliteralstart_state,
    [stringescapeoctal1_state][76] = stringliteralstart_state,
    [stringescapeoctal1_state][77] = stringliteralstart_state,
    [stringescapeoctal1_state][78] = stringliteralstart_state,
    [stringescapeoctal1_state][79] = stringliteralstart_state,
    [stringescapeoctal1_state][80] = stringliteralstart_state,
    [stringescapeoctal1_state][82] = stringliteralstart_state,
    [stringescapeoctal1_state][84] = stringliteralstart_state,
    [stringescapeoctal1_state][85] = stringliteralstart_state,
    [stringescapeoctal1_state][86] = stringliteralstart_state,
    [stringescapeoctal1_state][87] = stringliteralstart_state,
    [stringescapeoctal1_state][88] = stringliteralstart_state,
    [stringescapeoctal1_state][89] = stringliteralstart_state,
    [stringescapeoctal1_state][90] = stringliteralstart_state,
    [stringescapeoctal1_state][91] = stringliteralstart_state,
    [stringescapeoctal1_state][92] = stringliteralstart_state,
    [stringescapeoctal1_state][93] = stringliteralstart_state,
    [stringescapeoctal1_state][94] = stringliteralstart_state,
    [stringescapeoctal1_state][95] = stringliteralstart_state,
    [stringescapeoctal1_state][96] = stringliteralstart_state,
    [stringescapeoctal1_state][97] = stringliteralstart_state,
    [stringescapehexempty_state][2] = stringescapehex_state,
    [stringescapehexempty_state][7] = stringescapehex_state,
    [stringescapehexempty_state][12] = stringescapehex_state,
    [stringescapehexempty_state][13] = stringescapehex_state,
    [stringescapehexempty_state][63] = stringescapehex_state,
    [stringescapehexempty_state][64] = stringescapehex_state,
    [stringescapehexempty_state][20] = stringescapehex_state,
    [stringescapehexempty_state][21] = stringescapehex_state,
    [stringescapehexempty_state][66] = stringescapehex_state,
    [stringescapehexempty_state][69] = stringescapehex_state,
    [stringescapehexempty_state][71] = stringescapehex_state,
    [stringescapehexempty_state][78] = stringescapehex_state,
    [stringescapehexempty_state][81] = stringescapehex_state,
    [stringescapehexempty_state][83] = stringescapehex_state,
    [stringescapehexempty_state][33] = stringescapehex_state,
    [stringescapehexempty_state][84] = stringescapehex_state,
    [stringescapehexempty_state][41] = stringescapehex_state,
    [stringescapehexempty_state][49] = stringescapehex_state,
    [stringescapehexempty_state][44] = stringescapehex_state,
    [stringescapehexempty_state][46] = stringescapehex_state,
    [stringescapehexempty_state][93] = stringescapehex_state,
    [stringescapehexempty_state][50] = stringescapehex_state,
    [stringescapehex_state][1] = stringliteralstart_state,
    [stringescapehex_state][2] = stringliteralstart_state,
    [stringescapehex_state][3] = stringliteralstart_state,
    [stringescapehex_state][4] = stringliteralstart_state,
    [stringescapehex_state][5] = stringliteralstart_state,
    [stringescapehex_state][6] = stringliteralstart_state,
    [stringescapehex_state][7] = stringliteralstart_state,
    [stringescapehex_state][9] = stringliteralstart_state,
    [stringescapehex_state][10] = stringliteralstart_state,
    [stringescapehex_state][11] = stringliteralstart_state,
    [stringescapehex_state][12] = stringliteralstart_state,
    [stringescapehex_state][13] = stringliteralstart_state,
    [stringescapehex_state][14] = stringliteralstart_state,
    [stringescapehex_state][15] = stringliteralstart_state,
    [stringescapehex_state][16] = stringliteralstart_state,
    [stringescapehex_state][17] = stringliteralstart_state,
    [stringescapehex_state][18] = stringliteralstart_state,
    [stringescapehex_state][19] = stringliteralstart_state,
    [stringescapehex_state][20] = stringliteralstart_state,
    [stringescapehex_state][21] = stringliteralstart_state,
    [stringescapehex_state][22] = stringliteralstart_state,
    [stringescapehex_state][23] = stringliteralstart_state,
    [stringescapehex_state][24] = stringliteralstart_state,
    [stringescapehex_state][25] = stringliteralstart_state,
    [stringescapehex_state][26] = stringliteralstart_state,
    [stringescapehex_state][27] = stringliteralstart_state,
    [stringescapehex_state][28] = stringliteralstart_state,
    [stringescapehex_state][29] = stringliteralstart_state,
    [stringescapehex_state][30] = stringliteralstart_state,
    [stringescapehex_state][31] = stringliteralstart_state,
    [stringescapehex_state][32] = stringliteralstart_state,
    [stringescapehex_state][33] = stringliteralstart_state,
    [stringescapehex_state][34] = stringliteralstart_state,
    [stringescapehex_state][35] = stringliteralstart_state,
    [stringescapehex_state][37] = stringliteralstart_state,
    [stringescapehex_state][38] = stringliteralstart_state,
    [stringescapehex_state][39] = stringliteralstart_state,
    [stringescapehex_state][40] = stringliteralstart_state,
    [stringescapehex_state][41] = stringliteralstart_state,
    [stringescapehex_state][42] = stringliteralstart_state,
    [stringescapehex_state][43] = stringliteralstart_state,
    [stringescapehex_state][44] = stringliteralstart_state,
    [stringescapehex_state][45] = stringliteralstart_state,
    [stringescapehex_state][46] = stringliteralstart_state,
    [stringescapehex_state][47] = stringliteralstart_state,
    [stringescapehex_state][48] = stringliteralstart_state,
    [stringescapehex_state][49] = stringliteralstart_state,
    [stringescapehex_state][50] = stringliteralstart_state,
    [stringescapehex_state][51] = stringliteralstart_state,
    [stringescapehex_state][52] = stringliteralstart_state,
    [stringescapehex_state][53] = stringliteralstart_state,
    [stringescapehex_state][54] = stringliteralstart_state,
    [stringescapehex_state][55] = stringliteralstart_state,
    [stringescapehex_state][56] = stringliteralstart_state,
    [stringescapehex_state][57] = stringliteralstart_state,
    [stringescapehex_state][58] = stringliteralstart_state,
    [stringescapehex_state][59] = stringliteralstart_state,
    [stringescapehex_state][60] = stringliteralstart_state,
    [stringescapehex_state][61] = stringliteralstart_state,
    [stringescapehex_state][62] = stringliteralstart_state,
    [stringescapehex_state][63] = stringliteralstart_state,
    [stringescapehex_state][64] = stringliteralstart_state,
    [stringescapehex_state][65] = stringliteralstart_state,
    [stringescapehex_state][66] = stringliteralstart_state,
    [stringescapehex_state][67] = stringliteralstart_state,
    [stringescapehex_state][68] = stringliteralstart_state,
    [stringescapehex_state][69] = stringliteralstart_state,
    [stringescapehex_state][70] = stringliteralstart_state,
    [stringescapehex_state][71] = stringliteralstart_state,
    [stringescapehex_state][72] = stringliteralstart_state,
    [stringescapehex_state][73] = stringliteralstart_state,
    [stringescapehex_state][74] = stringliteralstart_state,
    [stringescapehex_state][75] = stringliteralstart_state,
    [stringescapehex_state][76] = stringliteralstart_state,
    [stringescapehex_state][77] = stringliteralstart_state,
    [stringescapehex_state][78] = stringliteralstart_state,
    [stringescapehex_state][79] = stringliteralstart_state,
    [stringescapehex_state][80] = stringliteralstart_state,
    [stringescapehex_state][81] = stringliteralstart_state,
    [stringescapehex_state][82] = stringliteralstart_state,
    [stringescapehex_state][83] = stringliteralstart_state,
    [stringescapehex_state][84] = stringliteralstart_state,
    [stringescapehex_state][85] = stringliteralstart_state,
    [stringescapehex_state][86] = stringliteralstart_state,
    [stringescapehex_state][87] = stringliteralstart_state,
    [stringescapehex_state][88] = stringliteralstart_state,
    [stringescapehex_state][89] = stringliteralstart_state,
    [stringescapehex_state][90] = stringliteralstart_state,
    [stringescapehex_state][91] = stringliteralstart_state,
    [stringescapehex_state][92] = stringliteralstart_state,
    [stringescapehex_state][93] = stringliteralstart_state,
    [stringescapehex_state][94] = stringliteralstart_state,
    [stringescapehex_state][95] = stringliteralstart_state,
    [stringescapehex_state][96] = stringliteralstart_state,
    [stringescapehex_state][97] = stringliteralstart_state
};

static enum tokenType stateMachine_correspondingTokens[STATECOUNT] = {
    [cantmove_state] = cantmove_token,
    [charliteralstart_state] = bad_token,
    [charliteral_state] = charliteral_token,
    [charliteralchewedone_state] = bad_token,
    [charliteralescape_state] = bad_token,
    [charescapeoctal0_state] = bad_token,
    [charescapeoctal1_state] = bad_token,
    [charescapehexempty_state] = bad_token,
    [charescapehex_state] = bad_token,
    [nondecimal_state] = octal_token,
    [fraction_state] = fraction_token,
    [octal_state] = octal_token,
    [oct_u_state] = oct_u_token,
    [oct_lu_state] = oct_lu_token,
    [oct_l_state] = oct_l_token,
    [oct_L_state] = oct_l_token,
    [oct_w_state] = bad_token,
    [oct_W_state] = bad_token,
    [oct_ull_state] = oct_ull_token,
    [oct_ul_state] = oct_lu_token,
    [oct_uL_state] = oct_lu_token,
    [oct_uwb_state] = oct_uwb_token,
    [oct_uw_state] = bad_token,
    [oct_uW_state] = bad_token,
    [oct_ll_state] = oct_ll_token,
    [oct_wb_state] = oct_wb_token,
    [hexfraction_state] = hexfraction_token,
    [hexadecimal_state] = hexadecimal_token,
    [hex_u_state] = hex_u_token,
    [hex_lu_state] = hex_lu_token,
    [hex_l_state] = hex_l_token,
    [hex_L_state] = hex_l_token,
    [hex_w_state] = bad_token,
    [hex_W_state] = bad_token,
    [hex_ull_state] = hex_ull_token,
    [hex_ul_state] = hex_lu_token,
    [hex_uL_state] = hex_lu_token,
    [hex_uwb_state] = hex_uwb_token,
    [hex_uw_state] = bad_token,
    [hex_uW_state] = bad_token,
    [hex_ll_state] = hex_ll_token,
    [hex_wb_state] = hex_wb_token,
    [decimalfraction_state] = decimalfraction_token,
    [decimal_state] = decimal_token,
    [decimal_u_state] = decimal_u_token,
    [decimal_lu_state] = decimal_lu_token,
    [decimal_l_state] = decimal_l_token,
    [decimal_L_state] = decimal_l_token,
    [decimal_w_state] = bad_token,
    [decimal_W_state] = bad_token,
    [decimal_ull_state] = decimal_ull_token,
    [decimal_ul_state] = decimal_lu_token,
    [decimal_uL_state] = decimal_lu_token,
    [decimal_uwb_state] = decimal_uwb_token,
    [decimal_uw_state] = bad_token,
    [decimal_uW_state] = bad_token,
    [decimal_ll_state] = decimal_ll_token,
    [decimal_wb_state] = decimal_wb_token,
    [newline_state] = newline_token,
    [lparen_state] = lparen_token,
    [rparen_state] = rparen_token,
    [lcurly_state] = lcurly_token,
    [rcurly_state] = rcurly_token,
    [rbracket_state] = rbracket_token,
    [lbracket_state] = lbracket_token,
    [question_state] = question_token,
    [semicolon_state] = semicolon_token,
    [colon_state] = colon_token,
    [comma_state] = comma_token,
    [dot_state] = dot_token,
    [eof_state] = eof_token,
    [start_state] = bad_token,
    [identifier_state] = identifier_token,
    [modeq_state] = modeq_token,
    [mod_state] = mod_token,
    [minuseq_state] = minuseq_token,
    [arrow_state] = arrow_token,
    [minus_state] = minus_token,
    [xoreq_state] = xoreq_token,
    [caret_state] = caret_token,
    [bnoteq_state] = bnoteq_token,
    [tilde_state] = tilde_token,
    [boreq_state] = boreq_token,
    [lor_state] = lor_token,
    [pipe_state] = pipe_token,
    [eq_state] = eq_token,
    [assignment_state] = assignment_token,
    [pluseq_state] = pluseq_token,
    [plus_state] = plus_token,
    [shiftleft_state] = shiftleft_token,
    [le_state] = le_token,
    [langle_state] = langle_token,
    [shiftright_state] = shiftright_token,
    [ge_state] = ge_token,
    [rangle_state] = rangle_token,
    [div_state] = div_token,
    [linecomment_state] = linecomment_token,
    [blockcomment_state] = bad_token,
    [blockcommentweak_state] = bad_token,
    [blockcommentfinish_state] = blockcomment_token,
    [bandeq_state] = bandeq_token,
    [and_state] = and_token,
    [amp_state] = amp_token,
    [timeseq_state] = timeseq_token,
    [star_state] = star_token,
    [noteq_state] = noteq_token,
    [exc_state] = exc_token,
    [preproc_state] = preproc_token,
    [whitespace_state] = whitespace_token,
    [stringliteral_state] = stringliteral_token,
    [stringliteralstart_state] = bad_token,
    [stringliteralescape_state] = bad_token,
    [stringescapeoctal0_state] = bad_token,
    [stringescapeoctal1_state] = bad_token,
    [stringescapehexempty_state] = bad_token,
    [stringescapehex_state] = bad_token
};

static unsigned char asciiEnumeration[] = {
    ['y']=1,
    ['7']=2,
    ['}']=3,
    ['\\']=4,
    ['r']=5,
    ['h']=6,
    ['E']=7,
    ['\n']=8,
    ['H']=9,
    [',']=10,
    ['R']=11,
    ['f']=12,
    ['4']=13,
    ['t']=14,
    ['k']=15,
    ['-']=16,
    ['q']=17,
    ['+']=18,
    ['.']=19,
    ['b']=20,
    ['c']=21,
    ['"']=22,
    ['p']=23,
    ['P']=24,
    ['w']=25,
    ['{']=26,
    ['O']=27,
    ['U']=28,
    ['Q']=29,
    ['l']=30,
    [')']=31,
    ['[']=32,
    ['C']=33,
    ['(']=34,
    ['J']=35,
    [255]=36,
    ['?']=37,
    ['~']=38,
    ['>']=39,
    ['%']=40,
    ['e']=41,
    ['X']=42,
    [244]=43,
    ['A']=44,
    ['i']=45,
    ['5']=46,
    [';']=47,
    ['z']=48,
    ['3']=49,
    ['1']=50,
    [']']=51,
    ['\'']=52,
    ['j']=53,
    ['S']=54,
    ['V']=55,
    ['!']=56,
    ['^']=57,
    ['L']=58,
    ['m']=59,
    ['&']=60,
    ['<']=61,
    ['g']=62,
    ['9']=63,
    ['a']=64,
    ['u']=65,
    ['0']=66,
    ['G']=67,
    ['\t']=68,
    ['d']=69,
    ['\r']=70,
    ['F']=71,
    [':']=72,
    ['Y']=73,
    ['W']=74,
    ['T']=75,
    ['_']=76,
    ['s']=77,
    ['B']=78,
    ['Z']=79,
    ['|']=80,
    ['2']=81,
    ['=']=82,
    ['6']=83,
    ['8']=84,
    ['#']=85,
    ['v']=86,
    ['K']=87,
    ['x']=88,
    ['o']=89,
    ['n']=90,
    ['N']=91,
    ['/']=92,
    ['D']=93,
    ['M']=94,
    ['I']=95,
    ['*']=96,
    [' ']=97
};

