
#pragma once
enum tokenType {
    exc_token,
    octal_token,
    preproc_token,
    hex_ll_token,
    eq_token,
    assignment_token,
    mod_token,
    charliteral_token,
    decimal_lu_token,
    cantmove_token,
    dot_token,
    shiftright_token,
    lcurly_token,
    rparen_token,
    hexfraction_token,
    le_token,
    decimalfraction_token,
    linecomment_token,
    colon_token,
    oct_u_token,
    minus_token,
    noteq_token,
    oct_l_token,
    rbracket_token,
    and_token,
    star_token,
    eof_token,
    bnoteq_token,
    div_token,
    decimal_u_token,
    decimal_wb_token,
    oct_wb_token,
    hex_u_token,
    oct_lu_token,
    rangle_token,
    hexadecimal_token,
    hex_ull_token,
    lbracket_token,
    comma_token,
    oct_ull_token,
    hex_uwb_token,
    semicolon_token,
    oct_uwb_token,
    decimal_uwb_token,
    pluseq_token,
    pipe_token,
    shiftleft_token,
    whitespace_token,
    modeq_token,
    decimal_l_token,
    timeseq_token,
    ge_token,
    arrow_token,
    decimal_ll_token,
    hex_l_token,
    boreq_token,
    tilde_token,
    xoreq_token,
    identifier_token,
    blockcomment_token,
    newline_token,
    decimal_ull_token,
    rcurly_token,
    question_token,
    hex_lu_token,
    oct_ll_token,
    amp_token,
    decimal_token,
    lparen_token,
    stringliteral_token,
    plus_token,
    lor_token,
    caret_token,
    bad_token,
    langle_token,
    bandeq_token,
    fraction_token,
    hex_wb_token,
    minuseq_token,
    TOKENCOUNT
};

extern const char* tokenTypeStrings[TOKENCOUNT] = {
    "exc",
    "octal",
    "preproc",
    "hex_ll",
    "eq",
    "assignment",
    "mod",
    "charliteral",
    "decimal_lu",
    "cantmove",
    "dot",
    "shiftright",
    "lcurly",
    "rparen",
    "hexfraction",
    "le",
    "decimalfraction",
    "linecomment",
    "colon",
    "oct_u",
    "minus",
    "noteq",
    "oct_l",
    "rbracket",
    "and",
    "star",
    "eof",
    "bnoteq",
    "div",
    "decimal_u",
    "decimal_wb",
    "oct_wb",
    "hex_u",
    "oct_lu",
    "rangle",
    "hexadecimal",
    "hex_ull",
    "lbracket",
    "comma",
    "oct_ull",
    "hex_uwb",
    "semicolon",
    "oct_uwb",
    "decimal_uwb",
    "pluseq",
    "pipe",
    "shiftleft",
    "whitespace",
    "modeq",
    "decimal_l",
    "timeseq",
    "ge",
    "arrow",
    "decimal_ll",
    "hex_l",
    "boreq",
    "tilde",
    "xoreq",
    "identifier",
    "blockcomment",
    "newline",
    "decimal_ull",
    "rcurly",
    "question",
    "hex_lu",
    "oct_ll",
    "amp",
    "decimal",
    "lparen",
    "stringliteral",
    "plus",
    "lor",
    "caret",
    "bad",
    "langle",
    "bandeq",
    "fraction",
    "hex_wb",
    "minuseq"
};

extern const char* tokenTypeColors[TOKENCOUNT] = {
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;106;153;85m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;106;153;85m",
    "\033[38;2;181;206;168m",
    "\033[38;2;244;71;71m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;255;215;0m",
    "\033[38;2;255;215;0m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;106;153;85m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;255;215;0m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;128;128;128m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;255;215;0m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;156;220;254m",
    "\033[38;2;106;153;85m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;255;215;0m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;255;215;0m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;244;71;71m",
    "\033[38;2;212;212;212m",
    "\033[38;2;212;212;212m",
    "\033[38;2;181;206;168m",
    "\033[38;2;181;206;168m",
    "\033[38;2;212;212;212m"
};

#define MAXCHAR 97

enum state {
    cantmove_state,
    charliteralstart_state,
    charliteral_state,
    charliteralchewedone_state,
    charliteralescape_state,
    charescapeoctal0_state,
    charescapeoctal1_state,
    charescapehexempty_state,
    charescapehex_state,
    nondecimal_state,
    fraction_state,
    octal_state,
    oct_u_state,
    oct_lu_state,
    oct_l_state,
    oct_L_state,
    oct_w_state,
    oct_W_state,
    oct_ull_state,
    oct_ul_state,
    oct_uL_state,
    oct_uwb_state,
    oct_uw_state,
    oct_uW_state,
    oct_ll_state,
    oct_wb_state,
    hexfraction_state,
    hexadecimal_state,
    hex_u_state,
    hex_lu_state,
    hex_l_state,
    hex_L_state,
    hex_w_state,
    hex_W_state,
    hex_ull_state,
    hex_ul_state,
    hex_uL_state,
    hex_uwb_state,
    hex_uw_state,
    hex_uW_state,
    hex_ll_state,
    hex_wb_state,
    decimalfraction_state,
    decimal_state,
    decimal_u_state,
    decimal_lu_state,
    decimal_l_state,
    decimal_L_state,
    decimal_w_state,
    decimal_W_state,
    decimal_ull_state,
    decimal_ul_state,
    decimal_uL_state,
    decimal_uwb_state,
    decimal_uw_state,
    decimal_uW_state,
    decimal_ll_state,
    decimal_wb_state,
    newline_state,
    lparen_state,
    rparen_state,
    lcurly_state,
    rcurly_state,
    rbracket_state,
    lbracket_state,
    question_state,
    semicolon_state,
    colon_state,
    comma_state,
    dot_state,
    eof_state,
    start_state,
    identifier_state,
    modeq_state,
    mod_state,
    minuseq_state,
    arrow_state,
    minus_state,
    xoreq_state,
    caret_state,
    bnoteq_state,
    tilde_state,
    boreq_state,
    lor_state,
    pipe_state,
    eq_state,
    assignment_state,
    pluseq_state,
    plus_state,
    shiftleft_state,
    le_state,
    langle_state,
    shiftright_state,
    ge_state,
    rangle_state,
    div_state,
    linecomment_state,
    blockcomment_state,
    blockcommentweak_state,
    blockcommentfinish_state,
    bandeq_state,
    and_state,
    amp_state,
    timeseq_state,
    star_state,
    noteq_state,
    exc_state,
    preproc_state,
    whitespace_state,
    stringliteral_state,
    stringliteralstart_state,
    stringliteralescape_state,
    stringescapeoctal0_state,
    stringescapeoctal1_state,
    stringescapehexempty_state,
    stringescapehex_state,
    STATECOUNT
};

extern enum state stateMachine_transitions[STATECOUNT][MAXCHAR + 1] = {
    [charliteralstart_state][18] = charliteralescape_state,
    [charliteralstart_state][1] = charliteralchewedone_state,
    [charliteralstart_state][2] = charliteralchewedone_state,
    [charliteralstart_state][3] = charliteralchewedone_state,
    [charliteralstart_state][4] = charliteralchewedone_state,
    [charliteralstart_state][5] = charliteralchewedone_state,
    [charliteralstart_state][6] = charliteralchewedone_state,
    [charliteralstart_state][7] = charliteralchewedone_state,
    [charliteralstart_state][8] = charliteralchewedone_state,
    [charliteralstart_state][9] = charliteralchewedone_state,
    [charliteralstart_state][10] = charliteralchewedone_state,
    [charliteralstart_state][11] = charliteralchewedone_state,
    [charliteralstart_state][12] = charliteralchewedone_state,
    [charliteralstart_state][13] = charliteralchewedone_state,
    [charliteralstart_state][14] = charliteralchewedone_state,
    [charliteralstart_state][15] = charliteralchewedone_state,
    [charliteralstart_state][16] = charliteralchewedone_state,
    [charliteralstart_state][17] = charliteralchewedone_state,
    [charliteralstart_state][19] = charliteralchewedone_state,
    [charliteralstart_state][20] = charliteralchewedone_state,
    [charliteralstart_state][21] = charliteralchewedone_state,
    [charliteralstart_state][22] = charliteralchewedone_state,
    [charliteralstart_state][23] = charliteralchewedone_state,
    [charliteralstart_state][24] = charliteralchewedone_state,
    [charliteralstart_state][25] = charliteralchewedone_state,
    [charliteralstart_state][26] = charliteralchewedone_state,
    [charliteralstart_state][27] = charliteralchewedone_state,
    [charliteralstart_state][28] = charliteralchewedone_state,
    [charliteralstart_state][29] = charliteralchewedone_state,
    [charliteralstart_state][30] = charliteralchewedone_state,
    [charliteralstart_state][31] = charliteralchewedone_state,
    [charliteralstart_state][33] = charliteralchewedone_state,
    [charliteralstart_state][34] = charliteralchewedone_state,
    [charliteralstart_state][35] = charliteralchewedone_state,
    [charliteralstart_state][36] = charliteralchewedone_state,
    [charliteralstart_state][37] = charliteralchewedone_state,
    [charliteralstart_state][39] = charliteralchewedone_state,
    [charliteralstart_state][40] = charliteralchewedone_state,
    [charliteralstart_state][41] = charliteralchewedone_state,
    [charliteralstart_state][42] = charliteralchewedone_state,
    [charliteralstart_state][43] = charliteralchewedone_state,
    [charliteralstart_state][44] = charliteralchewedone_state,
    [charliteralstart_state][45] = charliteralchewedone_state,
    [charliteralstart_state][46] = charliteralchewedone_state,
    [charliteralstart_state][47] = charliteralchewedone_state,
    [charliteralstart_state][48] = charliteralchewedone_state,
    [charliteralstart_state][49] = charliteralchewedone_state,
    [charliteralstart_state][50] = charliteralchewedone_state,
    [charliteralstart_state][51] = charliteralchewedone_state,
    [charliteralstart_state][52] = charliteralchewedone_state,
    [charliteralstart_state][53] = charliteralchewedone_state,
    [charliteralstart_state][54] = charliteralchewedone_state,
    [charliteralstart_state][55] = charliteralchewedone_state,
    [charliteralstart_state][56] = charliteralchewedone_state,
    [charliteralstart_state][57] = charliteralchewedone_state,
    [charliteralstart_state][58] = charliteralchewedone_state,
    [charliteralstart_state][59] = charliteralchewedone_state,
    [charliteralstart_state][60] = charliteralchewedone_state,
    [charliteralstart_state][61] = charliteralchewedone_state,
    [charliteralstart_state][62] = charliteralchewedone_state,
    [charliteralstart_state][63] = charliteralchewedone_state,
    [charliteralstart_state][64] = charliteralchewedone_state,
    [charliteralstart_state][65] = charliteralchewedone_state,
    [charliteralstart_state][66] = charliteralchewedone_state,
    [charliteralstart_state][67] = charliteralchewedone_state,
    [charliteralstart_state][68] = charliteralchewedone_state,
    [charliteralstart_state][69] = charliteralchewedone_state,
    [charliteralstart_state][70] = charliteralchewedone_state,
    [charliteralstart_state][71] = charliteralchewedone_state,
    [charliteralstart_state][72] = charliteralchewedone_state,
    [charliteralstart_state][73] = charliteralchewedone_state,
    [charliteralstart_state][74] = charliteralchewedone_state,
    [charliteralstart_state][75] = charliteralchewedone_state,
    [charliteralstart_state][76] = charliteralchewedone_state,
    [charliteralstart_state][77] = charliteralchewedone_state,
    [charliteralstart_state][78] = charliteralchewedone_state,
    [charliteralstart_state][79] = charliteralchewedone_state,
    [charliteralstart_state][80] = charliteralchewedone_state,
    [charliteralstart_state][81] = charliteralchewedone_state,
    [charliteralstart_state][82] = charliteralchewedone_state,
    [charliteralstart_state][83] = charliteralchewedone_state,
    [charliteralstart_state][84] = charliteralchewedone_state,
    [charliteralstart_state][85] = charliteralchewedone_state,
    [charliteralstart_state][86] = charliteralchewedone_state,
    [charliteralstart_state][87] = charliteralchewedone_state,
    [charliteralstart_state][88] = charliteralchewedone_state,
    [charliteralstart_state][89] = charliteralchewedone_state,
    [charliteralstart_state][90] = charliteralchewedone_state,
    [charliteralstart_state][92] = charliteralchewedone_state,
    [charliteralstart_state][93] = charliteralchewedone_state,
    [charliteralstart_state][94] = charliteralchewedone_state,
    [charliteralstart_state][95] = charliteralchewedone_state,
    [charliteralstart_state][96] = charliteralchewedone_state,
    [charliteralstart_state][97] = charliteralchewedone_state,
    [charliteralchewedone_state][18] = charliteralescape_state,
    [charliteralchewedone_state][91] = charliteral_state,
    [charliteralchewedone_state][1] = charliteralchewedone_state,
    [charliteralchewedone_state][2] = charliteralchewedone_state,
    [charliteralchewedone_state][3] = charliteralchewedone_state,
    [charliteralchewedone_state][4] = charliteralchewedone_state,
    [charliteralchewedone_state][5] = charliteralchewedone_state,
    [charliteralchewedone_state][6] = charliteralchewedone_state,
    [charliteralchewedone_state][7] = charliteralchewedone_state,
    [charliteralchewedone_state][8] = charliteralchewedone_state,
    [charliteralchewedone_state][9] = charliteralchewedone_state,
    [charliteralchewedone_state][10] = charliteralchewedone_state,
    [charliteralchewedone_state][11] = charliteralchewedone_state,
    [charliteralchewedone_state][12] = charliteralchewedone_state,
    [charliteralchewedone_state][13] = charliteralchewedone_state,
    [charliteralchewedone_state][14] = charliteralchewedone_state,
    [charliteralchewedone_state][15] = charliteralchewedone_state,
    [charliteralchewedone_state][16] = charliteralchewedone_state,
    [charliteralchewedone_state][17] = charliteralchewedone_state,
    [charliteralchewedone_state][19] = charliteralchewedone_state,
    [charliteralchewedone_state][20] = charliteralchewedone_state,
    [charliteralchewedone_state][21] = charliteralchewedone_state,
    [charliteralchewedone_state][22] = charliteralchewedone_state,
    [charliteralchewedone_state][23] = charliteralchewedone_state,
    [charliteralchewedone_state][24] = charliteralchewedone_state,
    [charliteralchewedone_state][25] = charliteralchewedone_state,
    [charliteralchewedone_state][26] = charliteralchewedone_state,
    [charliteralchewedone_state][27] = charliteralchewedone_state,
    [charliteralchewedone_state][28] = charliteralchewedone_state,
    [charliteralchewedone_state][29] = charliteralchewedone_state,
    [charliteralchewedone_state][30] = charliteralchewedone_state,
    [charliteralchewedone_state][31] = charliteralchewedone_state,
    [charliteralchewedone_state][33] = charliteralchewedone_state,
    [charliteralchewedone_state][34] = charliteralchewedone_state,
    [charliteralchewedone_state][35] = charliteralchewedone_state,
    [charliteralchewedone_state][36] = charliteralchewedone_state,
    [charliteralchewedone_state][37] = charliteralchewedone_state,
    [charliteralchewedone_state][39] = charliteralchewedone_state,
    [charliteralchewedone_state][40] = charliteralchewedone_state,
    [charliteralchewedone_state][41] = charliteralchewedone_state,
    [charliteralchewedone_state][42] = charliteralchewedone_state,
    [charliteralchewedone_state][43] = charliteralchewedone_state,
    [charliteralchewedone_state][44] = charliteralchewedone_state,
    [charliteralchewedone_state][45] = charliteralchewedone_state,
    [charliteralchewedone_state][46] = charliteralchewedone_state,
    [charliteralchewedone_state][47] = charliteralchewedone_state,
    [charliteralchewedone_state][48] = charliteralchewedone_state,
    [charliteralchewedone_state][49] = charliteralchewedone_state,
    [charliteralchewedone_state][50] = charliteralchewedone_state,
    [charliteralchewedone_state][51] = charliteralchewedone_state,
    [charliteralchewedone_state][52] = charliteralchewedone_state,
    [charliteralchewedone_state][53] = charliteralchewedone_state,
    [charliteralchewedone_state][54] = charliteralchewedone_state,
    [charliteralchewedone_state][55] = charliteralchewedone_state,
    [charliteralchewedone_state][56] = charliteralchewedone_state,
    [charliteralchewedone_state][57] = charliteralchewedone_state,
    [charliteralchewedone_state][58] = charliteralchewedone_state,
    [charliteralchewedone_state][59] = charliteralchewedone_state,
    [charliteralchewedone_state][60] = charliteralchewedone_state,
    [charliteralchewedone_state][61] = charliteralchewedone_state,
    [charliteralchewedone_state][62] = charliteralchewedone_state,
    [charliteralchewedone_state][63] = charliteralchewedone_state,
    [charliteralchewedone_state][64] = charliteralchewedone_state,
    [charliteralchewedone_state][65] = charliteralchewedone_state,
    [charliteralchewedone_state][66] = charliteralchewedone_state,
    [charliteralchewedone_state][67] = charliteralchewedone_state,
    [charliteralchewedone_state][68] = charliteralchewedone_state,
    [charliteralchewedone_state][69] = charliteralchewedone_state,
    [charliteralchewedone_state][70] = charliteralchewedone_state,
    [charliteralchewedone_state][71] = charliteralchewedone_state,
    [charliteralchewedone_state][72] = charliteralchewedone_state,
    [charliteralchewedone_state][73] = charliteralchewedone_state,
    [charliteralchewedone_state][74] = charliteralchewedone_state,
    [charliteralchewedone_state][75] = charliteralchewedone_state,
    [charliteralchewedone_state][76] = charliteralchewedone_state,
    [charliteralchewedone_state][77] = charliteralchewedone_state,
    [charliteralchewedone_state][78] = charliteralchewedone_state,
    [charliteralchewedone_state][79] = charliteralchewedone_state,
    [charliteralchewedone_state][80] = charliteralchewedone_state,
    [charliteralchewedone_state][81] = charliteralchewedone_state,
    [charliteralchewedone_state][82] = charliteralchewedone_state,
    [charliteralchewedone_state][83] = charliteralchewedone_state,
    [charliteralchewedone_state][84] = charliteralchewedone_state,
    [charliteralchewedone_state][85] = charliteralchewedone_state,
    [charliteralchewedone_state][86] = charliteralchewedone_state,
    [charliteralchewedone_state][87] = charliteralchewedone_state,
    [charliteralchewedone_state][88] = charliteralchewedone_state,
    [charliteralchewedone_state][89] = charliteralchewedone_state,
    [charliteralchewedone_state][90] = charliteralchewedone_state,
    [charliteralchewedone_state][92] = charliteralchewedone_state,
    [charliteralchewedone_state][93] = charliteralchewedone_state,
    [charliteralchewedone_state][94] = charliteralchewedone_state,
    [charliteralchewedone_state][95] = charliteralchewedone_state,
    [charliteralchewedone_state][96] = charliteralchewedone_state,
    [charliteralchewedone_state][97] = charliteralchewedone_state,
    [charliteralescape_state][91] = charliteralchewedone_state,
    [charliteralescape_state][71] = charliteralchewedone_state,
    [charliteralescape_state][2] = charliteralchewedone_state,
    [charliteralescape_state][18] = charliteralchewedone_state,
    [charliteralescape_state][97] = charliteralchewedone_state,
    [charliteralescape_state][50] = charliteralchewedone_state,
    [charliteralescape_state][15] = charliteralchewedone_state,
    [charliteralescape_state][72] = charliteralchewedone_state,
    [charliteralescape_state][7] = charliteralchewedone_state,
    [charliteralescape_state][62] = charliteralchewedone_state,
    [charliteralescape_state][89] = charliteralchewedone_state,
    [charliteralescape_state][82] = charescapeoctal0_state,
    [charliteralescape_state][57] = charescapeoctal0_state,
    [charliteralescape_state][68] = charescapeoctal0_state,
    [charliteralescape_state][26] = charescapeoctal0_state,
    [charliteralescape_state][49] = charescapeoctal0_state,
    [charliteralescape_state][29] = charescapeoctal0_state,
    [charliteralescape_state][30] = charescapeoctal0_state,
    [charliteralescape_state][96] = charescapeoctal0_state,
    [charliteralescape_state][35] = charescapehexempty_state,
    [charescapeoctal0_state][82] = charescapeoctal1_state,
    [charescapeoctal0_state][57] = charescapeoctal1_state,
    [charescapeoctal0_state][68] = charescapeoctal1_state,
    [charescapeoctal0_state][26] = charescapeoctal1_state,
    [charescapeoctal0_state][49] = charescapeoctal1_state,
    [charescapeoctal0_state][29] = charescapeoctal1_state,
    [charescapeoctal0_state][30] = charescapeoctal1_state,
    [charescapeoctal0_state][96] = charescapeoctal1_state,
    [charescapeoctal0_state][91] = charliteral_state,
    [charescapeoctal1_state][82] = charliteralchewedone_state,
    [charescapeoctal1_state][57] = charliteralchewedone_state,
    [charescapeoctal1_state][68] = charliteralchewedone_state,
    [charescapeoctal1_state][26] = charliteralchewedone_state,
    [charescapeoctal1_state][49] = charliteralchewedone_state,
    [charescapeoctal1_state][29] = charliteralchewedone_state,
    [charescapeoctal1_state][30] = charliteralchewedone_state,
    [charescapeoctal1_state][96] = charliteralchewedone_state,
    [charescapeoctal1_state][91] = charliteral_state,
    [charescapehexempty_state][46] = charescapehex_state,
    [charescapehexempty_state][47] = charescapehex_state,
    [charescapehexempty_state][49] = charescapehex_state,
    [charescapehexempty_state][50] = charescapehex_state,
    [charescapehexempty_state][53] = charescapehex_state,
    [charescapehexempty_state][57] = charescapehex_state,
    [charescapehexempty_state][58] = charescapehex_state,
    [charescapehexempty_state][15] = charescapehex_state,
    [charescapehexempty_state][25] = charescapehex_state,
    [charescapehexempty_state][26] = charescapehex_state,
    [charescapehexempty_state][68] = charescapehex_state,
    [charescapehexempty_state][27] = charescapehex_state,
    [charescapehexempty_state][28] = charescapehex_state,
    [charescapehexempty_state][29] = charescapehex_state,
    [charescapehexempty_state][30] = charescapehex_state,
    [charescapehexempty_state][82] = charescapehex_state,
    [charescapehexempty_state][39] = charescapehex_state,
    [charescapehexempty_state][42] = charescapehex_state,
    [charescapehexempty_state][59] = charescapehex_state,
    [charescapehexempty_state][94] = charescapehex_state,
    [charescapehexempty_state][96] = charescapehex_state,
    [charescapehexempty_state][97] = charescapehex_state,
    [charescapehex_state][46] = charescapehex_state,
    [charescapehex_state][47] = charescapehex_state,
    [charescapehex_state][49] = charescapehex_state,
    [charescapehex_state][50] = charescapehex_state,
    [charescapehex_state][53] = charescapehex_state,
    [charescapehex_state][57] = charescapehex_state,
    [charescapehex_state][58] = charescapehex_state,
    [charescapehex_state][15] = charescapehex_state,
    [charescapehex_state][25] = charescapehex_state,
    [charescapehex_state][26] = charescapehex_state,
    [charescapehex_state][68] = charescapehex_state,
    [charescapehex_state][27] = charescapehex_state,
    [charescapehex_state][28] = charescapehex_state,
    [charescapehex_state][29] = charescapehex_state,
    [charescapehex_state][30] = charescapehex_state,
    [charescapehex_state][82] = charescapehex_state,
    [charescapehex_state][39] = charescapehex_state,
    [charescapehex_state][42] = charescapehex_state,
    [charescapehex_state][59] = charescapehex_state,
    [charescapehex_state][94] = charescapehex_state,
    [charescapehex_state][96] = charescapehex_state,
    [charescapehex_state][97] = charescapehex_state,
    [charescapehex_state][91] = charliteral_state,
    [nondecimal_state][35] = hexadecimal_state,
    [nondecimal_state][84] = hexadecimal_state,
    [nondecimal_state][82] = octal_state,
    [nondecimal_state][57] = octal_state,
    [nondecimal_state][68] = octal_state,
    [nondecimal_state][26] = octal_state,
    [nondecimal_state][49] = octal_state,
    [nondecimal_state][29] = octal_state,
    [nondecimal_state][30] = octal_state,
    [nondecimal_state][96] = octal_state,
    [octal_state][82] = octal_state,
    [octal_state][57] = octal_state,
    [octal_state][68] = octal_state,
    [octal_state][26] = octal_state,
    [octal_state][49] = octal_state,
    [octal_state][29] = octal_state,
    [octal_state][30] = octal_state,
    [octal_state][96] = octal_state,
    [octal_state][91] = octal_state,
    [octal_state][74] = fraction_state,
    [octal_state][31] = oct_u_state,
    [octal_state][34] = oct_u_state,
    [octal_state][6] = oct_l_state,
    [octal_state][51] = oct_L_state,
    [octal_state][48] = oct_w_state,
    [octal_state][33] = oct_W_state,
    [oct_u_state][6] = oct_ul_state,
    [oct_u_state][51] = oct_uL_state,
    [oct_u_state][48] = oct_uw_state,
    [oct_u_state][33] = oct_uW_state,
    [oct_l_state][6] = oct_ll_state,
    [oct_l_state][31] = oct_lu_state,
    [oct_l_state][34] = oct_lu_state,
    [oct_L_state][51] = oct_ll_state,
    [oct_L_state][31] = oct_lu_state,
    [oct_L_state][34] = oct_lu_state,
    [oct_w_state][50] = oct_wb_state,
    [oct_W_state][25] = oct_wb_state,
    [oct_ul_state][6] = oct_ull_state,
    [oct_uL_state][51] = oct_ull_state,
    [oct_uw_state][50] = oct_uwb_state,
    [oct_uW_state][25] = oct_uwb_state,
    [oct_ll_state][31] = oct_ull_state,
    [oct_ll_state][34] = oct_ull_state,
    [oct_wb_state][31] = oct_uwb_state,
    [oct_wb_state][34] = oct_uwb_state,
    [hexadecimal_state][46] = hexadecimal_state,
    [hexadecimal_state][47] = hexadecimal_state,
    [hexadecimal_state][49] = hexadecimal_state,
    [hexadecimal_state][50] = hexadecimal_state,
    [hexadecimal_state][53] = hexadecimal_state,
    [hexadecimal_state][57] = hexadecimal_state,
    [hexadecimal_state][58] = hexadecimal_state,
    [hexadecimal_state][15] = hexadecimal_state,
    [hexadecimal_state][25] = hexadecimal_state,
    [hexadecimal_state][26] = hexadecimal_state,
    [hexadecimal_state][68] = hexadecimal_state,
    [hexadecimal_state][27] = hexadecimal_state,
    [hexadecimal_state][28] = hexadecimal_state,
    [hexadecimal_state][29] = hexadecimal_state,
    [hexadecimal_state][30] = hexadecimal_state,
    [hexadecimal_state][82] = hexadecimal_state,
    [hexadecimal_state][39] = hexadecimal_state,
    [hexadecimal_state][42] = hexadecimal_state,
    [hexadecimal_state][59] = hexadecimal_state,
    [hexadecimal_state][94] = hexadecimal_state,
    [hexadecimal_state][96] = hexadecimal_state,
    [hexadecimal_state][97] = hexadecimal_state,
    [hexadecimal_state][91] = hexadecimal_state,
    [hexadecimal_state][74] = hexfraction_state,
    [hexadecimal_state][31] = hex_u_state,
    [hexadecimal_state][34] = hex_u_state,
    [hexadecimal_state][6] = hex_l_state,
    [hexadecimal_state][51] = hex_L_state,
    [hexadecimal_state][48] = hex_w_state,
    [hexadecimal_state][33] = hex_W_state,
    [hex_u_state][6] = hex_ul_state,
    [hex_u_state][51] = hex_uL_state,
    [hex_u_state][48] = hex_uw_state,
    [hex_u_state][33] = hex_uW_state,
    [hex_l_state][6] = hex_ll_state,
    [hex_l_state][31] = hex_lu_state,
    [hex_l_state][34] = hex_lu_state,
    [hex_L_state][51] = hex_ll_state,
    [hex_L_state][31] = hex_lu_state,
    [hex_L_state][34] = hex_lu_state,
    [hex_w_state][50] = hex_wb_state,
    [hex_W_state][25] = hex_wb_state,
    [hex_ul_state][6] = hex_ull_state,
    [hex_uL_state][51] = hex_ull_state,
    [hex_uw_state][50] = hex_uwb_state,
    [hex_uW_state][25] = hex_uwb_state,
    [hex_ll_state][31] = hex_ull_state,
    [hex_ll_state][34] = hex_ull_state,
    [hex_wb_state][31] = hex_uwb_state,
    [hex_wb_state][34] = hex_uwb_state,
    [decimal_state][82] = decimal_state,
    [decimal_state][57] = decimal_state,
    [decimal_state][68] = decimal_state,
    [decimal_state][26] = decimal_state,
    [decimal_state][27] = decimal_state,
    [decimal_state][58] = decimal_state,
    [decimal_state][49] = decimal_state,
    [decimal_state][29] = decimal_state,
    [decimal_state][30] = decimal_state,
    [decimal_state][96] = decimal_state,
    [decimal_state][91] = decimal_state,
    [decimal_state][74] = decimalfraction_state,
    [decimal_state][31] = decimal_u_state,
    [decimal_state][34] = decimal_u_state,
    [decimal_state][6] = decimal_l_state,
    [decimal_state][51] = decimal_L_state,
    [decimal_state][48] = decimal_w_state,
    [decimal_state][33] = decimal_W_state,
    [decimal_u_state][6] = decimal_ul_state,
    [decimal_u_state][51] = decimal_uL_state,
    [decimal_u_state][48] = decimal_uw_state,
    [decimal_u_state][33] = decimal_uW_state,
    [decimal_l_state][6] = decimal_ll_state,
    [decimal_l_state][31] = decimal_lu_state,
    [decimal_l_state][34] = decimal_lu_state,
    [decimal_L_state][51] = decimal_ll_state,
    [decimal_L_state][31] = decimal_lu_state,
    [decimal_L_state][34] = decimal_lu_state,
    [decimal_w_state][50] = decimal_wb_state,
    [decimal_W_state][25] = decimal_wb_state,
    [decimal_ul_state][6] = decimal_ull_state,
    [decimal_uL_state][51] = decimal_ull_state,
    [decimal_uw_state][50] = decimal_uwb_state,
    [decimal_uW_state][25] = decimal_uwb_state,
    [decimal_ll_state][31] = decimal_ull_state,
    [decimal_ll_state][34] = decimal_ull_state,
    [decimal_wb_state][31] = decimal_uwb_state,
    [decimal_wb_state][34] = decimal_uwb_state,
    [start_state][46] = identifier_state,
    [start_state][47] = identifier_state,
    [start_state][1] = identifier_state,
    [start_state][48] = identifier_state,
    [start_state][3] = identifier_state,
    [start_state][50] = identifier_state,
    [start_state][51] = identifier_state,
    [start_state][53] = identifier_state,
    [start_state][6] = identifier_state,
    [start_state][55] = identifier_state,
    [start_state][7] = identifier_state,
    [start_state][54] = identifier_state,
    [start_state][9] = identifier_state,
    [start_state][10] = identifier_state,
    [start_state][13] = identifier_state,
    [start_state][15] = identifier_state,
    [start_state][93] = identifier_state,
    [start_state][60] = identifier_state,
    [start_state][63] = identifier_state,
    [start_state][62] = identifier_state,
    [start_state][21] = identifier_state,
    [start_state][65] = identifier_state,
    [start_state][64] = identifier_state,
    [start_state][66] = identifier_state,
    [start_state][23] = identifier_state,
    [start_state][67] = identifier_state,
    [start_state][24] = identifier_state,
    [start_state][25] = identifier_state,
    [start_state][28] = identifier_state,
    [start_state][72] = identifier_state,
    [start_state][31] = identifier_state,
    [start_state][73] = identifier_state,
    [start_state][44] = identifier_state,
    [start_state][75] = identifier_state,
    [start_state][33] = identifier_state,
    [start_state][34] = identifier_state,
    [start_state][80] = identifier_state,
    [start_state][83] = identifier_state,
    [start_state][84] = identifier_state,
    [start_state][35] = identifier_state,
    [start_state][86] = identifier_state,
    [start_state][87] = identifier_state,
    [start_state][88] = identifier_state,
    [start_state][89] = identifier_state,
    [start_state][39] = identifier_state,
    [start_state][40] = identifier_state,
    [start_state][92] = identifier_state,
    [start_state][42] = identifier_state,
    [start_state][41] = identifier_state,
    [start_state][59] = identifier_state,
    [start_state][94] = identifier_state,
    [start_state][45] = identifier_state,
    [start_state][97] = identifier_state,
    [start_state][82] = nondecimal_state,
    [start_state][57] = decimal_state,
    [start_state][68] = decimal_state,
    [start_state][26] = decimal_state,
    [start_state][27] = decimal_state,
    [start_state][58] = decimal_state,
    [start_state][49] = decimal_state,
    [start_state][29] = decimal_state,
    [start_state][30] = decimal_state,
    [start_state][96] = decimal_state,
    [start_state][77] = whitespace_state,
    [start_state][16] = whitespace_state,
    [start_state][22] = whitespace_state,
    [start_state][38] = newline_state,
    [start_state][12] = mod_state,
    [start_state][70] = minus_state,
    [start_state][43] = plus_state,
    [start_state][76] = caret_state,
    [start_state][5] = tilde_state,
    [start_state][37] = lparen_state,
    [start_state][79] = rparen_state,
    [start_state][52] = lcurly_state,
    [start_state][95] = rcurly_state,
    [start_state][4] = rbracket_state,
    [start_state][14] = lbracket_state,
    [start_state][2] = question_state,
    [start_state][8] = semicolon_state,
    [start_state][81] = colon_state,
    [start_state][61] = assignment_state,
    [start_state][17] = langle_state,
    [start_state][19] = rangle_state,
    [start_state][20] = div_state,
    [start_state][11] = star_state,
    [start_state][78] = preproc_state,
    [start_state][85] = amp_state,
    [start_state][90] = comma_state,
    [start_state][74] = dot_state,
    [start_state][56] = exc_state,
    [start_state][71] = stringliteralstart_state,
    [start_state][69] = pipe_state,
    [start_state][91] = charliteralstart_state,
    [start_state][32] = eof_state,
    [identifier_state][46] = identifier_state,
    [identifier_state][47] = identifier_state,
    [identifier_state][1] = identifier_state,
    [identifier_state][48] = identifier_state,
    [identifier_state][3] = identifier_state,
    [identifier_state][50] = identifier_state,
    [identifier_state][51] = identifier_state,
    [identifier_state][53] = identifier_state,
    [identifier_state][6] = identifier_state,
    [identifier_state][55] = identifier_state,
    [identifier_state][7] = identifier_state,
    [identifier_state][54] = identifier_state,
    [identifier_state][9] = identifier_state,
    [identifier_state][10] = identifier_state,
    [identifier_state][13] = identifier_state,
    [identifier_state][15] = identifier_state,
    [identifier_state][93] = identifier_state,
    [identifier_state][60] = identifier_state,
    [identifier_state][63] = identifier_state,
    [identifier_state][62] = identifier_state,
    [identifier_state][21] = identifier_state,
    [identifier_state][65] = identifier_state,
    [identifier_state][64] = identifier_state,
    [identifier_state][66] = identifier_state,
    [identifier_state][23] = identifier_state,
    [identifier_state][67] = identifier_state,
    [identifier_state][24] = identifier_state,
    [identifier_state][25] = identifier_state,
    [identifier_state][28] = identifier_state,
    [identifier_state][72] = identifier_state,
    [identifier_state][31] = identifier_state,
    [identifier_state][73] = identifier_state,
    [identifier_state][44] = identifier_state,
    [identifier_state][75] = identifier_state,
    [identifier_state][33] = identifier_state,
    [identifier_state][34] = identifier_state,
    [identifier_state][80] = identifier_state,
    [identifier_state][83] = identifier_state,
    [identifier_state][84] = identifier_state,
    [identifier_state][35] = identifier_state,
    [identifier_state][86] = identifier_state,
    [identifier_state][87] = identifier_state,
    [identifier_state][88] = identifier_state,
    [identifier_state][89] = identifier_state,
    [identifier_state][39] = identifier_state,
    [identifier_state][40] = identifier_state,
    [identifier_state][92] = identifier_state,
    [identifier_state][42] = identifier_state,
    [identifier_state][41] = identifier_state,
    [identifier_state][59] = identifier_state,
    [identifier_state][94] = identifier_state,
    [identifier_state][45] = identifier_state,
    [identifier_state][97] = identifier_state,
    [identifier_state][82] = identifier_state,
    [identifier_state][57] = identifier_state,
    [identifier_state][68] = identifier_state,
    [identifier_state][26] = identifier_state,
    [identifier_state][27] = identifier_state,
    [identifier_state][58] = identifier_state,
    [identifier_state][49] = identifier_state,
    [identifier_state][29] = identifier_state,
    [identifier_state][30] = identifier_state,
    [identifier_state][96] = identifier_state,
    [mod_state][61] = modeq_state,
    [minus_state][61] = minuseq_state,
    [minus_state][19] = arrow_state,
    [caret_state][61] = xoreq_state,
    [tilde_state][61] = bnoteq_state,
    [pipe_state][61] = boreq_state,
    [pipe_state][69] = lor_state,
    [assignment_state][61] = eq_state,
    [plus_state][61] = pluseq_state,
    [langle_state][17] = shiftleft_state,
    [langle_state][61] = le_state,
    [rangle_state][19] = shiftright_state,
    [rangle_state][61] = ge_state,
    [div_state][20] = linecomment_state,
    [div_state][11] = blockcomment_state,
    [linecomment_state][1] = linecomment_state,
    [linecomment_state][2] = linecomment_state,
    [linecomment_state][3] = linecomment_state,
    [linecomment_state][4] = linecomment_state,
    [linecomment_state][5] = linecomment_state,
    [linecomment_state][6] = linecomment_state,
    [linecomment_state][7] = linecomment_state,
    [linecomment_state][8] = linecomment_state,
    [linecomment_state][9] = linecomment_state,
    [linecomment_state][10] = linecomment_state,
    [linecomment_state][11] = linecomment_state,
    [linecomment_state][12] = linecomment_state,
    [linecomment_state][13] = linecomment_state,
    [linecomment_state][14] = linecomment_state,
    [linecomment_state][15] = linecomment_state,
    [linecomment_state][16] = linecomment_state,
    [linecomment_state][17] = linecomment_state,
    [linecomment_state][18] = linecomment_state,
    [linecomment_state][19] = linecomment_state,
    [linecomment_state][20] = linecomment_state,
    [linecomment_state][21] = linecomment_state,
    [linecomment_state][22] = linecomment_state,
    [linecomment_state][23] = linecomment_state,
    [linecomment_state][24] = linecomment_state,
    [linecomment_state][25] = linecomment_state,
    [linecomment_state][26] = linecomment_state,
    [linecomment_state][27] = linecomment_state,
    [linecomment_state][28] = linecomment_state,
    [linecomment_state][29] = linecomment_state,
    [linecomment_state][30] = linecomment_state,
    [linecomment_state][31] = linecomment_state,
    [linecomment_state][33] = linecomment_state,
    [linecomment_state][34] = linecomment_state,
    [linecomment_state][35] = linecomment_state,
    [linecomment_state][36] = linecomment_state,
    [linecomment_state][37] = linecomment_state,
    [linecomment_state][39] = linecomment_state,
    [linecomment_state][40] = linecomment_state,
    [linecomment_state][41] = linecomment_state,
    [linecomment_state][42] = linecomment_state,
    [linecomment_state][43] = linecomment_state,
    [linecomment_state][44] = linecomment_state,
    [linecomment_state][45] = linecomment_state,
    [linecomment_state][46] = linecomment_state,
    [linecomment_state][47] = linecomment_state,
    [linecomment_state][48] = linecomment_state,
    [linecomment_state][49] = linecomment_state,
    [linecomment_state][50] = linecomment_state,
    [linecomment_state][51] = linecomment_state,
    [linecomment_state][52] = linecomment_state,
    [linecomment_state][53] = linecomment_state,
    [linecomment_state][54] = linecomment_state,
    [linecomment_state][55] = linecomment_state,
    [linecomment_state][56] = linecomment_state,
    [linecomment_state][57] = linecomment_state,
    [linecomment_state][58] = linecomment_state,
    [linecomment_state][59] = linecomment_state,
    [linecomment_state][60] = linecomment_state,
    [linecomment_state][61] = linecomment_state,
    [linecomment_state][62] = linecomment_state,
    [linecomment_state][63] = linecomment_state,
    [linecomment_state][64] = linecomment_state,
    [linecomment_state][65] = linecomment_state,
    [linecomment_state][66] = linecomment_state,
    [linecomment_state][67] = linecomment_state,
    [linecomment_state][68] = linecomment_state,
    [linecomment_state][69] = linecomment_state,
    [linecomment_state][70] = linecomment_state,
    [linecomment_state][71] = linecomment_state,
    [linecomment_state][72] = linecomment_state,
    [linecomment_state][73] = linecomment_state,
    [linecomment_state][74] = linecomment_state,
    [linecomment_state][75] = linecomment_state,
    [linecomment_state][76] = linecomment_state,
    [linecomment_state][77] = linecomment_state,
    [linecomment_state][78] = linecomment_state,
    [linecomment_state][79] = linecomment_state,
    [linecomment_state][80] = linecomment_state,
    [linecomment_state][81] = linecomment_state,
    [linecomment_state][82] = linecomment_state,
    [linecomment_state][83] = linecomment_state,
    [linecomment_state][84] = linecomment_state,
    [linecomment_state][85] = linecomment_state,
    [linecomment_state][86] = linecomment_state,
    [linecomment_state][87] = linecomment_state,
    [linecomment_state][88] = linecomment_state,
    [linecomment_state][89] = linecomment_state,
    [linecomment_state][90] = linecomment_state,
    [linecomment_state][91] = linecomment_state,
    [linecomment_state][92] = linecomment_state,
    [linecomment_state][93] = linecomment_state,
    [linecomment_state][94] = linecomment_state,
    [linecomment_state][95] = linecomment_state,
    [linecomment_state][96] = linecomment_state,
    [linecomment_state][97] = linecomment_state,
    [blockcomment_state][11] = blockcommentweak_state,
    [blockcomment_state][1] = blockcomment_state,
    [blockcomment_state][2] = blockcomment_state,
    [blockcomment_state][3] = blockcomment_state,
    [blockcomment_state][4] = blockcomment_state,
    [blockcomment_state][5] = blockcomment_state,
    [blockcomment_state][6] = blockcomment_state,
    [blockcomment_state][7] = blockcomment_state,
    [blockcomment_state][8] = blockcomment_state,
    [blockcomment_state][9] = blockcomment_state,
    [blockcomment_state][10] = blockcomment_state,
    [blockcomment_state][12] = blockcomment_state,
    [blockcomment_state][13] = blockcomment_state,
    [blockcomment_state][14] = blockcomment_state,
    [blockcomment_state][15] = blockcomment_state,
    [blockcomment_state][16] = blockcomment_state,
    [blockcomment_state][17] = blockcomment_state,
    [blockcomment_state][18] = blockcomment_state,
    [blockcomment_state][19] = blockcomment_state,
    [blockcomment_state][20] = blockcomment_state,
    [blockcomment_state][21] = blockcomment_state,
    [blockcomment_state][22] = blockcomment_state,
    [blockcomment_state][23] = blockcomment_state,
    [blockcomment_state][24] = blockcomment_state,
    [blockcomment_state][25] = blockcomment_state,
    [blockcomment_state][26] = blockcomment_state,
    [blockcomment_state][27] = blockcomment_state,
    [blockcomment_state][28] = blockcomment_state,
    [blockcomment_state][29] = blockcomment_state,
    [blockcomment_state][30] = blockcomment_state,
    [blockcomment_state][31] = blockcomment_state,
    [blockcomment_state][33] = blockcomment_state,
    [blockcomment_state][34] = blockcomment_state,
    [blockcomment_state][35] = blockcomment_state,
    [blockcomment_state][36] = blockcomment_state,
    [blockcomment_state][37] = blockcomment_state,
    [blockcomment_state][38] = blockcomment_state,
    [blockcomment_state][39] = blockcomment_state,
    [blockcomment_state][40] = blockcomment_state,
    [blockcomment_state][41] = blockcomment_state,
    [blockcomment_state][42] = blockcomment_state,
    [blockcomment_state][43] = blockcomment_state,
    [blockcomment_state][44] = blockcomment_state,
    [blockcomment_state][45] = blockcomment_state,
    [blockcomment_state][46] = blockcomment_state,
    [blockcomment_state][47] = blockcomment_state,
    [blockcomment_state][48] = blockcomment_state,
    [blockcomment_state][49] = blockcomment_state,
    [blockcomment_state][50] = blockcomment_state,
    [blockcomment_state][51] = blockcomment_state,
    [blockcomment_state][52] = blockcomment_state,
    [blockcomment_state][53] = blockcomment_state,
    [blockcomment_state][54] = blockcomment_state,
    [blockcomment_state][55] = blockcomment_state,
    [blockcomment_state][56] = blockcomment_state,
    [blockcomment_state][57] = blockcomment_state,
    [blockcomment_state][58] = blockcomment_state,
    [blockcomment_state][59] = blockcomment_state,
    [blockcomment_state][60] = blockcomment_state,
    [blockcomment_state][61] = blockcomment_state,
    [blockcomment_state][62] = blockcomment_state,
    [blockcomment_state][63] = blockcomment_state,
    [blockcomment_state][64] = blockcomment_state,
    [blockcomment_state][65] = blockcomment_state,
    [blockcomment_state][66] = blockcomment_state,
    [blockcomment_state][67] = blockcomment_state,
    [blockcomment_state][68] = blockcomment_state,
    [blockcomment_state][69] = blockcomment_state,
    [blockcomment_state][70] = blockcomment_state,
    [blockcomment_state][71] = blockcomment_state,
    [blockcomment_state][72] = blockcomment_state,
    [blockcomment_state][73] = blockcomment_state,
    [blockcomment_state][74] = blockcomment_state,
    [blockcomment_state][75] = blockcomment_state,
    [blockcomment_state][76] = blockcomment_state,
    [blockcomment_state][77] = blockcomment_state,
    [blockcomment_state][78] = blockcomment_state,
    [blockcomment_state][79] = blockcomment_state,
    [blockcomment_state][80] = blockcomment_state,
    [blockcomment_state][81] = blockcomment_state,
    [blockcomment_state][82] = blockcomment_state,
    [blockcomment_state][83] = blockcomment_state,
    [blockcomment_state][84] = blockcomment_state,
    [blockcomment_state][85] = blockcomment_state,
    [blockcomment_state][86] = blockcomment_state,
    [blockcomment_state][87] = blockcomment_state,
    [blockcomment_state][88] = blockcomment_state,
    [blockcomment_state][89] = blockcomment_state,
    [blockcomment_state][90] = blockcomment_state,
    [blockcomment_state][91] = blockcomment_state,
    [blockcomment_state][92] = blockcomment_state,
    [blockcomment_state][93] = blockcomment_state,
    [blockcomment_state][94] = blockcomment_state,
    [blockcomment_state][95] = blockcomment_state,
    [blockcomment_state][96] = blockcomment_state,
    [blockcomment_state][97] = blockcomment_state,
    [blockcommentweak_state][11] = blockcommentweak_state,
    [blockcommentweak_state][20] = blockcommentfinish_state,
    [blockcommentweak_state][1] = blockcomment_state,
    [blockcommentweak_state][2] = blockcomment_state,
    [blockcommentweak_state][3] = blockcomment_state,
    [blockcommentweak_state][4] = blockcomment_state,
    [blockcommentweak_state][5] = blockcomment_state,
    [blockcommentweak_state][6] = blockcomment_state,
    [blockcommentweak_state][7] = blockcomment_state,
    [blockcommentweak_state][8] = blockcomment_state,
    [blockcommentweak_state][9] = blockcomment_state,
    [blockcommentweak_state][10] = blockcomment_state,
    [blockcommentweak_state][12] = blockcomment_state,
    [blockcommentweak_state][13] = blockcomment_state,
    [blockcommentweak_state][14] = blockcomment_state,
    [blockcommentweak_state][15] = blockcomment_state,
    [blockcommentweak_state][16] = blockcomment_state,
    [blockcommentweak_state][17] = blockcomment_state,
    [blockcommentweak_state][18] = blockcomment_state,
    [blockcommentweak_state][19] = blockcomment_state,
    [blockcommentweak_state][21] = blockcomment_state,
    [blockcommentweak_state][22] = blockcomment_state,
    [blockcommentweak_state][23] = blockcomment_state,
    [blockcommentweak_state][24] = blockcomment_state,
    [blockcommentweak_state][25] = blockcomment_state,
    [blockcommentweak_state][26] = blockcomment_state,
    [blockcommentweak_state][27] = blockcomment_state,
    [blockcommentweak_state][28] = blockcomment_state,
    [blockcommentweak_state][29] = blockcomment_state,
    [blockcommentweak_state][30] = blockcomment_state,
    [blockcommentweak_state][31] = blockcomment_state,
    [blockcommentweak_state][33] = blockcomment_state,
    [blockcommentweak_state][34] = blockcomment_state,
    [blockcommentweak_state][35] = blockcomment_state,
    [blockcommentweak_state][36] = blockcomment_state,
    [blockcommentweak_state][37] = blockcomment_state,
    [blockcommentweak_state][38] = blockcomment_state,
    [blockcommentweak_state][39] = blockcomment_state,
    [blockcommentweak_state][40] = blockcomment_state,
    [blockcommentweak_state][41] = blockcomment_state,
    [blockcommentweak_state][42] = blockcomment_state,
    [blockcommentweak_state][43] = blockcomment_state,
    [blockcommentweak_state][44] = blockcomment_state,
    [blockcommentweak_state][45] = blockcomment_state,
    [blockcommentweak_state][46] = blockcomment_state,
    [blockcommentweak_state][47] = blockcomment_state,
    [blockcommentweak_state][48] = blockcomment_state,
    [blockcommentweak_state][49] = blockcomment_state,
    [blockcommentweak_state][50] = blockcomment_state,
    [blockcommentweak_state][51] = blockcomment_state,
    [blockcommentweak_state][52] = blockcomment_state,
    [blockcommentweak_state][53] = blockcomment_state,
    [blockcommentweak_state][54] = blockcomment_state,
    [blockcommentweak_state][55] = blockcomment_state,
    [blockcommentweak_state][56] = blockcomment_state,
    [blockcommentweak_state][57] = blockcomment_state,
    [blockcommentweak_state][58] = blockcomment_state,
    [blockcommentweak_state][59] = blockcomment_state,
    [blockcommentweak_state][60] = blockcomment_state,
    [blockcommentweak_state][61] = blockcomment_state,
    [blockcommentweak_state][62] = blockcomment_state,
    [blockcommentweak_state][63] = blockcomment_state,
    [blockcommentweak_state][64] = blockcomment_state,
    [blockcommentweak_state][65] = blockcomment_state,
    [blockcommentweak_state][66] = blockcomment_state,
    [blockcommentweak_state][67] = blockcomment_state,
    [blockcommentweak_state][68] = blockcomment_state,
    [blockcommentweak_state][69] = blockcomment_state,
    [blockcommentweak_state][70] = blockcomment_state,
    [blockcommentweak_state][71] = blockcomment_state,
    [blockcommentweak_state][72] = blockcomment_state,
    [blockcommentweak_state][73] = blockcomment_state,
    [blockcommentweak_state][74] = blockcomment_state,
    [blockcommentweak_state][75] = blockcomment_state,
    [blockcommentweak_state][76] = blockcomment_state,
    [blockcommentweak_state][77] = blockcomment_state,
    [blockcommentweak_state][78] = blockcomment_state,
    [blockcommentweak_state][79] = blockcomment_state,
    [blockcommentweak_state][80] = blockcomment_state,
    [blockcommentweak_state][81] = blockcomment_state,
    [blockcommentweak_state][82] = blockcomment_state,
    [blockcommentweak_state][83] = blockcomment_state,
    [blockcommentweak_state][84] = blockcomment_state,
    [blockcommentweak_state][85] = blockcomment_state,
    [blockcommentweak_state][86] = blockcomment_state,
    [blockcommentweak_state][87] = blockcomment_state,
    [blockcommentweak_state][88] = blockcomment_state,
    [blockcommentweak_state][89] = blockcomment_state,
    [blockcommentweak_state][90] = blockcomment_state,
    [blockcommentweak_state][91] = blockcomment_state,
    [blockcommentweak_state][92] = blockcomment_state,
    [blockcommentweak_state][93] = blockcomment_state,
    [blockcommentweak_state][94] = blockcomment_state,
    [blockcommentweak_state][95] = blockcomment_state,
    [blockcommentweak_state][96] = blockcomment_state,
    [blockcommentweak_state][97] = blockcomment_state,
    [amp_state][61] = bandeq_state,
    [amp_state][85] = and_state,
    [star_state][61] = timeseq_state,
    [exc_state][61] = noteq_state,
    [preproc_state][1] = preproc_state,
    [preproc_state][2] = preproc_state,
    [preproc_state][3] = preproc_state,
    [preproc_state][4] = preproc_state,
    [preproc_state][5] = preproc_state,
    [preproc_state][6] = preproc_state,
    [preproc_state][7] = preproc_state,
    [preproc_state][8] = preproc_state,
    [preproc_state][9] = preproc_state,
    [preproc_state][10] = preproc_state,
    [preproc_state][11] = preproc_state,
    [preproc_state][12] = preproc_state,
    [preproc_state][13] = preproc_state,
    [preproc_state][14] = preproc_state,
    [preproc_state][15] = preproc_state,
    [preproc_state][16] = preproc_state,
    [preproc_state][17] = preproc_state,
    [preproc_state][18] = preproc_state,
    [preproc_state][19] = preproc_state,
    [preproc_state][20] = preproc_state,
    [preproc_state][21] = preproc_state,
    [preproc_state][22] = preproc_state,
    [preproc_state][23] = preproc_state,
    [preproc_state][24] = preproc_state,
    [preproc_state][25] = preproc_state,
    [preproc_state][26] = preproc_state,
    [preproc_state][27] = preproc_state,
    [preproc_state][28] = preproc_state,
    [preproc_state][29] = preproc_state,
    [preproc_state][30] = preproc_state,
    [preproc_state][31] = preproc_state,
    [preproc_state][33] = preproc_state,
    [preproc_state][34] = preproc_state,
    [preproc_state][35] = preproc_state,
    [preproc_state][36] = preproc_state,
    [preproc_state][37] = preproc_state,
    [preproc_state][39] = preproc_state,
    [preproc_state][40] = preproc_state,
    [preproc_state][41] = preproc_state,
    [preproc_state][42] = preproc_state,
    [preproc_state][43] = preproc_state,
    [preproc_state][44] = preproc_state,
    [preproc_state][45] = preproc_state,
    [preproc_state][46] = preproc_state,
    [preproc_state][47] = preproc_state,
    [preproc_state][48] = preproc_state,
    [preproc_state][49] = preproc_state,
    [preproc_state][50] = preproc_state,
    [preproc_state][51] = preproc_state,
    [preproc_state][52] = preproc_state,
    [preproc_state][53] = preproc_state,
    [preproc_state][54] = preproc_state,
    [preproc_state][55] = preproc_state,
    [preproc_state][56] = preproc_state,
    [preproc_state][57] = preproc_state,
    [preproc_state][58] = preproc_state,
    [preproc_state][59] = preproc_state,
    [preproc_state][60] = preproc_state,
    [preproc_state][61] = preproc_state,
    [preproc_state][62] = preproc_state,
    [preproc_state][63] = preproc_state,
    [preproc_state][64] = preproc_state,
    [preproc_state][65] = preproc_state,
    [preproc_state][66] = preproc_state,
    [preproc_state][67] = preproc_state,
    [preproc_state][68] = preproc_state,
    [preproc_state][69] = preproc_state,
    [preproc_state][70] = preproc_state,
    [preproc_state][71] = preproc_state,
    [preproc_state][72] = preproc_state,
    [preproc_state][73] = preproc_state,
    [preproc_state][74] = preproc_state,
    [preproc_state][75] = preproc_state,
    [preproc_state][76] = preproc_state,
    [preproc_state][77] = preproc_state,
    [preproc_state][78] = preproc_state,
    [preproc_state][79] = preproc_state,
    [preproc_state][80] = preproc_state,
    [preproc_state][81] = preproc_state,
    [preproc_state][82] = preproc_state,
    [preproc_state][83] = preproc_state,
    [preproc_state][84] = preproc_state,
    [preproc_state][85] = preproc_state,
    [preproc_state][86] = preproc_state,
    [preproc_state][87] = preproc_state,
    [preproc_state][88] = preproc_state,
    [preproc_state][89] = preproc_state,
    [preproc_state][90] = preproc_state,
    [preproc_state][91] = preproc_state,
    [preproc_state][92] = preproc_state,
    [preproc_state][93] = preproc_state,
    [preproc_state][94] = preproc_state,
    [preproc_state][95] = preproc_state,
    [preproc_state][96] = preproc_state,
    [preproc_state][97] = preproc_state,
    [whitespace_state][77] = whitespace_state,
    [whitespace_state][16] = whitespace_state,
    [whitespace_state][22] = whitespace_state,
    [whitespace_state][38] = newline_state,
    [stringliteralstart_state][18] = stringliteralescape_state,
    [stringliteralstart_state][71] = stringliteral_state,
    [stringliteralstart_state][1] = stringliteralstart_state,
    [stringliteralstart_state][2] = stringliteralstart_state,
    [stringliteralstart_state][3] = stringliteralstart_state,
    [stringliteralstart_state][4] = stringliteralstart_state,
    [stringliteralstart_state][5] = stringliteralstart_state,
    [stringliteralstart_state][6] = stringliteralstart_state,
    [stringliteralstart_state][7] = stringliteralstart_state,
    [stringliteralstart_state][8] = stringliteralstart_state,
    [stringliteralstart_state][9] = stringliteralstart_state,
    [stringliteralstart_state][10] = stringliteralstart_state,
    [stringliteralstart_state][11] = stringliteralstart_state,
    [stringliteralstart_state][12] = stringliteralstart_state,
    [stringliteralstart_state][13] = stringliteralstart_state,
    [stringliteralstart_state][14] = stringliteralstart_state,
    [stringliteralstart_state][15] = stringliteralstart_state,
    [stringliteralstart_state][16] = stringliteralstart_state,
    [stringliteralstart_state][17] = stringliteralstart_state,
    [stringliteralstart_state][19] = stringliteralstart_state,
    [stringliteralstart_state][20] = stringliteralstart_state,
    [stringliteralstart_state][21] = stringliteralstart_state,
    [stringliteralstart_state][22] = stringliteralstart_state,
    [stringliteralstart_state][23] = stringliteralstart_state,
    [stringliteralstart_state][24] = stringliteralstart_state,
    [stringliteralstart_state][25] = stringliteralstart_state,
    [stringliteralstart_state][26] = stringliteralstart_state,
    [stringliteralstart_state][27] = stringliteralstart_state,
    [stringliteralstart_state][28] = stringliteralstart_state,
    [stringliteralstart_state][29] = stringliteralstart_state,
    [stringliteralstart_state][30] = stringliteralstart_state,
    [stringliteralstart_state][31] = stringliteralstart_state,
    [stringliteralstart_state][33] = stringliteralstart_state,
    [stringliteralstart_state][34] = stringliteralstart_state,
    [stringliteralstart_state][35] = stringliteralstart_state,
    [stringliteralstart_state][36] = stringliteralstart_state,
    [stringliteralstart_state][37] = stringliteralstart_state,
    [stringliteralstart_state][39] = stringliteralstart_state,
    [stringliteralstart_state][40] = stringliteralstart_state,
    [stringliteralstart_state][41] = stringliteralstart_state,
    [stringliteralstart_state][42] = stringliteralstart_state,
    [stringliteralstart_state][43] = stringliteralstart_state,
    [stringliteralstart_state][44] = stringliteralstart_state,
    [stringliteralstart_state][45] = stringliteralstart_state,
    [stringliteralstart_state][46] = stringliteralstart_state,
    [stringliteralstart_state][47] = stringliteralstart_state,
    [stringliteralstart_state][48] = stringliteralstart_state,
    [stringliteralstart_state][49] = stringliteralstart_state,
    [stringliteralstart_state][50] = stringliteralstart_state,
    [stringliteralstart_state][51] = stringliteralstart_state,
    [stringliteralstart_state][52] = stringliteralstart_state,
    [stringliteralstart_state][53] = stringliteralstart_state,
    [stringliteralstart_state][54] = stringliteralstart_state,
    [stringliteralstart_state][55] = stringliteralstart_state,
    [stringliteralstart_state][56] = stringliteralstart_state,
    [stringliteralstart_state][57] = stringliteralstart_state,
    [stringliteralstart_state][58] = stringliteralstart_state,
    [stringliteralstart_state][59] = stringliteralstart_state,
    [stringliteralstart_state][60] = stringliteralstart_state,
    [stringliteralstart_state][61] = stringliteralstart_state,
    [stringliteralstart_state][62] = stringliteralstart_state,
    [stringliteralstart_state][63] = stringliteralstart_state,
    [stringliteralstart_state][64] = stringliteralstart_state,
    [stringliteralstart_state][65] = stringliteralstart_state,
    [stringliteralstart_state][66] = stringliteralstart_state,
    [stringliteralstart_state][67] = stringliteralstart_state,
    [stringliteralstart_state][68] = stringliteralstart_state,
    [stringliteralstart_state][69] = stringliteralstart_state,
    [stringliteralstart_state][70] = stringliteralstart_state,
    [stringliteralstart_state][72] = stringliteralstart_state,
    [stringliteralstart_state][73] = stringliteralstart_state,
    [stringliteralstart_state][74] = stringliteralstart_state,
    [stringliteralstart_state][75] = stringliteralstart_state,
    [stringliteralstart_state][76] = stringliteralstart_state,
    [stringliteralstart_state][77] = stringliteralstart_state,
    [stringliteralstart_state][78] = stringliteralstart_state,
    [stringliteralstart_state][79] = stringliteralstart_state,
    [stringliteralstart_state][80] = stringliteralstart_state,
    [stringliteralstart_state][81] = stringliteralstart_state,
    [stringliteralstart_state][82] = stringliteralstart_state,
    [stringliteralstart_state][83] = stringliteralstart_state,
    [stringliteralstart_state][84] = stringliteralstart_state,
    [stringliteralstart_state][85] = stringliteralstart_state,
    [stringliteralstart_state][86] = stringliteralstart_state,
    [stringliteralstart_state][87] = stringliteralstart_state,
    [stringliteralstart_state][88] = stringliteralstart_state,
    [stringliteralstart_state][89] = stringliteralstart_state,
    [stringliteralstart_state][90] = stringliteralstart_state,
    [stringliteralstart_state][91] = stringliteralstart_state,
    [stringliteralstart_state][92] = stringliteralstart_state,
    [stringliteralstart_state][93] = stringliteralstart_state,
    [stringliteralstart_state][94] = stringliteralstart_state,
    [stringliteralstart_state][95] = stringliteralstart_state,
    [stringliteralstart_state][96] = stringliteralstart_state,
    [stringliteralstart_state][97] = stringliteralstart_state,
    [stringliteralescape_state][91] = stringliteralstart_state,
    [stringliteralescape_state][71] = stringliteralstart_state,
    [stringliteralescape_state][2] = stringliteralstart_state,
    [stringliteralescape_state][18] = stringliteralstart_state,
    [stringliteralescape_state][97] = stringliteralstart_state,
    [stringliteralescape_state][50] = stringliteralstart_state,
    [stringliteralescape_state][15] = stringliteralstart_state,
    [stringliteralescape_state][72] = stringliteralstart_state,
    [stringliteralescape_state][7] = stringliteralstart_state,
    [stringliteralescape_state][62] = stringliteralstart_state,
    [stringliteralescape_state][89] = stringliteralstart_state,
    [stringliteralescape_state][82] = stringescapeoctal0_state,
    [stringliteralescape_state][57] = stringescapeoctal0_state,
    [stringliteralescape_state][68] = stringescapeoctal0_state,
    [stringliteralescape_state][26] = stringescapeoctal0_state,
    [stringliteralescape_state][49] = stringescapeoctal0_state,
    [stringliteralescape_state][29] = stringescapeoctal0_state,
    [stringliteralescape_state][30] = stringescapeoctal0_state,
    [stringliteralescape_state][96] = stringescapeoctal0_state,
    [stringliteralescape_state][35] = stringescapehexempty_state,
    [stringescapeoctal0_state][82] = stringescapeoctal1_state,
    [stringescapeoctal0_state][57] = stringescapeoctal1_state,
    [stringescapeoctal0_state][68] = stringescapeoctal1_state,
    [stringescapeoctal0_state][26] = stringescapeoctal1_state,
    [stringescapeoctal0_state][49] = stringescapeoctal1_state,
    [stringescapeoctal0_state][29] = stringescapeoctal1_state,
    [stringescapeoctal0_state][30] = stringescapeoctal1_state,
    [stringescapeoctal0_state][96] = stringescapeoctal1_state,
    [stringescapeoctal0_state][71] = stringliteral_state,
    [stringescapeoctal0_state][1] = stringliteralstart_state,
    [stringescapeoctal0_state][2] = stringliteralstart_state,
    [stringescapeoctal0_state][3] = stringliteralstart_state,
    [stringescapeoctal0_state][4] = stringliteralstart_state,
    [stringescapeoctal0_state][5] = stringliteralstart_state,
    [stringescapeoctal0_state][6] = stringliteralstart_state,
    [stringescapeoctal0_state][7] = stringliteralstart_state,
    [stringescapeoctal0_state][8] = stringliteralstart_state,
    [stringescapeoctal0_state][9] = stringliteralstart_state,
    [stringescapeoctal0_state][10] = stringliteralstart_state,
    [stringescapeoctal0_state][11] = stringliteralstart_state,
    [stringescapeoctal0_state][12] = stringliteralstart_state,
    [stringescapeoctal0_state][13] = stringliteralstart_state,
    [stringescapeoctal0_state][14] = stringliteralstart_state,
    [stringescapeoctal0_state][15] = stringliteralstart_state,
    [stringescapeoctal0_state][16] = stringliteralstart_state,
    [stringescapeoctal0_state][17] = stringliteralstart_state,
    [stringescapeoctal0_state][18] = stringliteralstart_state,
    [stringescapeoctal0_state][19] = stringliteralstart_state,
    [stringescapeoctal0_state][20] = stringliteralstart_state,
    [stringescapeoctal0_state][21] = stringliteralstart_state,
    [stringescapeoctal0_state][22] = stringliteralstart_state,
    [stringescapeoctal0_state][23] = stringliteralstart_state,
    [stringescapeoctal0_state][24] = stringliteralstart_state,
    [stringescapeoctal0_state][25] = stringliteralstart_state,
    [stringescapeoctal0_state][27] = stringliteralstart_state,
    [stringescapeoctal0_state][28] = stringliteralstart_state,
    [stringescapeoctal0_state][31] = stringliteralstart_state,
    [stringescapeoctal0_state][33] = stringliteralstart_state,
    [stringescapeoctal0_state][34] = stringliteralstart_state,
    [stringescapeoctal0_state][35] = stringliteralstart_state,
    [stringescapeoctal0_state][36] = stringliteralstart_state,
    [stringescapeoctal0_state][37] = stringliteralstart_state,
    [stringescapeoctal0_state][39] = stringliteralstart_state,
    [stringescapeoctal0_state][40] = stringliteralstart_state,
    [stringescapeoctal0_state][41] = stringliteralstart_state,
    [stringescapeoctal0_state][42] = stringliteralstart_state,
    [stringescapeoctal0_state][43] = stringliteralstart_state,
    [stringescapeoctal0_state][44] = stringliteralstart_state,
    [stringescapeoctal0_state][45] = stringliteralstart_state,
    [stringescapeoctal0_state][46] = stringliteralstart_state,
    [stringescapeoctal0_state][47] = stringliteralstart_state,
    [stringescapeoctal0_state][48] = stringliteralstart_state,
    [stringescapeoctal0_state][50] = stringliteralstart_state,
    [stringescapeoctal0_state][51] = stringliteralstart_state,
    [stringescapeoctal0_state][52] = stringliteralstart_state,
    [stringescapeoctal0_state][53] = stringliteralstart_state,
    [stringescapeoctal0_state][54] = stringliteralstart_state,
    [stringescapeoctal0_state][55] = stringliteralstart_state,
    [stringescapeoctal0_state][56] = stringliteralstart_state,
    [stringescapeoctal0_state][58] = stringliteralstart_state,
    [stringescapeoctal0_state][59] = stringliteralstart_state,
    [stringescapeoctal0_state][60] = stringliteralstart_state,
    [stringescapeoctal0_state][61] = stringliteralstart_state,
    [stringescapeoctal0_state][62] = stringliteralstart_state,
    [stringescapeoctal0_state][63] = stringliteralstart_state,
    [stringescapeoctal0_state][64] = stringliteralstart_state,
    [stringescapeoctal0_state][65] = stringliteralstart_state,
    [stringescapeoctal0_state][66] = stringliteralstart_state,
    [stringescapeoctal0_state][67] = stringliteralstart_state,
    [stringescapeoctal0_state][69] = stringliteralstart_state,
    [stringescapeoctal0_state][70] = stringliteralstart_state,
    [stringescapeoctal0_state][72] = stringliteralstart_state,
    [stringescapeoctal0_state][73] = stringliteralstart_state,
    [stringescapeoctal0_state][74] = stringliteralstart_state,
    [stringescapeoctal0_state][75] = stringliteralstart_state,
    [stringescapeoctal0_state][76] = stringliteralstart_state,
    [stringescapeoctal0_state][77] = stringliteralstart_state,
    [stringescapeoctal0_state][78] = stringliteralstart_state,
    [stringescapeoctal0_state][79] = stringliteralstart_state,
    [stringescapeoctal0_state][80] = stringliteralstart_state,
    [stringescapeoctal0_state][81] = stringliteralstart_state,
    [stringescapeoctal0_state][83] = stringliteralstart_state,
    [stringescapeoctal0_state][84] = stringliteralstart_state,
    [stringescapeoctal0_state][85] = stringliteralstart_state,
    [stringescapeoctal0_state][86] = stringliteralstart_state,
    [stringescapeoctal0_state][87] = stringliteralstart_state,
    [stringescapeoctal0_state][88] = stringliteralstart_state,
    [stringescapeoctal0_state][89] = stringliteralstart_state,
    [stringescapeoctal0_state][90] = stringliteralstart_state,
    [stringescapeoctal0_state][91] = stringliteralstart_state,
    [stringescapeoctal0_state][92] = stringliteralstart_state,
    [stringescapeoctal0_state][93] = stringliteralstart_state,
    [stringescapeoctal0_state][94] = stringliteralstart_state,
    [stringescapeoctal0_state][95] = stringliteralstart_state,
    [stringescapeoctal0_state][97] = stringliteralstart_state,
    [stringescapeoctal1_state][82] = stringliteralstart_state,
    [stringescapeoctal1_state][57] = stringliteralstart_state,
    [stringescapeoctal1_state][68] = stringliteralstart_state,
    [stringescapeoctal1_state][26] = stringliteralstart_state,
    [stringescapeoctal1_state][49] = stringliteralstart_state,
    [stringescapeoctal1_state][29] = stringliteralstart_state,
    [stringescapeoctal1_state][30] = stringliteralstart_state,
    [stringescapeoctal1_state][96] = stringliteralstart_state,
    [stringescapeoctal1_state][71] = stringliteral_state,
    [stringescapeoctal1_state][1] = stringliteralstart_state,
    [stringescapeoctal1_state][2] = stringliteralstart_state,
    [stringescapeoctal1_state][3] = stringliteralstart_state,
    [stringescapeoctal1_state][4] = stringliteralstart_state,
    [stringescapeoctal1_state][5] = stringliteralstart_state,
    [stringescapeoctal1_state][6] = stringliteralstart_state,
    [stringescapeoctal1_state][7] = stringliteralstart_state,
    [stringescapeoctal1_state][8] = stringliteralstart_state,
    [stringescapeoctal1_state][9] = stringliteralstart_state,
    [stringescapeoctal1_state][10] = stringliteralstart_state,
    [stringescapeoctal1_state][11] = stringliteralstart_state,
    [stringescapeoctal1_state][12] = stringliteralstart_state,
    [stringescapeoctal1_state][13] = stringliteralstart_state,
    [stringescapeoctal1_state][14] = stringliteralstart_state,
    [stringescapeoctal1_state][15] = stringliteralstart_state,
    [stringescapeoctal1_state][16] = stringliteralstart_state,
    [stringescapeoctal1_state][17] = stringliteralstart_state,
    [stringescapeoctal1_state][18] = stringliteralstart_state,
    [stringescapeoctal1_state][19] = stringliteralstart_state,
    [stringescapeoctal1_state][20] = stringliteralstart_state,
    [stringescapeoctal1_state][21] = stringliteralstart_state,
    [stringescapeoctal1_state][22] = stringliteralstart_state,
    [stringescapeoctal1_state][23] = stringliteralstart_state,
    [stringescapeoctal1_state][24] = stringliteralstart_state,
    [stringescapeoctal1_state][25] = stringliteralstart_state,
    [stringescapeoctal1_state][27] = stringliteralstart_state,
    [stringescapeoctal1_state][28] = stringliteralstart_state,
    [stringescapeoctal1_state][31] = stringliteralstart_state,
    [stringescapeoctal1_state][33] = stringliteralstart_state,
    [stringescapeoctal1_state][34] = stringliteralstart_state,
    [stringescapeoctal1_state][35] = stringliteralstart_state,
    [stringescapeoctal1_state][36] = stringliteralstart_state,
    [stringescapeoctal1_state][37] = stringliteralstart_state,
    [stringescapeoctal1_state][39] = stringliteralstart_state,
    [stringescapeoctal1_state][40] = stringliteralstart_state,
    [stringescapeoctal1_state][41] = stringliteralstart_state,
    [stringescapeoctal1_state][42] = stringliteralstart_state,
    [stringescapeoctal1_state][43] = stringliteralstart_state,
    [stringescapeoctal1_state][44] = stringliteralstart_state,
    [stringescapeoctal1_state][45] = stringliteralstart_state,
    [stringescapeoctal1_state][46] = stringliteralstart_state,
    [stringescapeoctal1_state][47] = stringliteralstart_state,
    [stringescapeoctal1_state][48] = stringliteralstart_state,
    [stringescapeoctal1_state][50] = stringliteralstart_state,
    [stringescapeoctal1_state][51] = stringliteralstart_state,
    [stringescapeoctal1_state][52] = stringliteralstart_state,
    [stringescapeoctal1_state][53] = stringliteralstart_state,
    [stringescapeoctal1_state][54] = stringliteralstart_state,
    [stringescapeoctal1_state][55] = stringliteralstart_state,
    [stringescapeoctal1_state][56] = stringliteralstart_state,
    [stringescapeoctal1_state][58] = stringliteralstart_state,
    [stringescapeoctal1_state][59] = stringliteralstart_state,
    [stringescapeoctal1_state][60] = stringliteralstart_state,
    [stringescapeoctal1_state][61] = stringliteralstart_state,
    [stringescapeoctal1_state][62] = stringliteralstart_state,
    [stringescapeoctal1_state][63] = stringliteralstart_state,
    [stringescapeoctal1_state][64] = stringliteralstart_state,
    [stringescapeoctal1_state][65] = stringliteralstart_state,
    [stringescapeoctal1_state][66] = stringliteralstart_state,
    [stringescapeoctal1_state][67] = stringliteralstart_state,
    [stringescapeoctal1_state][69] = stringliteralstart_state,
    [stringescapeoctal1_state][70] = stringliteralstart_state,
    [stringescapeoctal1_state][72] = stringliteralstart_state,
    [stringescapeoctal1_state][73] = stringliteralstart_state,
    [stringescapeoctal1_state][74] = stringliteralstart_state,
    [stringescapeoctal1_state][75] = stringliteralstart_state,
    [stringescapeoctal1_state][76] = stringliteralstart_state,
    [stringescapeoctal1_state][77] = stringliteralstart_state,
    [stringescapeoctal1_state][78] = stringliteralstart_state,
    [stringescapeoctal1_state][79] = stringliteralstart_state,
    [stringescapeoctal1_state][80] = stringliteralstart_state,
    [stringescapeoctal1_state][81] = stringliteralstart_state,
    [stringescapeoctal1_state][83] = stringliteralstart_state,
    [stringescapeoctal1_state][84] = stringliteralstart_state,
    [stringescapeoctal1_state][85] = stringliteralstart_state,
    [stringescapeoctal1_state][86] = stringliteralstart_state,
    [stringescapeoctal1_state][87] = stringliteralstart_state,
    [stringescapeoctal1_state][88] = stringliteralstart_state,
    [stringescapeoctal1_state][89] = stringliteralstart_state,
    [stringescapeoctal1_state][90] = stringliteralstart_state,
    [stringescapeoctal1_state][91] = stringliteralstart_state,
    [stringescapeoctal1_state][92] = stringliteralstart_state,
    [stringescapeoctal1_state][93] = stringliteralstart_state,
    [stringescapeoctal1_state][94] = stringliteralstart_state,
    [stringescapeoctal1_state][95] = stringliteralstart_state,
    [stringescapeoctal1_state][97] = stringliteralstart_state,
    [stringescapehexempty_state][46] = stringescapehex_state,
    [stringescapehexempty_state][47] = stringescapehex_state,
    [stringescapehexempty_state][49] = stringescapehex_state,
    [stringescapehexempty_state][50] = stringescapehex_state,
    [stringescapehexempty_state][53] = stringescapehex_state,
    [stringescapehexempty_state][57] = stringescapehex_state,
    [stringescapehexempty_state][58] = stringescapehex_state,
    [stringescapehexempty_state][15] = stringescapehex_state,
    [stringescapehexempty_state][25] = stringescapehex_state,
    [stringescapehexempty_state][26] = stringescapehex_state,
    [stringescapehexempty_state][68] = stringescapehex_state,
    [stringescapehexempty_state][27] = stringescapehex_state,
    [stringescapehexempty_state][28] = stringescapehex_state,
    [stringescapehexempty_state][29] = stringescapehex_state,
    [stringescapehexempty_state][30] = stringescapehex_state,
    [stringescapehexempty_state][82] = stringescapehex_state,
    [stringescapehexempty_state][39] = stringescapehex_state,
    [stringescapehexempty_state][42] = stringescapehex_state,
    [stringescapehexempty_state][59] = stringescapehex_state,
    [stringescapehexempty_state][94] = stringescapehex_state,
    [stringescapehexempty_state][96] = stringescapehex_state,
    [stringescapehexempty_state][97] = stringescapehex_state,
    [stringescapehex_state][1] = stringliteralstart_state,
    [stringescapehex_state][2] = stringliteralstart_state,
    [stringescapehex_state][3] = stringliteralstart_state,
    [stringescapehex_state][4] = stringliteralstart_state,
    [stringescapehex_state][5] = stringliteralstart_state,
    [stringescapehex_state][6] = stringliteralstart_state,
    [stringescapehex_state][7] = stringliteralstart_state,
    [stringescapehex_state][8] = stringliteralstart_state,
    [stringescapehex_state][9] = stringliteralstart_state,
    [stringescapehex_state][10] = stringliteralstart_state,
    [stringescapehex_state][11] = stringliteralstart_state,
    [stringescapehex_state][12] = stringliteralstart_state,
    [stringescapehex_state][13] = stringliteralstart_state,
    [stringescapehex_state][14] = stringliteralstart_state,
    [stringescapehex_state][15] = stringliteralstart_state,
    [stringescapehex_state][16] = stringliteralstart_state,
    [stringescapehex_state][17] = stringliteralstart_state,
    [stringescapehex_state][18] = stringliteralstart_state,
    [stringescapehex_state][19] = stringliteralstart_state,
    [stringescapehex_state][20] = stringliteralstart_state,
    [stringescapehex_state][21] = stringliteralstart_state,
    [stringescapehex_state][22] = stringliteralstart_state,
    [stringescapehex_state][23] = stringliteralstart_state,
    [stringescapehex_state][24] = stringliteralstart_state,
    [stringescapehex_state][25] = stringliteralstart_state,
    [stringescapehex_state][26] = stringliteralstart_state,
    [stringescapehex_state][27] = stringliteralstart_state,
    [stringescapehex_state][28] = stringliteralstart_state,
    [stringescapehex_state][29] = stringliteralstart_state,
    [stringescapehex_state][30] = stringliteralstart_state,
    [stringescapehex_state][31] = stringliteralstart_state,
    [stringescapehex_state][33] = stringliteralstart_state,
    [stringescapehex_state][34] = stringliteralstart_state,
    [stringescapehex_state][35] = stringliteralstart_state,
    [stringescapehex_state][36] = stringliteralstart_state,
    [stringescapehex_state][37] = stringliteralstart_state,
    [stringescapehex_state][39] = stringliteralstart_state,
    [stringescapehex_state][40] = stringliteralstart_state,
    [stringescapehex_state][41] = stringliteralstart_state,
    [stringescapehex_state][42] = stringliteralstart_state,
    [stringescapehex_state][43] = stringliteralstart_state,
    [stringescapehex_state][44] = stringliteralstart_state,
    [stringescapehex_state][45] = stringliteralstart_state,
    [stringescapehex_state][46] = stringliteralstart_state,
    [stringescapehex_state][47] = stringliteralstart_state,
    [stringescapehex_state][48] = stringliteralstart_state,
    [stringescapehex_state][49] = stringliteralstart_state,
    [stringescapehex_state][50] = stringliteralstart_state,
    [stringescapehex_state][51] = stringliteralstart_state,
    [stringescapehex_state][52] = stringliteralstart_state,
    [stringescapehex_state][53] = stringliteralstart_state,
    [stringescapehex_state][54] = stringliteralstart_state,
    [stringescapehex_state][55] = stringliteralstart_state,
    [stringescapehex_state][56] = stringliteralstart_state,
    [stringescapehex_state][57] = stringliteralstart_state,
    [stringescapehex_state][58] = stringliteralstart_state,
    [stringescapehex_state][59] = stringliteralstart_state,
    [stringescapehex_state][60] = stringliteralstart_state,
    [stringescapehex_state][61] = stringliteralstart_state,
    [stringescapehex_state][62] = stringliteralstart_state,
    [stringescapehex_state][63] = stringliteralstart_state,
    [stringescapehex_state][64] = stringliteralstart_state,
    [stringescapehex_state][65] = stringliteralstart_state,
    [stringescapehex_state][66] = stringliteralstart_state,
    [stringescapehex_state][67] = stringliteralstart_state,
    [stringescapehex_state][68] = stringliteralstart_state,
    [stringescapehex_state][69] = stringliteralstart_state,
    [stringescapehex_state][70] = stringliteralstart_state,
    [stringescapehex_state][71] = stringliteralstart_state,
    [stringescapehex_state][72] = stringliteralstart_state,
    [stringescapehex_state][73] = stringliteralstart_state,
    [stringescapehex_state][74] = stringliteralstart_state,
    [stringescapehex_state][75] = stringliteralstart_state,
    [stringescapehex_state][76] = stringliteralstart_state,
    [stringescapehex_state][77] = stringliteralstart_state,
    [stringescapehex_state][78] = stringliteralstart_state,
    [stringescapehex_state][79] = stringliteralstart_state,
    [stringescapehex_state][80] = stringliteralstart_state,
    [stringescapehex_state][81] = stringliteralstart_state,
    [stringescapehex_state][82] = stringliteralstart_state,
    [stringescapehex_state][83] = stringliteralstart_state,
    [stringescapehex_state][84] = stringliteralstart_state,
    [stringescapehex_state][85] = stringliteralstart_state,
    [stringescapehex_state][86] = stringliteralstart_state,
    [stringescapehex_state][87] = stringliteralstart_state,
    [stringescapehex_state][88] = stringliteralstart_state,
    [stringescapehex_state][89] = stringliteralstart_state,
    [stringescapehex_state][90] = stringliteralstart_state,
    [stringescapehex_state][91] = stringliteralstart_state,
    [stringescapehex_state][92] = stringliteralstart_state,
    [stringescapehex_state][93] = stringliteralstart_state,
    [stringescapehex_state][94] = stringliteralstart_state,
    [stringescapehex_state][95] = stringliteralstart_state,
    [stringescapehex_state][96] = stringliteralstart_state,
    [stringescapehex_state][97] = stringliteralstart_state
};

extern enum tokenType stateMachine_correspondingTokens[STATECOUNT] = {
    [cantmove_state] = cantmove_token,
    [charliteralstart_state] = bad_token,
    [charliteral_state] = charliteral_token,
    [charliteralchewedone_state] = bad_token,
    [charliteralescape_state] = bad_token,
    [charescapeoctal0_state] = bad_token,
    [charescapeoctal1_state] = bad_token,
    [charescapehexempty_state] = bad_token,
    [charescapehex_state] = bad_token,
    [nondecimal_state] = octal_token,
    [fraction_state] = fraction_token,
    [octal_state] = octal_token,
    [oct_u_state] = oct_u_token,
    [oct_lu_state] = oct_lu_token,
    [oct_l_state] = oct_l_token,
    [oct_L_state] = oct_l_token,
    [oct_w_state] = bad_token,
    [oct_W_state] = bad_token,
    [oct_ull_state] = oct_ull_token,
    [oct_ul_state] = oct_lu_token,
    [oct_uL_state] = oct_lu_token,
    [oct_uwb_state] = oct_uwb_token,
    [oct_uw_state] = bad_token,
    [oct_uW_state] = bad_token,
    [oct_ll_state] = oct_ll_token,
    [oct_wb_state] = oct_wb_token,
    [hexfraction_state] = hexfraction_token,
    [hexadecimal_state] = hexadecimal_token,
    [hex_u_state] = hex_u_token,
    [hex_lu_state] = hex_lu_token,
    [hex_l_state] = hex_l_token,
    [hex_L_state] = hex_l_token,
    [hex_w_state] = bad_token,
    [hex_W_state] = bad_token,
    [hex_ull_state] = hex_ull_token,
    [hex_ul_state] = hex_lu_token,
    [hex_uL_state] = hex_lu_token,
    [hex_uwb_state] = hex_uwb_token,
    [hex_uw_state] = bad_token,
    [hex_uW_state] = bad_token,
    [hex_ll_state] = hex_ll_token,
    [hex_wb_state] = hex_wb_token,
    [decimalfraction_state] = decimalfraction_token,
    [decimal_state] = decimal_token,
    [decimal_u_state] = decimal_u_token,
    [decimal_lu_state] = decimal_lu_token,
    [decimal_l_state] = decimal_l_token,
    [decimal_L_state] = decimal_l_token,
    [decimal_w_state] = bad_token,
    [decimal_W_state] = bad_token,
    [decimal_ull_state] = decimal_ull_token,
    [decimal_ul_state] = decimal_lu_token,
    [decimal_uL_state] = decimal_lu_token,
    [decimal_uwb_state] = decimal_uwb_token,
    [decimal_uw_state] = bad_token,
    [decimal_uW_state] = bad_token,
    [decimal_ll_state] = decimal_ll_token,
    [decimal_wb_state] = decimal_wb_token,
    [newline_state] = newline_token,
    [lparen_state] = lparen_token,
    [rparen_state] = rparen_token,
    [lcurly_state] = lcurly_token,
    [rcurly_state] = rcurly_token,
    [rbracket_state] = rbracket_token,
    [lbracket_state] = lbracket_token,
    [question_state] = question_token,
    [semicolon_state] = semicolon_token,
    [colon_state] = colon_token,
    [comma_state] = comma_token,
    [dot_state] = dot_token,
    [eof_state] = eof_token,
    [start_state] = bad_token,
    [identifier_state] = identifier_token,
    [modeq_state] = modeq_token,
    [mod_state] = mod_token,
    [minuseq_state] = minuseq_token,
    [arrow_state] = arrow_token,
    [minus_state] = minus_token,
    [xoreq_state] = xoreq_token,
    [caret_state] = caret_token,
    [bnoteq_state] = bnoteq_token,
    [tilde_state] = tilde_token,
    [boreq_state] = boreq_token,
    [lor_state] = lor_token,
    [pipe_state] = pipe_token,
    [eq_state] = eq_token,
    [assignment_state] = assignment_token,
    [pluseq_state] = pluseq_token,
    [plus_state] = plus_token,
    [shiftleft_state] = shiftleft_token,
    [le_state] = le_token,
    [langle_state] = langle_token,
    [shiftright_state] = shiftright_token,
    [ge_state] = ge_token,
    [rangle_state] = rangle_token,
    [div_state] = div_token,
    [linecomment_state] = linecomment_token,
    [blockcomment_state] = bad_token,
    [blockcommentweak_state] = bad_token,
    [blockcommentfinish_state] = blockcomment_token,
    [bandeq_state] = bandeq_token,
    [and_state] = and_token,
    [amp_state] = amp_token,
    [timeseq_state] = timeseq_token,
    [star_state] = star_token,
    [noteq_state] = noteq_token,
    [exc_state] = exc_token,
    [preproc_state] = preproc_token,
    [whitespace_state] = whitespace_token,
    [stringliteral_state] = stringliteral_token,
    [stringliteralstart_state] = bad_token,
    [stringliteralescape_state] = bad_token,
    [stringescapeoctal0_state] = bad_token,
    [stringescapeoctal1_state] = bad_token,
    [stringescapehexempty_state] = bad_token,
    [stringescapehex_state] = bad_token
};

extern unsigned char asciiEnumeration[] = {
    ['s']=1,
    ['?']=2,
    ['Q']=3,
    [']']=4,
    ['~']=5,
    ['l']=6,
    ['r']=7,
    [';']=8,
    ['N']=9,
    ['p']=10,
    ['*']=11,
    ['%']=12,
    ['q']=13,
    ['[']=14,
    ['f']=15,
    ['\r']=16,
    ['<']=17,
    ['\\']=18,
    ['>']=19,
    ['/']=20,
    ['G']=21,
    [' ']=22,
    ['O']=23,
    ['R']=24,
    ['B']=25,
    ['7']=26,
    ['9']=27,
    ['D']=28,
    ['5']=29,
    ['2']=30,
    ['u']=31,
    [255]=32,
    ['W']=33,
    ['U']=34,
    ['x']=35,
    [244]=36,
    ['(']=37,
    ['\n']=38,
    ['d']=39,
    ['z']=40,
    ['H']=41,
    ['C']=42,
    ['+']=43,
    ['M']=44,
    ['K']=45,
    ['A']=46,
    ['e']=47,
    ['w']=48,
    ['6']=49,
    ['b']=50,
    ['L']=51,
    ['{']=52,
    ['c']=53,
    ['P']=54,
    ['g']=55,
    ['!']=56,
    ['3']=57,
    ['8']=58,
    ['E']=59,
    ['V']=60,
    ['=']=61,
    ['t']=62,
    ['j']=63,
    ['J']=64,
    ['h']=65,
    ['m']=66,
    ['Y']=67,
    ['4']=68,
    ['|']=69,
    ['-']=70,
    ['"']=71,
    ['n']=72,
    ['I']=73,
    ['.']=74,
    ['S']=75,
    ['^']=76,
    ['\t']=77,
    ['#']=78,
    [')']=79,
    ['o']=80,
    [':']=81,
    ['0']=82,
    ['T']=83,
    ['X']=84,
    ['&']=85,
    ['_']=86,
    ['y']=87,
    ['i']=88,
    ['v']=89,
    [',']=90,
    ['\'']=91,
    ['k']=92,
    ['Z']=93,
    ['F']=94,
    ['}']=95,
    ['1']=96,
    ['a']=97
};

